### ISSUE TITLE
Question: How to handle self modifying code with DSE ?

### ISSUE THREAD

**Issue by kamou** [cea-sec/miasm#1001]
Hi,
I'm trying to perform dse on some self modifying code.

At some point, the binary will mmap some rwx region, and store code in it, execute it, then rewrite the code and rexecute it:
first code:
```
0x20000040: movabs    rax, 0x5210
0x2000004a: call      rax
```

second code (same basic block address):
```
0x20000040: movabs    r13, 0x500
0x2000004a: movabs    rax, 0x20000080
0x20000054: jmp       rax
```
during the emulation of the second code, at the first instruction I get the following exception: 
```
miasm.analysis.dse.DriftException: Drift of RAX: 21008 instead of 536870976
```
where 21008 is 0x5210 and 536870976 is 0x20000040

Seems like miasm expects that block to contain the previously executed code.
Is there a way to avoid this behaviour ? Should I let miasm know at some point that the block it tries to execute have changed ?

**Comment by kamou** [comment]
I guess the jitter exception EXCEPT_CODE_AUTOMOD could be used to help the DSE, but I'm not sure what I could do to help DSE emulate the new version of the rewriten basic block...

**Comment by commial** [comment]
Hello,

In fact, the `EXCEPT_CODE_AUTOMOD` is already used by the jitter to remove jitted block concerned by a memory write. So it's working for the concrete part (as you mentioned).
But, the DSE engine is using a cache to avoid translating Asm -> IR for already seen blocks. The code in charge is https://github.com/cea-sec/miasm/blob/master/miasm/analysis/dse.py#L340.
You can, for a first step, remove this cache use and see if it fixes the problem.

**Comment by kamou** [comment]
Perfect, Thanks ! I will have a look at that this weekend
