### ISSUE TITLE
Default mapping of CALL_FINISH_ADDR in jitter virtual memory?

### ISSUE THREAD

**Issue by icecr4ck** [cea-sec/miasm#1006]
Hello,
This is more a question than an issue, isn't the address 0x13371ACC (CALL_FINISH_ADDR) should be mapped in virtual memory by default? Because I'm always getting a `RuntimeError: Cannot find address` each time I play with the Sandbox `call` method.
Thanks!

**Comment by icecr4ck** [comment]
Hum seems the problem is actually related to the way the `printf` function is handled, for the particular program I am running, the format string given to the `printf` looks like "%s\n%s\n" so the `get_fmt_args` function looks for 2 string pointers on the stack and there is only one... (disclaimer: I'm not the developer of this program)

**Comment by commial** [comment]
Hello!
This is actually one of the reason we do not mapped the address: seeing it popping in error is often a good way to know there is an error in the code, or a misunderstanding of the stack depth.

**Comment by icecr4ck** [comment]
Indeed! I will close this one, it's more related to the program itself anyway, sorry for the noise!

**Comment by commial** [comment]
No problem, issues are also made for questions :)
