### ISSUE TITLE
miasm compile with error on mac

### ISSUE THREAD

**Issue by wxq491216** [cea-sec/miasm#1009]
i pull the newest code and compile it with "python setup.py build", the bellow error earch occur:

> miasm/jitter/vm_mngr_py.c:1003:3: error: void function 'initVmMngr' should not return a value [-Wreturn-type]
                return NULL;
                ^      ~~~~
miasm/jitter/vm_mngr_py.c:1006:3: error: void function 'initVmMngr' should not return a value [-Wreturn-type]
                return NULL;
                ^      ~~~~
miasm/jitter/vm_mngr_py.c:1010:3: error: void function 'initVmMngr' should not return a value [-Wreturn-type]
                return NULL;
                ^      ~~~~
miasm/jitter/vm_mngr_py.c:1012:2: error: void function 'initVmMngr' should not return a value [-Wreturn-type]
        return module;

**Comment by serpilliere** [comment]
Right!
We have some ugly codes remaining in C modules.
They were warnings here, but anyway: we will fix them in a near future.
Thank you for the feed back @wxq491216 !

**Comment by serpilliere** [comment]
Hey @wxq491216, can you confirm us the the new master fixes the build on MacOS?

**Comment by wxq491216** [comment]
there still has some errors like this:

```
miasm/jitter/vm_mngr_py.c:776:24: error: use of undeclared identifier '__BIG_ENDIAN'
        self->vm_mngr.sex   = __BIG_ENDIAN;
                              ^
miasm/jitter/vm_mngr_py.c:784:24: error: use of undeclared identifier '__LITTLE_ENDIAN'
        self->vm_mngr.sex   = __LITTLE_ENDIAN;
                              ^
miasm/jitter/vm_mngr_py.c:793:27: error: use of undeclared identifier '__BIG_ENDIAN'
        if (self->vm_mngr.sex == __BIG_ENDIAN) {
```

**Comment by serpilliere** [comment]
Maybe one day someone with a mac will fix this :smile:
