### ISSUE TITLE
Increase the stack size initialized by the Jitter?

### ISSUE THREAD

**Issue by icecr4ck** [cea-sec/miasm#1013]
Hello,

By default the size of the stack initialized by the jitter is 0x10000, do you think you could increase it to avoid `WARNING: address XXX is not mapped in virtual memory` errors for programs using heavily the stack? As an example, I recently went through an obfuscated binary executing the following instructions:
```asm
PUSH       RBP
MOV        RBP, RSP
PUSH       RBX
SUB        RSP, 0xBA4A8
...
```
Thanks 🙏

**Comment by commial** [comment]
Hello,

Even if we increase the default stack size, it might continue to not be enough for certain use, or too much to dump and analyze.
We usually set the stack size per script, depending on the target needs, using `Sandbox_XXX.STACK_SIZE`

You just need to adjust this value *before* instantiating the Sandbox. You can also play with `STACK_BASE` if needed.

Hope it helps

**Comment by icecr4ck** [comment]
Indeed it definitely makes sense! I hadn't seen the `Sandbox_XXX.STACK_SIZE`, I thought the stack size was only set by the Jitter my bad :)
