### ISSUE TITLE
Fine-grained control over optimization pipeline

### ISSUE THREAD

**Issue by dwuid** [cea-sec/miasm#1019]
Following up on #1000, I noticed some unintuitive behavior when performing SSA-based DCE.

My goal is to perform proper DCE on miasm's IR while keeping the correspondence to the underlying native instructions. Hence, if an optimization discards all IR effects of a native instruction, I want to eliminate that specific instruction, but keep all others.

With @serpilliere's approach, outlined in #1000, a problem arises. As the optimization pipeline is fixed, miasm will eventually propagate IR expressions, constants and the like, which breaks the abovementioned correspondence (native instructions are referenced in `AssignBlocks`, but not in individual expressions).

Take this slightly obfuscated assembly sequence for example:
```
MOV        EAX, DWORD PTR [R9]
STC        
XOR        EAX, R10D
DEC        EAX
XOR        EAX, 0xDEADBEEF
ROR        EAX, 0x1
TEST       CH, 0x76
BSWAP      EAX
NEG        EAX
ROL        EAX, 0x3
BSWAP      SI
XOR        DWORD PTR [RSP], EAX
POP        RBX
JMP        RBX
```

I performed two simplification runs, one with miasm's default pipeline and one with expression propagation disabled in a rather unergonomic way. While the IR is true to the semantics in the first case, we lose information for the native instructions:
```
==== W/ propagation: ====================================================================

---- IR  --------------------------------------------------------------------------------
@32[RSP] = @32[RSP] ^ ((-{((((@32[R9] ^ R10[0:32]) + 0xFFFFFFFF) ^ 0xDEADBEEF) >>> 0x1)[24:32] 0 8, ((((@32[R9] ^ R10[0:32]) + 0xFFFFFFFF) ^ 0xDEADBEEF) >>> 0x1)[16:24] 8 16, ((((@32[R9] ^ R10[0:32]) + 0xFFFFFFFF) ^ 0xDEADBEEF) >>> 0x1)[8:16] 16 24, ((((@32[R9] ^ R10[0:32]) + 0xFFFFFFFF) ^ 0xDEADBEEF) >>> 0x1)[0:8] 24 32}) <<< 0x3)
RBX.0 = @64[RSP]
IRDst = RBX.0

---- x64 --------------------------------------------------------------------------------
XOR        DWORD PTR [RSP], EAX
POP        RBX
JMP        RBX

==== W/o propagation: ===================================================================

---- IR  --------------------------------------------------------------------------------
RAX.0 = zeroExt_64(@32[R9])
RAX.1 = zeroExt_64(R10[0:32] ^ RAX.0[0:32])
RAX.2 = zeroExt_64(RAX.1[0:32] + 0xFFFFFFFF)
RAX.3 = zeroExt_64(RAX.2[0:32] ^ 0xDEADBEEF)
RAX.4 = zeroExt_64(RAX.3[0:32] >>> 0x1)
RAX.5 = zeroExt_64({RAX.4[24:32] 0 8, RAX.4[16:24] 8 16, RAX.4[8:16] 16 24, RAX.4[0:8] 24 32})
RAX.6 = zeroExt_64(-RAX.5[0:32])
RAX.7 = zeroExt_64(RAX.6[0:32] <<< 0x3)
@32[RSP] = @32[RSP] ^ RAX.7[0:32]
RBX.0 = @64[RSP]
IRDst = RBX.0

---- x64 --------------------------------------------------------------------------------
MOV        EAX, DWORD PTR [R9]
XOR        EAX, R10D
DEC        EAX
XOR        EAX, 0xDEADBEEF
ROR        EAX, 0x1
BSWAP      EAX
NEG        EAX
ROL        EAX, 0x3
XOR        DWORD PTR [RSP], EAX
POP        RBX
JMP        RBX
```

With the ability to disable or parameterize specific optimizations, miasm would be way more flexible. I get that the abovementioned use case is a bit unusual, but more control over the optimization process cannot hurt. :)

Ideally, miasm would expose an interface to override optimization functions such as `propagation_allowed`.

What do you think?

**Comment by dwuid** [comment]
(Pasting full test case as file attachments don't seem to work.)
```python

from miasm.arch.x86.ira import ir_a_x86_64
from miasm.arch.x86.disasm import dis_x86_64
from miasm.analysis.simplifier import IRCFGSimplifierSSA

import miasm.arch.x86.regs as x86_regs


class MyArch(ir_a_x86_64):
    def __init__(self, location_db):
        ir_a_x86_64.__init__(self, location_db)

    def get_out_regs(self, ir_block):
        return {x86_regs.RAX, x86_regs.RBX}


class MyArchSSA(MyArch):
    def __init__(self, location_db):
        ir_a_x86_64.__init__(self, location_db)

    def get_out_regs(self, ir_block):
        registers = super(MyArchSSA, self).get_out_regs(ir_block)

        collect = {}
        for assignment in ir_block:
            for dst in assignment:
                reg = self.ssa_var.get(dst, None)
                if reg in registers:
                    collect[reg] = dst

        registers = set(collect.values())
        return registers


def print_ir_cfg(cfg):
    for loc, block in cfg.blocks.iteritems():
        for assign in block:
            print(assign)


def print_native(cfg):
    for loc, block in cfg.blocks.iteritems():
        for assign in block:
            print(assign.instr)


def setup():
    code = ''.join('''
        41 8B 01
        F9
        41 33 C2
        FF C8
        35 EF BE AD DE
        D1 C8
        F6 C5 76
        0F C8
        F7 D8
        C1 C0 03
        66 0F CE
        31 04 24
        5B
        FF E3
    '''.split()).decode('hex')

    disasm = dis_x86_64(code)
    arch = MyArch(disasm.loc_db)

    asm_cfg = disasm.dis_multiblock(0)
    location = asm_cfg.loc_db.get_offset_location(0)
    cfg = arch.new_ircfg_from_asmcfg(asm_cfg)

    return arch, cfg, location


def no_propagation_allowed(_self, _ssa, _to_replace, _node_a, _node_b):
    return False


def optimize():
    arch, cfg, location = setup()

    arch_ssa = MyArch(arch.loc_db)
    simplifier = IRCFGSimplifierSSA(arch_ssa)
    simplifier.simplify(cfg, location)

    print('\n---- IR  ' + '-' * 80)
    print_ir_cfg(cfg)

    print('\n---- x64 ' + '-' * 80)
    print_native(cfg)


def main():
    print('\n==== W/ propagation: ' + '=' * 68)
    optimize()

    # Ugly hack to disable propagation for `ExprId` objects.
    from miasm.analysis.data_flow import PropagateThroughExprId
    PropagateThroughExprId.propagation_allowed = no_propagation_allowed

    print('\n==== W/o propagation: ' + '=' * 67)
    optimize()


if __name__ == '__main__':
    main()
```

**Comment by serpilliere** [comment]
I think I sse your point.

For your information,  we are working on a more cleaner simplifier. We are using this branch:
https://github.com/serpilliere/miasm/tree/clean_simplifier

We are trying here to clean the simplifier to match generic cases of simplifications. You can remove/add simplification passes by directly manipulate them in the passes list or by subclass it.

The goal is provide basic bricks, which can be joined together to match your need.
For example, if you do not want the expression propagation, you remove it from the list.

And if the whole simplifier class does not fit your need, you can make your own by picking some simplification passes from `data_flow`

We are currently trying this with some users to see if it responds to most needs.
If you are motivated, join the party :smile: 
Actually, we have tried it on (at least) #954 and #955 samples.

The interesting part for you may be in https://github.com/serpilliere/miasm/blob/clean_simplifier/miasm/analysis/simplifier.py

**Comment by serpilliere** [comment]
You can now subclass the `IRCFGSimplifier` or the `IRCFGSimplierSSA` (see https://github.com/serpilliere/miasm/blob/master/miasm/analysis/simplifier.py) in order to select the passes you want to enable/disable, like:
```python
class CustomSimplifier(IRCFGSimplifierCommon):
    def init_passes(self):
        self.passes = [
            self.do_dead_simp_ircfg,
        ]
```
Fell free to re open this issue
