### ISSUE TITLE
Add option to fully drop SSA indices

### ISSUE THREAD

**Issue by dwuid** [cea-sec/miasm#1020]
Currently, when converting into and out of SSA form, the remaining IR still maintains version information for `ExprId` objects (e.g., `RAX.42` instead of a plain `RAX`). This is perfectly sound and fine for most applications, but proves to be disadvantageous for some use cases.

For example, when symbolically executing such an IR block, the SE engine keeps state _per versioned register_ (e.g., `RAX.42`, `RAX.3`, `RAX`, ...), which makes tracking effects of a particular register more challenging (as we now need to distinguish the registers versions as well). In many cases, there might not be a need to track these intermediate expressions.

I came up with the following to drop all indices but it's rather costly. Is there a better way to drop these indices somewhere else in the process?

```python
def drop_index(expr):
    if isinstance(expr, (ExprLoc, ExprInt)):
        return expr

    if isinstance(expr, ExprId):
        # Actually drop the version.
        return ExprId(expr.name.split('.')[0], expr.size)

    if isinstance(expr, ExprAssign):
        return ExprAssign(drop_index(expr.dst), drop_index(expr.src))

    if isinstance(expr, ExprMem):
        return ExprMem(drop_index(expr.ptr), expr.size)

    if isinstance(expr, ExprOp):
        args = iter(drop_index(arg) for arg in expr.args)
        return ExprOp(expr.op, *args)

    if isinstance(expr, ExprCompose):
        args = iter(drop_index(arg) for arg in expr.args)
        return ExprCompose(*args)

    if isinstance(expr, ExprCond):
        return ExprCond(drop_index(expr.cond), drop_index(expr.src1),
                        drop_index(expr.src2))

    if isinstance(expr, ExprSlice):
        return ExprSlice(drop_index(expr.arg), expr.start, expr.stop)

    assert False, 'Unsupported expression: {}.'.format(repr(expr))


def drop_indices(cfg):
    for location, block in cfg.blocks.iteritems():
        new_assignments = []
        for assignment in block:
            new_irs = {
                    drop_index(k): drop_index(v)
                    for k, v in assignment.iteritems()
            }

            new_assignments.append(AssignBlock(new_irs, assignment.instr))

        new_block = IRBlock(block.loc_key, new_assignments)
        cfg.blocks[location] = new_block
```

Thanks for your input!

**Comment by serpilliere** [comment]
Hi @dwuid !
The use of the symbolic execution in the SSA world seems a bit strange to me. I don't see a use case of it. For example: How to you handle the `Phi` operator in symbolic execution ? Which source do you use? In a case of a oop for example?

Maybe you want to go back in a classic world by using the Un-SSA algorithm of Miasm? (https://github.com/cea-sec/miasm/blob/master/miasm/analysis/outofssa.py#L19)

Maybe I have missed something here :confused:

**Comment by commial** [comment]
Hi there,
Well, IMHO, it does have a signification along a path. SE being an execution, the notion of path could be defined, and then Phi might be resolved.

But this is something we do not have for now (path tracking in SE). And I'm not fully convinced by the benefit of it, compared to doing the SE on the Out of Ssa form.

In addition, the equality between versionned  Id of the same variable doesn't always stand. Some transformation in the SSA world will create interferences between these variables. And this is something the Out of SSA algorithm is meant to deal with

**Comment by dwuid** [comment]
I think there might have been a misunderstanding, let me try to re-phrase the question. I am not trying to symbolically execute in SSA form.

Consider a simple x86-64 sequence such as the following:
```
mov rax, 0xdeadbeef
inc rax
inc rax
inc rax
ret
```

I convert this sequence into SSA form (in order to perform certain transformations) and then **out of** SSA form again:
```python
ssa = simplifier.ircfg_to_ssa(cfg, location)
# Optimizations may happen here...
cfg = simplifier.ssa_to_unssa(ssa, location)
```

This yields something along the following (I removed flag effects for readability):
```
RAX.0 = 0xDEADBEEF
RAX.1 = RAX.0 + 0x1
RAX.2 = RAX.1 + 0x1
RAX.3 = RAX.2 + 0x1
IRDst = @64[RSP[0:64]]
RSP.0 = RSP[0:64] + 0x8
```
Note how `ExprId`s for `RAX` still have version information, which is _sound_, but not fully out-of-SSA either.

If I now symbolically execute this sequence, the state is updated with intermediate computations of `RAX.0`, `RAX.1`, `RAX.2`, `RAX.3` as well. This is fine, but it causes overhead if you are not interested in the intermediate steps. Also, you would have to figure out that `RAX.3` is the most recent version.

If the out-of-SSA conversion would have dropped the indices, the SE state would only yield one single computation for `RAX` (just as it would have done if one symbolically executed the `cfg` before any SSA transformations).

Ih short, the original `cfg` and `out_of_ssa(into_ssa(cfg))` are not equivalent.

**Comment by commial** [comment]
Thanks for the details.
> In short, the original cfg and out_of_ssa(into_ssa(cfg)) are not equivalent.

Indeed! And there are not meant to be equivalent.
Actually, we lack a global coalescing pass, which would be able to detect that the several RAX can coalesce together. IMHO, it is the best way to address this issue, because it would also have benefit for simplifications in other situations

**Comment by dwuid** [comment]
Thanks! The lack of coalescing explains the current situation. Also agreed that this is the sanest way to fix it.

**Comment by serpilliere** [comment]
Ok here is some information which may be usefull:
- the SSA structure owns a field which is called `self.ssa_variable_to_expr` which links the "indexed register" to its original register, ie `{RAX.0 => RAX, RAX.1 => RAX, ...}`
- to do its job, the `DeadRemoval` compute two things: the first one is to note 'important varaibels' to keep through the analysed function. The second one is to note recursively each computation which gives a data node computed in the first step. To do the first step, the algorithm known "original important" register, ie EAX, ESP, ... and back track SSA variables *linked* to them through the `self.ssa_variable_to_expr` starting from the leaves of the function.

Then, @dwuid , if you do a DeadRemoval pass before symbolic execution, in your example, RAX.3 will be noted as important register, *but* RAX.2 computation is kept, then RAX.1, ...

**Comment by dwuid** [comment]
Thanks, @serpilliere, `ssa_variable_to_expr` certainly makes things easier in this regard.

**Comment by serpilliere** [comment]
Are we ok to close this issue @dwuid ?

**Comment by dwuid** [comment]
Yes, closing this for now until someone revisits variable coalescing.
