### ISSUE TITLE
The dearth of documentation.

### ISSUE THREAD

**Issue by ianamason** [cea-sec/miasm#1032]
I know that it is a TODO item. But it would be really nice if the blog examples were updated so
that they work with the latest code base.  Especially the detailed the two CGC ones.
[1](https://miasm.re/blog/2016/01/27/re150.html) and [2]( https://miasm.re/blog/2016/03/24/re150_rebuild.html).

On a related note, I would like to see an example of where, instead of overwriting the original binary, and in [2]( https://miasm.re/blog/2016/03/24/re150_rebuild.html), you 
```
...
we can add a custom section containing our code, and modify the entry point to jump on it;
```

**Comment by commial** [comment]
Hello,

I'm not sure we will have the time to maintain the blog code examples. The corresponding working Miasm version is usually also in the the blog post, so the results can be reproduced. Not saying we will not, but this is not the priority for now.
There are code base which we do maintain: the examples (`/examples`) and regression tests (`/tests`). We encourage people to have a look at them (especially `examples`): they should provides example of use of the different Miasm APIs. The blog is more an illustration the framework capabilities / fun use cases.

Regarding the example you quote, you can base yourself on the example `example/elfesteem/test_pe.py`, which add a new section to a PE and set the entrypoint on it:
```Python
s_text = e_.SHList.add_section(
    name="text", addr=0x1000, rawsize=0x1000, data=mysh)
e_.Opthdr.AddressOfEntryPoint = s_text.addr
```

Hope it helps.
