### ISSUE TITLE
Failed to decode aarch64 instruction 'ldarb'

### ISSUE THREAD

**Issue by BlackLuny** [cea-sec/miasm#1039]
In /test/arch/aarch64/arch.py, I added a new item in 'reg_tests_aarch64'
("XXXXXXXX    LDARB     W0, [X20]", "80FEDF08")

But there have something wrong while decoding.It's a bug?
the error info is:
XXXXXXXX     80FEDF08
Traceback (most recent call last):
  File "D:\miasm-master\miasm-master\test\arch\aarch64\arch.py", line 1841, in <
module>
    mn = mn_aarch64.dis(b, 'l')
  File "C:\Python27\lib\site-packages\miasm\core\cpu.py", line 1249, in dis
    ret = f.decode(todo[i])
  File "C:\Python27\lib\site-packages\miasm\arch\aarch64\arch.py", line 529, in
decode
    size = 64 if self.parent.sf.value else 32
AttributeError: 'ldarb' object has no attribute 'sf'

**Comment by serpilliere** [comment]
Thank you for the feedback @BlackLuny !
You are right: It seems the destination register is always 32 bit so: can you confirm it's ok for you with:
```diff
diff --git a/miasm/arch/aarch64/arch.py b/miasm/arch/aarch64/arch.py
index d12fbe724..33c1d427d 100644
--- a/miasm/arch/aarch64/arch.py
+++ b/miasm/arch/aarch64/arch.py
@@ -2152,7 +2152,7 @@ aarch64op("ldxp", [bs('1'), sf, bs('001000'), bs('0'), bs('1'), bs('1'), bs('111
 
 # load acquire/store release p.141
 aarch64op("ldar", [bs('1'), sf, bs('001000'), bs('1'), bs('1'), bs('0'), bs('11111'), bs('1'), bs('11111'), rn64_deref_nooff, rt], [rt, rn64_deref_nooff])
-aarch64op("ldarb",[bs('0'), bs('0'), bs('001000'), bs('1'), bs('1'), bs('0'), bs('11111'), bs('1'), bs('11111'), rn64_deref_nooff, rt], [rt, rn64_deref_nooff])
+aarch64op("ldarb",[bs('0'), bs('0'), bs('001000'), bs('1'), bs('1'), bs('0'), bs('11111'), bs('1'), bs('11111'), rn64_deref_nooff, rt32], [rt32, rn64_deref_nooff])
 aarch64op("ldarh",[bs('0'), bs('1'), bs('001000'), bs('0'), bs('1'), bs('0'), bs('11111'), bs('1'), bs('11111'), rn64_deref_nooff, rt], [rt, rn64_deref_nooff])
 aarch64op("ldaxp",[bs('1'), sf, bs('001000'), bs('0'), bs('1'), bs('1'), bs('11111'), bs('1'), bs('11111'), rn64_deref_nooff, rt], [rt, rn64_deref_nooff])
 aarch64op("ldaxr",[bs('1'), sf, bs('001000'), bs('0'), bs('1'), bs('0'), bs('11111'), bs('1'), bs('11111'), rn64_deref_nooff, rt], [rt, rn64_deref_nooff])
```

**Comment by BlackLuny** [comment]
Thanks.It works for me.But did't implement the semantics.So I use 'ldr' to replace it.
