### ISSUE TITLE
Question: a release with python3 ?

### ISSUE THREAD

**Issue by Summus6** [cea-sec/miasm#1046]
Hello everyone !
I really enjoy the work you did on miasm, and moreover about the python3 compatibility !
But python3 compatibility was not available in the release v0.1.1

When can we expect a new release so we can upgrade our code in python3 ? :)
Or do you think the actual state of miasm (master) is stable enough ?

Thank you !

**Comment by serpilliere** [comment]
I planned to include the #1025 for the next release: it introduces some new objects that we are testing for some times now (see the PR), but it's still in development...
So if you are using something liked to code simplification, maybe you will have to wait some more times. Anything else should not move for now.

Anyway, maybe the plan is to far away and we have enough modifications without #1025 to launch the v0.1.2 .

**Comment by Summus6** [comment]
Thank you for your answer !
I'm not using it so I will begin to upgrade my code waiting the release :)

Have a good day
