### ISSUE TITLE
MSP430's SR register

### ISSUE THREAD

**Issue by stan1slas** [cea-sec/miasm#1054]
Hello !

I'm currently trying to emulate some msp430 opcodes using the jit_msp430 engine, and I'm facing a small problem regarding the SR register. It looks like this register isn't accessible during the emulation. 

This probably comes from https://github.com/cea-sec/miasm/blob/master/miasm/jitter/arch/JitCore_msp430.h#L2 where the declaration of SR register is missing.

However, in https://github.com/cea-sec/miasm/blob/master/miasm/arch/msp430/sem.py#L166, it looks like SR register is properly used during the emulation.

Is there a way to access the value of this register ? Should we add it to the declaration of `struct vm_cpu` ?

Thanks for miasm !

**Comment by serpilliere** [comment]
Hi @stan1slas !
Currently the msp430 is a bit like on x86 with the eflag.
We decided to implement it as the group of flags (zf, nf, cf, ...) instead of a full register, so you directly cannot use it. You have to modify every of its flags.

**Comment by stan1slas** [comment]
Hi !
Thanks for the information, I close the issue.
