### ISSUE TITLE
Setup is not working

### ISSUE THREAD

**Issue by ericsia** [cea-sec/miasm#1073]
Correct me if I'm wrong, you are suppose to open the setup.py on first use right?
I got
 line 162, in <module>
    buil_all()
  File "/home//Desktop/miasm-0.1.1/setup.py", line 126, in buil_all
    raise ValueError("Unable to build Miasm!")
ValueError: Unable to build Miasm!

I tried it in both linux and windows, I'd like to find the bug but unfortunately I not know how python work
for linux:
miasm2/jitter/vm_mngr.h:31:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~

hmm it's better to just release the binary/compiled version

**Comment by serpilliere** [comment]
Hi @ericsia !
As explained in the README, you have to install python-dev (which provides python.h)
