### ISSUE TITLE
Does it support aarch64 floating-point arithmetic?

### ISSUE THREAD

**Issue by DobeReverser** [cea-sec/miasm#1111]
When disassembling instructions with floating point registers, the following situation occurs.

WARNING: cannot disasm (guess) at 103B6671C
WARNING: cannot disasm at 103B6671C
WARNING: cannot disasm (guess) at 103B6671C
WARNING: cannot disasm at 103B6671C

__text:0000000103B66718 E8 57 00 F9                 STR             X8, [SP,#0x5D60+var_5CB8]
__text:0000000103B6671C 28 04 00 0F                 MOVI            V8.2S, #1
__text:0000000103B66720 88 BE 00 90                 ADRP            X8, #xmmword_105336ED0@PAGE

**Comment by serpilliere** [comment]
Hi @DobeReverser 
Yes: ARM is not fully supported yet, and soe instructions are missing at the moment :disappointed:

**Comment by DobeReverser** [comment]
@serpilliere 

May I know when you plan to add support for the soe instructions?

**Comment by serpilliere** [comment]
Hum. @DobeReverser : We don't have real "plans". Let say we will try before 2020.

**Comment by DobeReverser** [comment]
got it
