### ISSUE TITLE
aarch46 UMINV instruction not supported

### ISSUE THREAD

**Issue by chago** [cea-sec/miasm#1113]
The UMINV instruction need Intermediate variables to implement ir in sem.py, so it's not support in current  framework?

the maxmin variables

C6.3.316 UMINV

bits(datasize) operand = V[n]; integer maxmin;
integer element;
maxmin = Int(Elem[operand, 0, esize], unsigned); 
for e = 1 to elements-1
    element = Int(Elem[operand, e, esize], unsigned);
    maxmin = if min then Min(maxmin, element) else Max(maxmin, element); 
V[d] = maxmin<esize-1:0>;

**Comment by serpilliere** [comment]
Are you sure to *need* intermediate variables?
Si for example: https://github.com/cea-sec/miasm/blob/master/miasm/arch/x86/sem.py#L4938

**Comment by serpilliere** [comment]
Ho, sorry, I mislead on the instruction comprehension. I will check this @chago !

**Comment by serpilliere** [comment]
Ok, so let say we have to compute: min(a, b, c)
(with a, b, c parts of the in vector)
We could generate something like:
```
(a < b) ? (
    (
	(a < c) ? (a:c)
    )
    :
    (
	(b < c) ? (b:c)
    )
)


```
But it seems it will be painful with a big vector (for example 8 elements)

**Comment by serpilliere** [comment]
Maybe we can add the operator `imin/imax` and 'umin/umax'. This can be interesting both many point of view:
- for "high level" recovery
- simplify IR representation

The ir of this instruction may become something like:
```
R1 = ExprOp("umin", R0[0:8], R0[8:16], R0[16:24], R0[24:32])
```

**Comment by chago** [comment]
Thanks~
