### ISSUE TITLE
Translate ircfg or ssa back to assembly suitable for compilation

### ISSUE THREAD

**Issue by winniepe** [cea-sec/miasm#1146]
Hi there,
Is there a way to translate ircfg or ssa back to assembly and compile?

I'm trying to disassemble a function, lift to ir/ssa, perform some optimization passes, translate back to same architecture, and assemble/compile.
I've looked at export_llvm but generated ll code has too many artifacts for the compiled code to be close to original or very useful.

Thanks!

**Comment by serpilliere** [comment]
The basic answer is no.
But it is possible to lift the assembly code, translate to IR, *simplify* it, and then generate llvm code. The generated code will in fact work on "fake" registers, but if you have the ABI of the function you are analyzing, you can use it in your generated llvm code, and the code will be close to the original one.

**Comment by serpilliere** [comment]
Feel free to reopen the issue if something is not clear here.
