### ISSUE TITLE
Remove Python 2 support

### ISSUE THREAD

**Issue by XVilka** [cea-sec/miasm#1152]
Python 2 is [dead](https://pythonclock.org/) and will not be updated anymore. Moreover, many distributions started to remove it from the packages. Would be nice to remove Python 2 remnants from miasm and use something like [Black](https://github.com/psf/black) to conform a better style.

**Comment by serpilliere** [comment]
Hi @XVilka !
Yes, but we still have:
- some machines running old stable distribs
- ghidra scripts which runs python though jython, which only supports python2

So for now, we will keep the support.
