### ISSUE TITLE
Add the "read" analogue of the "modified" generator in SymbolicExecutionEngine

### ISSUE THREAD

**Issue by XVilka** [cea-sec/miasm#1176]
Currently you can get the variables modified with:
```python
for var, val in symex.modified(mems=False):
     print("{0}  <= {1}".format(var, val)
```
The `var` values are usable as is, but `val` are often wrapped in the `ExprOp`, `ExprMem`, etc.
It would be nice to have a similar function but returning the "pure" source registers without symbolizing operations on top of these.
Something like
```python
for var in symex.read(mems=False):
     print(var)
```

**Comment by serpilliere** [comment]
Hi @XVilka 
In fact, when you have `var = val`, with `var` something like `@32[EAX]` maybe you want `EAX` as well?

So your solution already exists in Miasm:
```python
for dst, src in symb.modified(mems=True):
    a = ExprAssign(dst, src)
    print("read:", [str(x) for x in a.get_r(mem_read=True)])
```
For `"MOV EAX, DWORD PTR [EBX + ECX]"`
```
read: ['@32[EBX + ECX]', 'EBX', 'ECX']
read: []
```
 
for `"MOV DWORD PTR [EBX + ECX], EAX"`:
```
read: []
read: ['ECX', 'EBX', 'EAX']
```

I am not sure if it worth adding another "shortcut" API, as it seems already 'short'.
Do you agree with this?

**Comment by XVilka** [comment]
Thanks, makes sense.

**Comment by serpilliere** [comment]
no problemo @XVilka
