### ISSUE TITLE
IR serialize

### ISSUE THREAD

**Issue by sparkyparrot** [cea-sec/miasm#1194]
Hello,

Im looking on how to store miasm IR, lets say I want to load up a file and get directly a block of expression like:
A=1
B=2
C=A+B
Is there currently anyway to store/load IR or would I have to implement my own serializer/deserializer to be able to load up expressions ?
Im not talking about asm conversion, I just want to be able to load/store expressions.

Thanks.

**Comment by serpilliere** [comment]
Do you mean serialization?
You can use pickle:
```python
from miasm.expression.expression import *
import pickle

a = ExprId('a', 32)
cst = ExprInt(1, 32)
op = a + cst

data = pickle.dumps(op)
print(repr(data))

x = pickle.loads(data)
print(repr(x))
```
