### ISSUE TITLE
stwcx. in PPC raise AssertionError in ir.py

### ISSUE THREAD

**Issue by IridiumXOR** [cea-sec/miasm#1206]
Hi there is a problem with the opcode "stwcx." in PPC.
"stwcx." calls mn_do_store() in sem.py and in `if is_stwcx:`
the assignment 
```
additional_ir = [ IRBlock(loc_do, [ AssignBlock(ret) ]),
                          IRBlock(loc_dont, [ AssignBlock(dont) ]) ]
```
uses loc_do which is an `ExprLoc` object not a `LocKey` object as requested by `IRBlock`.
I'm not friendly with IR internals so, please can you fix it?
Here a script to reproduce the bug

```
from miasm.ir.symbexec import SymbolicExecutionEngine
from miasm.analysis.machine import Machine
from miasm.analysis.binary import Container

c = Container.from_string(b"\x7c\x80\x19\x2d") # stwcx.  %r4,0,%r3
machine = Machine("ppc32b")
mdis = machine.dis_engine(c.bin_stream)
asmcfg = mdis.dis_multiblock(0)
ira = machine.ira(asmcfg.loc_db)

iracfg = ira.new_ircfg_from_asmcfg(asmcfg)

miasm/ir/ir.py", line 327, in __init__
    assert isinstance(loc_key, m2_expr.LocKey)
AssertionError
```

**Comment by serpilliere** [comment]
Hi @IridiumXOR ,
There was a "typo":
the `IRBlock` creation takes a "loc_key". And the code was actually giving an `ExprLoc`.
But you can get the loc_key of an `ExprLoc` (using `expr.loc_key`)

**Comment by IridiumXOR** [comment]
Thank you
