### ISSUE TITLE
Loading (debug) symbols

### ISSUE THREAD

**Issue by mrphrazer** [cea-sec/miasm#1219]
Hi guys,

it's a while :)

Did you ever come across the use case of automatically loading/reading debug symbols (e.g, from functions or global arrays) such that they can be  accessed/parsed in miasm? As a workaround, I would externally parse the addresses to acces it, but perhaps there already exists a smarter way?

Best,

phrazer

**Comment by serpilliere** [comment]
Hi @mrphrazer !

We miss this in miasm for now... The way we are using to have "debug names" is to open the binary in IDA, export the symbols name in a pickle, and load it in the locationdb before disassembling the binayr...
Yes, it's a shame :cry:

**Comment by commial** [comment]
Hi,

It's not that much, but the Container also parse symbols and add them to
its LocationDB.

You can try dumping a loc_db of a Container ELF and see if it is enough for
you needs.

**Comment by mrphrazer** [comment]
Hi,

thanks! With that I wasn't able to access global data structures etc. :( My workaround is to query `nm` and feed the symbols into Miasm. Quick hax 4 life!

Best,

phrazer
