### ISSUE TITLE
Invalid symbolization of x86-64 [BSWAP Reg16] behaviour.

### ISSUE THREAD

**Issue by can1357** [cea-sec/miasm#1236]
I'm not familiar with this repo so will not touch any code, but wanted to let you know that [this ](https://github.com/cea-sec/miasm/blob/master/miasm/arch/x86/sem.py#L1162) is invalid. 

`BSWAP Reg16` is explicitly said to be undefined in the `Intel® 64 and IA-32 Architectures Software Developer Manuals` and seems to zero-out in real world from what I've seen from 6 CPUs.

**Comment by serpilliere** [comment]
Oh! Thank you for the tip @can1357 
Sadly for now, in Miasm we don't have a good way to represent undefined behaviors.
But maybe we can change the semantic to reflect a real cpu.
