### ISSUE TITLE
README example of symbolic execution not working

### ISSUE THREAD

**Issue by heinrich5991** [cea-sec/miasm#1268]
I tried following the steps of the README:

```python
from miasm.analysis.binary import Container
from miasm.analysis.machine import Machine
from miasm.arch.x86.arch import mn_x86
from miasm.core.locationdb import LocationDB
from miasm.ir.symbexec import SymbolicExecutionEngine

EXAMPLE_BYTES = b'\x8dI\x04\x8d[\x01\x80\xf9\x01t\x05\x8d[\xff\xeb\x03\x8d[\x01\x89\xd8\xc3'

def main():
    loc_db = LocationDB()
    c = Container.from_string(EXAMPLE_BYTES)
    machine = Machine("x86_32")
    mdis = machine.dis_engine(c.bin_stream)
    asmcfg = mdis.dis_multiblock(0)
    ira = machine.ira(loc_db)
    ircfg = ira.new_ircfg_from_asmcfg(asmcfg)
    sb = SymbolicExecutionEngine(ira)
    symbolic_pc = sb.run_at(ircfg, 0, step=True)
    print(symbolic_pc)

    sb = SymbolicExecutionEngine(ira, machine.mn.regs.regs_init)
    print(sb.run_at(ircfg, 0, step=True))
```

But I only get the following:
```
0
0
```

The README tells me that I should expect something like `((ECX + 0x4)[0:8] + 0xFF)?(0xB,0x10)` for the first line, and many more lines after that.

I'm running this on Arch Linux, I installed miasm via the [AUR package python-miasm-git](https://aur.archlinux.org/packages/python-miasm-git/) which installed the latest master (currently https://github.com/cea-sec/miasm/commit/a1c2dcbf6c4f3191984a781119d131c7c7f8d9ad).

**Comment by serpilliere** [comment]
Ok, here is the bug: In Miasm, you can only work with *one location db*.
This is "bad".
I mean, in a ghostbusters style, like  "don't cross the streams"
(https://www.youtube.com/watch?v=wyKQe_i9yyo)

In the readme, we make the demo of multiple different features: and in some cases, we are generating a new locationdb, and others no. When generating the `dis_engine` we only gave the `bin_stream` (source of bytes), but we don't give any `locationdb`.
In this case, the disasm engine generates it's own new fresh locationdb.
Thus, we have two different `locationdb` in the script which is bad (you know, like in 


Your point is very interesting as it's not the first time someone do this.
And it's very hard to debug, as nothing seems to go wrong.
It seems that the very original problem is that the disassembler engine should *not* generate any locationdb, but take it as mandatory argument.

This will avoid such cases.

What do you think ?

**Comment by heinrich5991** [comment]
Changing
```python
    ira = machine.ira(loc_db)
```
to
```python
    ira = machine.ira(mdis.loc_db)
```
did the trick.

Complete working code:

```python
from miasm.analysis.binary import Container
from miasm.analysis.machine import Machine
from miasm.arch.x86.arch import mn_x86
from miasm.core.locationdb import LocationDB
from miasm.ir.symbexec import SymbolicExecutionEngine

EXAMPLE_BYTES = b'\x8dI\x04\x8d[\x01\x80\xf9\x01t\x05\x8d[\xff\xeb\x03\x8d[\x01\x89\xd8\xc3'

def main():
    loc_db = LocationDB()
    c = Container.from_string(EXAMPLE_BYTES)
    machine = Machine("x86_32")
    mdis = machine.dis_engine(c.bin_stream)
    asmcfg = mdis.dis_multiblock(0)
    ira = machine.ira(mdis.loc_db)
    ircfg = ira.new_ircfg_from_asmcfg(asmcfg)
    sb = SymbolicExecutionEngine(ira)
    symbolic_pc = sb.run_at(ircfg, 0, step=True)
    print(symbolic_pc)
```

> This will avoid such cases.

Mh, my first try was to use the `loc_db` from the Container, that also didn't work. (I realize that you even spelled it out for me, that I need to take `loc_db` from the `dis_engine`.)

I think a good first step would be to improve the README.md so that copying the code from there works.

Given that you're only allowed to use exactly one location db, changing constructors to not generate one on-demand might be a good way to stop newbies like me from producing more than one.

**Comment by heinrich5991** [comment]
Thanks!

**Comment by serpilliere** [comment]
Noproblemo @heinrich5991 
Thanks to you for the issue!
