### ISSUE TITLE
Wrong docs

### ISSUE THREAD

**Issue by archercreat** [cea-sec/miasm#1270]
Why are the auto generated docs for miams2? Shouldn't they be updated?

**Comment by serpilliere** [comment]
Hi @archercreat !
Which documentation are you talking about?
Today, the (very limited) documentation is in the directory `doc` of the repository of miasm.
We renamed miasm2 into miasm some years ago: we now use real versions for now, see in the https://github.com/cea-sec/miasm/releases

**Comment by archercreat** [comment]
Hello, I'm talking about auto generated docs which are located here: https://miasmdoc.ajax.re/
It looks like they are for really old miasm version and some entries are not present in new miasm.

**Comment by commial** [comment]
My bad, indeed, it has been built a long time ago.
FYI, it only reflects the comments already available in the code, it is only a graphical abstract of them.

I'll update them.

**Comment by archercreat** [comment]
Thank you 👍

**Comment by p-l-** [comment]
@commial you may also want to have a look to your certificate, by the way.

**Comment by serpilliere** [comment]
The documentation has been update on the README!
