### ISSUE TITLE
Disassembling armv7-m

### ISSUE THREAD

**Issue by mrphrazer** [cea-sec/miasm#1281]
Hi there! 

When disassembling an armv7-m binary, the disassembler seems to have problems (the example hardcodes the main, but it behaves the same on all other addresses)

Expected:

```
.text:0800023C                 PUSH    {R7,LR}
.text:0800023E                 ADD     R7, SP, #0
.text:08000240                 BL      func
```

Output:

```
[WARNING ]: cannot disasm (guess) at 8000240
[WARNING ]: cannot disasm at 8000240
loc_800023c
SVCGE      0xB580
->      c_next:loc_8000240 
```

Code:

```python
from miasm.analysis.binary import Container
from miasm.analysis.machine import Machine
from miasm.core.locationdb import LocationDB

file_path =  "main.elf"
start_addr = 0x0800023C

loc_db = LocationDB()
container = Container.from_stream(open(file_path, 'rb'), loc_db)
machine = Machine(container.arch)
mdis = machine.dis_engine(container.bin_stream, loc_db=loc_db)

block = mdis.dis_block(start_addr)
print(block)
```

Do you have any idea what is going on?

Best,

mrphrazer

[binary.zip](https://github.com/cea-sec/miasm/files/5150479/binary.zip)

**Comment by serpilliere** [comment]
Hi @mrphrazer 
It seems the default machine extracted from the elf is:
```python
>>> machine.name
'arml'
>>> 
```

But the real machine is arml thumb as it seems your code is in arm thumb...
The quick fix is to fix this in the command line:
```shell
python -i  miasm/example/disasm/full.py -m armtl main.elf  0x0800023C
```

In theory, the architecture is good, (arml) but we might disassemble at an odd address to explicit the thumb hint.
But miasm doesn't do the swith between thumb/arm if we give an odd address...
So for the moment, the quick fix is the best fix :cry:

**Comment by mrphrazer** [comment]
Hey @serpilliere 

awesome, thanks! I assumed sth like that but wasn't sure.

It works fine now.

Best
