### ISSUE TITLE
add_instr_to_ircfg call add_asmblock_to_ircfg everytime lead to an assertion error while processing subcall instructions.

### ISSUE THREAD

**Issue by bluestar628** [cea-sec/miasm#1287]
I am analyzing a mips-32 ELF using miasm and I want to represent all instruction in LLVM IR format.
 
Here is my code:

with open(path) as json_file:
        data = json.load(json_file)
        for block in data[0]['blocks']:
            for op in block['ops']:
                logging.debug(op["bytes"])
                bytes_op = bytes.fromhex(op["bytes"])
                opinstr = mn.dis(bytes_op,"b")
                logging.debug(opinstr)
                ira.add_instr_to_ircfg(opinstr, ircfg)

I stored all instructions of each function in a single json file. I traverse all instructions and try to add all of them into an ircfg. However, when I encounter a "jalr t9 (\x03\x20\xf8\x09)" instruction(a subcall), an assertion error occurred. The error messages are:
 "  File "/home/zyx/anaconda3/envs/tf/lib/python3.8/site-packages/miasm/arch/mips32/ira.py", line 50, in add_asmblock_to_ircfg
    assert index == len(block.lines) - 2
AssertionError"
When I read the source code, I found that the add_instr_to_ircfg in ir.py calls the add_asmblock_to_ircfg in ira.py. And the assert checks whether a subcall is the last but one instruction. However, the add_asmblock_to_ircfg just create a block with one instruction, how could this instruction be the last but one instruction?

**Comment by bluestar628** [comment]
Just use the 

asmcfg = mdis.dis_multiblock(func_addr)  
ircfg = ir.new_ircfg_from_asmcfg(asmcfg)

to generate the ircfg for the whole function.

**Comment by serpilliere** [comment]
So the problem is solved, right ?
