### ISSUE TITLE
link same irblock multiple times

### ISSUE THREAD

**Issue by archercreat** [cea-sec/miasm#1291]
Hi! Is there a painless way to link same basic block in ircfg? 
i.e. Lets say I have a function with blocks: `block A -> block B -> block C` and I want to represent ircfg as `block A -> block B -> block A -> block A ...`
This is relevant in virtual machine reversing when each basic block represent some opcode and you want to link them together.

**Comment by serpilliere** [comment]
Hi @archercreat 
Sorry, but I am afraid I didn't understand the question.
Can you elaborate a bit more ?

**Comment by archercreat** [comment]
Sure, lets say I have the "vm" that processes opcodes:

```cpp
int a;

int vm(int opcode) {
  switch (opcode)
  {
  case 0:
    a++;
    break;
  case 1:
    a--;
    break;
  case 2:
    a ^= 0x69;
    break;
  default:
    break;
  }   
}
```
And the following ircfg:
![](https://user-images.githubusercontent.com/41573188/93914473-49a35880-fd0f-11ea-9b46-2e25a28e8e8a.png)

In ircfg blocks `loc_686`, `loc_664`, `loc_675` are opcode handlers.
Since I know the bytecode (e.g. 0, 0, 1, 2) I want to build ircfg like this: `loc_664` -> `loc_664` -> `loc_675` -> `loc_686`

I can link those blocks together no problem, but I can not link same block (`loc_664`) to itself since it creates a loop.

**Comment by serpilliere** [comment]
Ok, I think I have understood the question.
Stop me during the explanation here if something is wrong:
- *you* have the information of which block is next to which one (Miasm doesn't have it here.)
- so you know their labels and the sequence in which they are executer.

The goal is then to:
- get the block associated to each address of the new sequence
- generate new loc_key for each block
- reset the destination of each block to then "next" block you want to link


Here is a code started from the `dis_binary_ira.py`:
```python
from __future__ import print_function
import sys

from future.utils import viewvalues
from miasm.analysis.binary import Container
from miasm.analysis.machine import Machine
from miasm.core.locationdb import LocationDB
from miasm.ir.ir import IRCFG, IRBlock
from miasm.expression.expression import ExprLoc
from miasm.analysis.simplifier import IRCFGSimplifierCommon

#####################################
# Common section from dis_binary.py #
#####################################

fdesc = open(sys.argv[1], 'rb')
loc_db = LocationDB()

cont = Container.from_stream(fdesc, loc_db)

machine = Machine(cont.arch)

mdis = machine.dis_engine(cont.bin_stream, loc_db=cont.loc_db)

addr = 0x1119
asmcfg = mdis.dis_multiblock(addr)

#####################################
#    End common section             #
#####################################

# Get an IRA converter
# The sub call are modelised by default operators
# call_func_ret and call_func_stack
ir_arch_analysis = machine.ira(mdis.loc_db)

head = loc_db.get_offset_location(addr)

# Get the IR of the asmcfg
ircfg = ir_arch_analysis.new_ircfg_from_asmcfg(asmcfg)

# Simplify graph
ircfg_simplifier = IRCFGSimplifierCommon(ir_arch_analysis)
ircfg_simplifier.simplify(ircfg, head)


####### CUSTOM CODE ########"
addrs = [0x115C, 0x113a, 0x114b]
blocks = []
addr_to_block = {}


new_ircfg = IRCFG(ircfg.IRDst, loc_db)

new_sequence = [0x115C, 0x115C, 0x115C, 0x113a, 0x114b]

# Prepare loc for new bloc
new_loc = loc_db.add_location()
for addr in new_sequence:
    loc = loc_db.get_offset_location(addr)
    block = ircfg.blocks[loc]


    # Set new loc_key
    new_block = IRBlock(loc_db, new_loc, block.assignblks)
    # Set new destination and link to future block
    new_loc = loc_db.add_location()
    new_block = new_block.set_dst(ExprLoc(new_loc, ircfg.IRDst.size))
    blocks.append(new_loc)

    new_ircfg.add_irblock(new_block)

open('out.dot', 'w').write(new_ircfg.dot())

# Bonus, simplify out graph
ircfg_simplifier.simplify(new_ircfg, head)

open('out_new.dot', 'w').write(new_ircfg.dot())
```

The original ircfg (a bit different from yours as we may use different compilers):
![g_orig](https://user-images.githubusercontent.com/9433661/93991413-8f523680-fd8c-11ea-9202-aaa859c5dce0.png)
The new generated graph:
![g_out](https://user-images.githubusercontent.com/9433661/93991430-9711db00-fd8c-11ea-8248-5076ce83fe53.png)
Note that the last label is missing, as we didn't set a final block to end the sequence.
The new generated and simplified graph:
![g_out_new](https://user-images.githubusercontent.com/9433661/93991453-9f6a1600-fd8c-11ea-9baa-634291b260da.png)
(note that we only used simple simplificator here, without SSA optimisations)

So regarding the code: Can you tell me if you find the code too complicated regarding to the API ?  For me, the code reflects more or less the points we described previously. Have you got some 'shortcuts' you wish to be in the API to simplify this ?

**Comment by archercreat** [comment]
Can't thank you enough for the explanation! Regarding the API there is really nothing to simplify. My case is more complicated then just relinking the blocks, but I see now how it is done right.

**Comment by serpilliere** [comment]
Noproblemo @archercreat 
May I close the issue ?

**Comment by archercreat** [comment]
yup
