### ISSUE TITLE
keep stack restore instructions after ssa simplification

### ISSUE THREAD

**Issue by tly000** [cea-sec/miasm#1320]
Hi everyone,

Is there a way to keep the stack restoration pop instructions even when simplifying with the SSA simplifier? 

This is the CFG of the input assembly:
[cfg.pdf](https://github.com/cea-sec/miasm/files/5643369/cfg.pdf)

Then i simplify it using the following code:
```python
ir_arch = IRADelModCallStack(loc_db)
ircfg = ir_arch.new_ircfg_from_asmcfg(cfg)
simplifier = IRCFGSimplifierSSA(ir_arch)
simplifier.simplify(ircfg, ircfg.heads()[0])
```
This is the CFG of the optimized IRCFG
[ircfg.pdf](https://github.com/cea-sec/miasm/files/5643370/ircfg.pdf)

The following block and similar blocks vanish, because its not used by the function:
```
pop     edi
pop     esi
pop     ebp
pop     ebx
```

**Comment by serpilliere** [comment]
Hi @tly000 !

Yes!
By default, Miasm on keeps (for x86) the EAX and ESP registers.
But you can tell Miasm that you care about all general purpose registers. To do so, you have to surcharge the `get_out_regs` of you ira class. Here is a simple example:
```python
from __future__ import print_function
import sys

from future.utils import viewvalues
from miasm.analysis.binary import Container
from miasm.analysis.machine import Machine
from miasm.core.locationdb import LocationDB
from miasm.ir.ir import AssignBlock
from miasm.expression.expression import ExprInt, ExprMem, ExprOp, ExprAssign
from miasm.arch.x86 import regs

fdesc = open(sys.argv[1], 'rb')
loc_db = LocationDB()

cont = Container.from_stream(fdesc, loc_db)

machine = Machine(cont.arch)


class CustomCallIRA(machine.ira):
    def get_out_regs(self, _):
        return set(
            [
                regs.EAX, regs.EBX, regs.ECX, regs.EDX,
                regs.ESI, regs.EDI,
                regs.ESP, regs.EBP,
            ]
        )

mdis = machine.dis_engine(cont.bin_stream, loc_db=cont.loc_db)
addr = cont.entry_point
asmcfg = mdis.dis_multiblock(addr)

# Get a custom IRA converter
ir_arch_analysis = CustomCallIRA(mdis.loc_db)

# Get the IR of the asmcfg
ircfg_analysis = ir_arch_analysis.new_ircfg_from_asmcfg(asmcfg)

# Display each IR basic blocks
for irblock in viewvalues(ircfg_analysis.blocks):
    print(irblock)

# Output ir control flow graph in a dot file
open('bin_ira_cfg.dot', 'w').write(ircfg_analysis.dot())
```

**Comment by serpilliere** [comment]
With the folliwing code:
```
main:
	PUSH EAX
	PUSH EBX
	PUSH ECX
	PUSH EDX
	POP EDX
	POP ECX
	POP EBX
	POP EAX
	RET
```
it gives (if you add the simplifications and propagation and ssa stuffs:
![final](https://user-images.githubusercontent.com/9433661/101186814-dfcef580-3653-11eb-8bf2-f456e130ef31.png)

**Comment by tly000** [comment]
thanks 🙂  this is exactly what i needed, this way it could be possible to detect if a register is callee-saved.
