### ISSUE TITLE
Result of expression propagation is not deterministic

### ISSUE THREAD

**Issue by tly000** [cea-sec/miasm#1322]
Hi,

I think i found a bug, that changes when i slightly change around the code before or after the simplification by IRCFGSimplifierSSA.
I use the following code to simplify the ircfg:

```python
import pickle
import os
import sys

from miasm.expression.expression import ExprWalk
from miasm.analysis.simplifier import IRCFGSimplifierSSA
from miasm.analysis.machine import Machine

def verify_esp_propagation(cfg):
    # search for all read accesses via the ESP.n register.
    # after the SSA optimization, no name of the form ESP.n should still read by the function
    walker = ExprWalk(lambda expr: True if expr.is_id() and expr.name.startswith("ESP.") else None)
    for loc_key, irblock in ircfg.blocks.items():
        for assignblock in irblock.assignblks:
            for read_access in assignblock.get_r():
                if walker.visit(read_access):
                    raise RuntimeError("esp propagation failed")

    print("ok")

ircfg = pickle.load(open("ircfg.dat", 'rb'))
assert len(ircfg.heads()) == 1
simplifier = IRCFGSimplifierSSA(Machine('x86_32').ira(ircfg.loc_db))
newircfg = simplifier.simplify(ircfg, ircfg.heads()[0])
#assert newircfg != None

verify_esp_propagation(newircfg)
```

Depending on whether i add the `assert newircfg != None`  call or not, the function verify_esp_propagation will raise an exception or print ok. In the following zip file you can find the "ircfg.dat" file and two pdfs of the wrongly and correctly simplified ircfg graphs.

[ircfg.zip](https://github.com/cea-sec/miasm/files/5668590/ircfg.zip)

Edit: I think the reason might be, that somewhere in the simplification code, an `__eq__` function uses the memory addresses of the python objects instead of a deep comparison.

**Comment by serpilliere** [comment]
Hi @tly000,
Interesting!
Can you provide the binary, or a blanked binary (except the current function)
The will be very helpfull for the debugging
Thanks for the issue!

**Comment by serpilliere** [comment]
Hi @tly000 !
You are right. It seems the `DelDummyPhi` simplifier is to blame.
I re wrote it using equivalence class test, and this should to the trick.
Can you try your code using the following branch:
https://github.com/serpilliere/miasm/tree/fix_del_dummy_phi

Tell me if it's ok or if some problems still remain.
I definitively need to add regression tests for the propagation / simplification part.

**Comment by tly000** [comment]
Thank you very much for the update 🙂 Now almost all functions work as expected, but i found one that worked in the master branch and does not with the new version. Here is the binary:

```python
binary = bytearray(11266520)
offset = 108448
l = [0x56, 0x33, 0xf6, 0xe8, 0xb8, 0x1e, 0x0, 0x0, 0x85, 0xc0, 0x75, 0x2, 0x5e, 0xc3, 0xa1, 0x0, 0x9a, 0xd, 0x0, 0x85,
     0xc0, 0x75, 0x4, 0x33, 0xc0, 0x5e, 0xc3, 0xc7, 0x5, 0xf8, 0x99, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x68, 0xe0, 0x76,
     0xab, 0x0, 0xe8, 0xb1, 0x90, 0xfe, 0xff, 0x83, 0xc4, 0x4, 0x83, 0xf8, 0x1, 0xf, 0x85, 0xb1, 0x0, 0x0, 0x0, 0xa1,
     0xfc, 0x76, 0xab, 0x0, 0x46, 0x85, 0xc0, 0xf, 0x84, 0x89, 0x0, 0x0, 0x0, 0x50, 0xe8, 0x11, 0x1b, 0x0, 0x0, 0x83,
     0xc4, 0x4, 0x85, 0xc0, 0x7d, 0x34, 0x66, 0xa1, 0x4, 0x77, 0xab, 0x0, 0x66, 0x83, 0xf8, 0x21, 0x74, 0x28, 0x66,
     0x83, 0xf8, 0x22, 0x74, 0x22, 0x66, 0x83, 0xf8, 0x28, 0x74, 0x1c, 0x66, 0x83, 0xf8, 0x20, 0x74, 0x16, 0xa1, 0x18,
     0xad, 0xd, 0x0, 0x85, 0xc0, 0x74, 0x62, 0xa1, 0xfc, 0x76, 0xab, 0x0, 0x50, 0xe8, 0x28, 0x1a, 0x0, 0x0, 0xeb, 0x52,
     0x66, 0xa1, 0x6, 0x77, 0xab, 0x0, 0x66, 0x85, 0xc0, 0x74, 0x31, 0x8b, 0x15, 0xfc, 0x76, 0xab, 0x0, 0x33, 0xc9,
     0x66, 0x8b, 0xc8, 0x51, 0x52, 0xe8, 0xc9, 0x0, 0x0, 0x0, 0x8b, 0xd, 0xfc, 0x76, 0xab, 0x0, 0x33, 0xc0, 0x66, 0xa1,
     0x6, 0x77, 0xab, 0x0, 0x83, 0xc4, 0x8, 0x50, 0x51, 0xe8, 0xf1, 0x0, 0x0, 0x0, 0x83, 0xc4, 0x8, 0x85, 0xc0, 0x75,
     0x19, 0x68, 0xe0, 0x76, 0xab, 0x0, 0xe8, 0x30, 0x0, 0x0, 0x0, 0xeb, 0xa, 0x68, 0xe0, 0x76, 0xab, 0x0, 0xe8, 0x74,
     0x0, 0x0, 0x0, 0x83, 0xc4, 0x4, 0xa1, 0xf8, 0x99, 0xd, 0x0, 0x85, 0xc0, 0xf, 0x84, 0x39, 0xff, 0xff, 0xff, 0xe8,
     0xdf, 0xaf, 0x0, 0x0, 0x8b, 0xc6, 0x5e, 0xc3, 0x8d, 0xa4, 0x24, 0x0, 0x0, 0x0, 0x0, 0x8d, 0x64, 0x24, 0x0]
binary[offset:offset + len(l)] = l
```

**Comment by serpilliere** [comment]
You are right.
I removed the handling of a case which was managed by the previous version.
I now have a better view of those cases and got an idea to deal with all of them (at least, I hope)
I will implement this in a short time.

**Comment by tly000** [comment]
thanks again for your help.

**Comment by serpilliere** [comment]
Hi @tly000 !
I repushed another version of the algorithm.
It seems to work on both functions.
Can you tell me that's is ok for you ?

Don't hesitate to tell me if you have others bad cases!

**Comment by tly000** [comment]
hi, i ran into the `assert len(successors) == 1` and the `print("BAD %s" % src)` output on multiple functions. would it be ok for you if i sent you a bunch of functions to test the new version?

**Comment by serpilliere** [comment]
yep fine!

**Comment by serpilliere** [comment]
ok, I forgot a debug stuff. My fault.

**Comment by serpilliere** [comment]
you may try removing the print and the "fds"

**Comment by tly000** [comment]
hi, i tested a lot of functions and the error seems to be fixed. i cannot reproduce the assertion error for now, so this could have been an error on my side. I found some assignments of the form `ESP.22 = ESP.22 + 0xFFFFFFD8`. I this a valid assignment after the ssa optimization?

**Comment by serpilliere** [comment]
Hi @tly000 
In fact, when the code goes out of SSA after all simplifications and propagations, phi registers are merged into a random register, which can be an ssa registers. So yes, this is legit

**Comment by tly000** [comment]
thanks! i think we can close this now, i found another problem with the value propagation bug i think its best to open a new issue.

**Comment by serpilliere** [comment]
Do you think it's linked to the deletion of phi nodes?

**Comment by tly000** [comment]
i dont know because i dont actually understand how all this stuff works 😆

**Comment by serpilliere** [comment]
Noproblemo. I have spotted the problem :+1: 
Your remarks leads to the following PR:
- #1329: dont propagate nul division 
- #1330: fix dummy phi
- #1331: allow propagation of expressions using undefs

Thank you for your feedback @tly000 !

**Comment by tly000** [comment]
youre welcome! and thanks for all the help.
