### ISSUE TITLE
Upon a memory access exception or on a memory breakpoint, get the faulty memory address

### ISSUE THREAD

**Issue by Meow-ops** [cea-sec/miasm#1327]
Using a x86 sandbox, I tried using both a memory breakpoint or catching memory access exceptions. But when doing that I did not find a way of getting easily the targetted memory address.

**Comment by serpilliere** [comment]
Hi @Meow-ops 
Can you be a bit more precise:
What are you trying to do exactly?
Retrieving the address touched during a memory breakpoint ?

You have an example of this in:
https://github.com/cea-sec/miasm/blob/master/test/jitter/mem_breakpoint.py

**Comment by Meow-ops** [comment]
Yes this example is what I was looking for. I should have looked at those tests a bit more.
Thank you for your time and answer.

**Comment by serpilliere** [comment]
noproblemo @Meow-ops !
