### ISSUE TITLE
Some problems with `sb` & `sh` instruction when get_ir with arch mips32

### ISSUE THREAD

**Issue by THUzxj** [cea-sec/miasm#1361]
Thank you for your great work. 
I met this problem:
```shell
ir_arch.add_asmblock_to_ircfg(block,ircfg)
  File "...\python\miasm\arch\mips32\lifter_model_call.py", line 65, in add_asmblock_to_ircfg
    split = self.add_instr_to_current_state(
  File "...\python\miasm\ir\analysis.py", line 82, in add_instr_to_current_state
    assignblk, ir_blocks_extra = self.instr2ir(instr)
  File "...\python\miasm\ir\ir.py", line 745, in instr2ir
    ir_bloc_cur, extra_irblocks = self.get_ir(instr)
  File "...\python\miasm\arch\mips32\sem.py", line 632, in get_ir
    instr_ir, extra_ir = get_mnemo_expr(self, instr, *args)
  File "...\python\miasm\arch\mips32\sem.py", line 618, in get_mnemo_expr
    instr, extra_ir = mnemo_func[instr.name.lower()](ir, instr, *args)
TypeError: sb() takes 2 positional arguments but 4 were given
```
And then I looked through the [source code](https://github.com/cea-sec/miasm/blob/master/miasm/arch/mips32/sem.py#L215-L225), I found that the function `sb` and `sh` are different with others. 
```python
def sb(arg1, arg2):
    """The least significant byte of @arg1 is stored at the specified address
    @arg2."""
    e = []
    e.append(m2_expr.ExprMem(arg2.ptr, 8), arg1[:8])
    return e, []

def sh(arg1, arg2):
    e = []
    e.append(m2_expr.ExprMem(arg2.ptr, 16), arg1[:16])
    return e, []
```
They can't be called normally like other functions, and obviously there is a bug that `list.append(obj)` is called with not only 1 argument. 

I tried adding `@sbuild.parse` but failed, but I think that code in [this commit](https://github.com/cea-sec/miasm/commit/6a9b83cb26fc6f169374caa130b3ea0148d17028) might work normally.
This code can also run under my test.
```python
def sb(ir, instr, arg1, arg2):
    """The least significant byte of @arg1 is stored at the specified address
    @arg2."""
    e = []
    e.append(m2_expr.ExprAssign(m2_expr.ExprMem(arg2.ptr, 8), arg1[:8]))
    return e, []

def sh(ir, instr, arg1, arg2):
    e = []
    e.append(m2_expr.ExprAssign(m2_expr.ExprMem(arg2.ptr, 16), arg1[:16]))
    return e, []
```
Please check this problem, thank you for your work again.

**Comment by serpilliere** [comment]
Hi @THUzxj 
Oh, nice catch!

Your analyze is good: I made a mistake when updating the code and forgot to modify the function API as you suggested.
Do you want to do the PR, or do you prefer I patch it ?
Thankt again @THUzxj

**Comment by THUzxj** [comment]
OK, I'll open a PR later😋

**Comment by serpilliere** [comment]
Thank you again for the PR @serpilliere , I am closing the issue
