### ISSUE TITLE
Sandbox_Win_x86_32 peb_struct Can't work well

### ISSUE THREAD

**Issue by solitudecc** [cea-sec/miasm#1387]
#init sandbox
  options.jitter = "llvm"
    options.loadbasedll = True
    options.dependencies = False
    options.singlestep = False
    options.use_windows_structs = True
    sb = Sandbox_Win_x86_32(loc_db, "StringXor07.exe", options)

#error 
WARNING: address 0x7FF70004 is not mapped in virtual memory:
jitter EIP:4133E8
A jitter exception occurred: DO_NOT_UPDATE_PC & ACCESS_VIOL (0x2004000)

eax == fs[0x18]
004133E8 | 8B40 04                  | mov eax,dword ptr ds:[eax+4]                                      |

**Comment by serpilliere** [comment]
Hi @solitudecc 
We didn't implement a whole windows so it happens that missing structures appears here and there.
We have only implemented basic (and incomplete) peb, teb, ...
So here is a hint:
If you encounter a binary which manipulates structures out of what is implemented and you know what is inside those structures, you can add a page (using `vm.add_memory_page`) and add data to it.
This way you will be able to continue the execution.

The important point is that we have seen the program is manipulating such structures.

**Comment by solitudecc** [comment]
ok,thank you @v@
