### ISSUE TITLE
Cannot deserialize IRCFG with Pickle.load

### ISSUE THREAD

**Issue by molgryn** [cea-sec/miasm#1410]
I want to serialize and save ircfg into file to cache the result.
But I encountered error when I try to load a pickled ircfg.

Tested on Python 3.9.0 and Miasm with commit: 3f3385ef21df3d108d573bcf8d299b645eff8c91

```python
from miasm.analysis.machine import Machine
from miasm.core.locationdb import LocationDB
from miasm.analysis.binary import Container
from miasm.core.cpu import *
import pickle
from miasm.analysis.binary import Container

machine = Machine('x86_64')
loc_db = LocationDB()
dis_engine, ira = machine.dis_engine, machine.lifter_model_call
c = Container.from_string(bytes([0x90, 0x90, 0xc3]), loc_db)
mdis = dis_engine(c.bin_stream, loc_db=loc_db)

addr = 0
asmcfg = mdis.dis_multiblock(addr)

ira = machine.lifter_model_call(asmcfg.loc_db)
ircfg = ira.new_ircfg_from_asmcfg(asmcfg)

PICKLE_PATH = "test.p"
with open(PICKLE_PATH, "wb") as f:
    pickle.dump(ircfg, f)
    print(type(ircfg))
with open(PICKLE_PATH, "rb") as f:
    a = pickle.load(f)
    print(a)
```

Above code raises the following error:
```
Traceback (most recent call last):
  File "d:\work\test.py", line 25, in <module>
    a = pickle.load(f)
AttributeError: 'instruction_x86' object attribute 'delayslot' is read-only
```

**Comment by serpilliere** [comment]
Hi @molgryn 
I looked a bit around, and it seems this can be resolved by initializing the slots of the instruction instance, right?
https://stackoverflow.com/questions/820671/python-slots-and-attribute-is-read-only
I didn't try it yet

**Comment by molgryn** [comment]
Thanks, I'm able to solve this problem by initializing `delayslot` inside of `__init__`  method.

```diff
diff --git a/miasm/arch/x86/arch.py b/miasm/arch/x86/arch.py
index ae58e69b..6875b87d 100644
--- a/miasm/arch/x86/arch.py
+++ b/miasm/arch/x86/arch.py
@@ -465,9 +465,9 @@ class additional_info(object):
 
 class instruction_x86(instruction):
     __slots__ = []
-    delayslot = 0
 
     def __init__(self, *args, **kargs):
+        self.delayslot = 0
         super(instruction_x86, self).__init__(*args, **kargs)
 
     def v_opmode(self):
```

Now it works!

**Comment by serpilliere** [comment]
Ok!
Thank you for the feed back.
I did a little PR #1412 but the fix is a little bit different:
I set the default delayslot value ine the parent class (instruction)
So only class with a delayslot different from it will have to set it in the custom class __init__
I am waiting for the regression tests to complete to see if it's ok on all architectures

**Comment by serpilliere** [comment]
Ok, #1412 has been merged: it should now work in master branch
