### ISSUE TITLE
miasm in Rust

### ISSUE THREAD

**Issue by Ch3nYe** [cea-sec/miasm#1411]
Hi, Is it still in progress to rewrite miasm with rust, I want to join this job. If it has been abandoned, could I get some code or guideline on rewirting?

**Comment by serpilliere** [comment]
Hi @Ch3nYe 
No, it's not abandoned.
We will do some code cleaning and improvement on it in the next months in order to make it public.

**Comment by Ch3nYe** [comment]
@serpilliere get it, What's the cause? Is rust not suitable for miasm, If so please let me know. And looking forward to source code.

**Comment by Ch3nYe** [comment]
@serpilliere Happy to know it, hope a preview release as soon as possible. 😘
