### ISSUE TITLE
How to recover switch cases?

### ISSUE THREAD

**Issue by X3eRo0** [cea-sec/miasm#1413]
How do we recover the control flow when there are jump tables? for example, The switch cases are implemented using jump tables.
Miasm does not handle this very well. It leaves the disassembly at the indirect jump ("jmp rax" for example, rax is calculated to be the case to execute for a particular switch value). Can we do it by lifting the code in miasm ir? Any ideas?

**Comment by mrexodia** [comment]
You can try something like this:

1. Symbolically execute the basic block(s) before the indirect jump
2. Extract symbolic expression for `rax`
3. Add a constraint `rax != 0xffffffffffffffff` (an impossible destination)
4. Make z3 solve
5. Evaluate the expression for rax with the counter example
6. Add a constraint `rax != found_destination`
7. Go to `4` until z3 finds no more destinations

**Comment by X3eRo0** [comment]
Thanks i will take a look :)

**Comment by commial** [comment]
Hi, you might also want to have a look at the ModularInterval classes.
If the computing expressions are basics enough, it should be able to give
you the list of interval of possible values
