### ISSUE TITLE
'llvmlite' python module not recognized inside miasm 

### ISSUE THREAD

**Issue by csgaee** [cea-sec/miasm#1416]
llvmlite 0.31.0 is the version to work with Python 2.7 ..  and i'm already installed it
and while running test_all.py it show this 
![image](https://user-images.githubusercontent.com/29278636/154978936-4c491cd6-84c6-4e9f-ac36-16417be69b08.png)

**Comment by serpilliere** [comment]
Hi @csgaee

**Comment by serpilliere** [comment]
Did you checked your llvm install matches your llvmlite version?

**Comment by csgaee** [comment]
it's solved by switching to python 3 ... seems that "llvmlite 0.31.0 " don't work with llvm installed as you said @serpilliere
