### ISSUE TITLE
How to draw a single block?

### ISSUE THREAD

**Issue by itewqq** [cea-sec/miasm#1451]
I'm handling a large function,. the `lifter.new_ircfg_from_asmcfg` way is too slow and the generated graph is too big for easy reading. So how to draw only a single (or serveral) block(s) in admcfg/ircfg? Didn't get any idea from the doc.

**Comment by serpilliere** [comment]
Hi @itewqq 
If you are interested in a particular block and its son, maybe you can only disasm this block and set a limit with block watchdog to only disasm some sons ?

**Comment by itewqq** [comment]
Wow that's a solution. Thanks!
