### ISSUE TITLE
x86-64 out of order IR block (add_asmblock_to_ircfg -> add_instr_to_current_state)

### ISSUE THREAD

**Issue by cyril-t-f** [cea-sec/miasm#1452]
Hello team,

First of all thanks for this magnifique baguette you guys gifted us.

I'm trying to lift the following asm block:
```asm
loc_1403b3419
INC        R9D
CMC        
CMP        RDX, 0xA9C2CC0
TEST       CL, R14B
NEG        R9D
CMP        R10B, BPL
PUSH       R8
RCR        R8B, 0x8B
ADC        R8B, 0x8
XOR        DWORD PTR [RSP], R9D
POP        R8
MOVSXD     R9, R9D
JMP        loc_14042ceff
->	c_to:loc_14042ceff
```

```python
asm_block = self.__engine.disassembler.dis_block(current_address)
ir_blocks = self.__engine.lifter.add_asmblock_to_ircfg(asm_block, ir_cfg, gen_pc_updt=True)
```

The interesting part is this one, it's a push/xor/pop pattern with crap instructions inbetween which should not produce any side effect on R8:
```asm
PUSH       R8
RCR        R8B, 0x8B
ADC        R8B, 0x8
XOR        DWORD PTR [RSP], R9D
POP        R8
```

However in the `add_instr_to_current_state` function the `RCR` instruction produce an **extra_block** that is added to the `ir_blocks_all` list before the rest of the previous assigments get a chance to be commited to the current IRBlock.

![image](https://github.com/cea-sec/miasm/assets/99127082/160cffa0-fbce-4bdd-8bfd-8fa1177611b9)

![image](https://github.com/cea-sec/miasm/assets/99127082/d59f0813-530d-4a1a-b475-01c28d0b2312)

This indeed modify the value of R8 before the push/xor/pop and at this point the emulation doesn't match reality anymore:

![image](https://github.com/cea-sec/miasm/assets/99127082/f6b95b3d-f7f7-4d7b-92ee-a54905b7477e)

Thanks!

**Comment by serpilliere** [comment]
Hi @cyril-t-f 
First of all, sorry for the late response.

Maybe I have missed something in your question, but I think there may be a misunderstanding in the miasm API.
When you disasm native code, one native instruction can generate multiple IR basic blocs. That what happens here, as you saw, with the RCR.

But when you lift something, the list of the ir basic bloc returned is not ordered. I mean the important thing is the irgraph.
In your case, if I disasm the raw asm:
```
python miasm/example/disasm/full.py test.exe -g 
```

If gives, in asm:

![test_asm](https://github.com/cea-sec/miasm/assets/9433661/16412681-c794-438c-9cc0-bd1a5d8453c6)


and in IR:
![test_ir](https://github.com/cea-sec/miasm/assets/9433661/609c9753-477f-450a-8729-b13a34ad223b)

So the resuling ircfg seems to be ok here.

Did I miss something here @cyril-t-f ?

**Comment by cyril-t-f** [comment]
Hey @serpilliere,

Ok I think I understand what I missed, I'm lifting/evaluating each IR block(s) one by one from the ASMCFG but actually I should first lift them all and then traverse/evaluate the IRCFG in a second time which indeed will maintain the right instructions order.

Thanks for reaching me out!
