### ISSUE TITLE
CMP and CMOV? analysis

### ISSUE THREAD

**Issue by adamprescott91** [cea-sec/miasm#1455]
I'm looking to analyse code using symbolic execution and am running into some odd behaviour.

I am looking to analyse individual blocks, and resolve a register state/value on exit from the block.
As an example:
>cmp [rcx], esi
>mov ecx, 0x1234
>cmovz ecx, r8d
>jmp loc_xyz

When I symbolically execute this with a SymbolicExecutionEngine initialised with:
>sb = SymbolicExecutionEngine(lifter, machine.mn.regs.regs_init)

The output value of RCX is fixed as 0x1234, whereas I would expect that the value would be either 0x1234 or r8d.

I might be misunderstanding how symbolic execution works with unknown values but would appreciate any pointers in trying to extract the possible values of registers when they have cmov instructions affecting them.

**Comment by serpilliere** [comment]
Hi @adamprescott91 
You are right, but here are some explanations:
- the cmov instruction gives in IR mulltiple IRBlocks. See https://github.com/cea-sec/miasm/blob/master/doc/ir/lift.ipynb
- The symbolic execution "runs" until it cannot resolve irdst (eip in IR world)
- so it stops at the comparison generated by the cmov (it cannot resolves the value or `[rcx]` nor `esi`
- so be sure about that, display the irdst value. It may be something like RCX?(loc_xxx, loc_yyy)

**Comment by adamprescott91** [comment]
Ah thanks a lot, that does explain the behaviour. I suspect it will be more effort than it is worth to fix the flags both ways at each cmov and carry on execution so I'm going to attack this problem from a different angle.
