### ISSUE TITLE
Rebasing program in graph

### ISSUE THREAD

**Issue by smuthayan** [cea-sec/miasm#1459]
Hello. Is there any way to rebase our program once it's loaded in miasm? For example, I want to represent all addresses with my own base, not 0x140000000
![image](https://github.com/cea-sec/miasm/assets/49108786/040f7839-0841-475a-a6b2-ddf7b7dc7c5e)

**Comment by serpilliere** [comment]
Hi @smuthayan !
No, not for now.
But you can rebase the program *before* with a rebase tool, and load it in Miasm.

**Comment by smuthayan** [comment]
Thanks! I solved it using CFF Explorer.
