### ISSUE TITLE
Error when using iterator from DependencyGraph object

### ISSUE THREAD

**Issue by smuthayan** [cea-sec/miasm#1460]
Hello. This code produces an error where it says that my expression was a bad slice. I stepped through the code and it fails only after a few iterations. I don't understand why.

`File "...miasm\expression\expression.py", line 519, in __getitem__
    raise TypeError("Expression: Bad slice: %s" % i)
TypeError: Expression: Bad slice: 0`

```
dep_graph = DependencyGraph(ira_cfg)
# Now we have a DiGraph(DependencyNodes)
info = dep_graph.address_to_location(0x140E015DC) # pass in assembly address for our place we want 0x140E015DC
sol_lst = []
for sol_nb, sol in enumerate(dep_graph.get(info["loc_key"], ExprId('RAX', 64), info["line_nb"], set())):
    sol_lst.append(sol)
    print ("End")
```

**Comment by serpilliere** [comment]
Hi @smuthayan 
You missused the api
the second argument of get is a set of expression. not an expression.
see `miasm/example/symbol_exec/depgraph.py` for API usage

**Comment by smuthayan** [comment]
My apologies. Thanks!
