### ISSUE TITLE
Unrolling of loop in SSA through symbolic execution

### ISSUE THREAD

**Issue by smuthayan** [cea-sec/miasm#1461]
Hello! I'm currently trying to unroll a loop in SSA using symbolic execution but, since the values of the registers that determine the result of the loop lie in the block above, I decide to implement them in the context of the Symbolic Execution Engine. This doesn't work though because adding the values into the context of the Symbolic execution engine just prepends them onto the block but then the indices of the registers in SSA form get incremented/decremented. But it's weird, sometimes it will increment/decrement the registers and not be able to solve the constraint. But, sometimes it can solve it. If I concretize SSA variables RDX.2, RDX.4 and R11.4, R11.6, then it can solve the condition.

For example:
![image](https://github.com/cea-sec/miasm/assets/49108786/83d72f03-94be-43db-b81b-2db43c1fa9db)

In this image, we have R11.4, RDX.2 as the targets to concretize.
My context for my symbolic execution engine is: `None` , my assignblks look like this: ![image](https://img001.prntscr.com/file/img001/zkPJxEdpTy-d0vtomfe_Xw.png)

After my concretization by passing in ctx_init to my symbolic execution engine: `ctx_init = {ExprId("RDX.2", 64) : ExprInt(0x27A1266259A10000, 64), ExprId("R11.4", 64) : ExprInt(0x27673E7419000000, 64)}.` My assignblks look like this: ![image](https://github.com/cea-sec/miasm/assets/49108786/14dcf398-d1da-4c7e-91c1-29847c09ece5)

I'm guessing that this is because the symb execution engine prepends the context to the block and automatically creates a new definitions. 

Secondly, is there any way to go back to the "normal form" from SSA? As in, turning R11.4 -> R11, and RDX.2 -> RDX etc etc? This would be extremely easier than working with the SSA and would solve my problem in this case. I tried using ssa_to_unssa but iirc it removes the phi-nodes.

Thanks!

**Comment by smuthayan** [comment]
Hi another question sorry!.
Does your liveness analysis assume that all variables and memory locations that have been written to are live at the end of the block? I had a RSP variable defined which was then propagated into a stack access expression to build a constant value but the RSP variable was used again after an indirect jump (which wasn't calculated at the time) and it couldn't find the definition.

**Comment by serpilliere** [comment]
Hi @smuthayan !
If I understand correctly, you want to "inject" the information of RDX.2 and R11.4 not at the very beginning of the symbolic execution, but just at the block at location ...f59080.
To do so, you can make your symbolic execution stops at this adress, concretize the registers value at this point, and continue your symbolic execute.
But if the previous block sets those values, why dont you start the symbolic execution at the previous bloc?
(Maybe I have missed something here)

For the next question: transforming a SSA form into a nonSSA form is the work of a 'register allocator' which is a part of the compilation process. So no there are no easy ways to do so.

For the liveness analysis, you must define the 'out regs' (from a custom defined abi) to tell which registers are live or not

**Comment by smuthayan** [comment]
Thank you for your response!
For defining the 'out regs' from a custom defined abi, how would you recommend I do this?

**Comment by smuthayan** [comment]
I figured out how to set my out_regs but I'm still having issues:
Here is my graph before constant propagation: 
As you can see: RSP.0 = 0xffffa90a2e9e28f8
![ircfg](https://github.com/cea-sec/miasm/assets/49108786/b79d6d00-ba93-4473-a8c6-c4cc8ae3d3ff)


Here it is after constant propagation:
But RSP.0 is apparently propagated into the stack accesses:
![ircfg](https://github.com/cea-sec/miasm/assets/49108786/55c8c6a3-e408-4208-9b65-7e7980b47aad)



In both cases, my out_regs in the 'head' are : {ExprId('RSP', 64), ExprId('RAX', 64)}
but it still propagates RSP into the stack expressions. Any ideas as to why this is happening?


Thank you for your time!

**Comment by serpilliere** [comment]
Hi @smuthayan 
I am reading your graphs, but I still miss something:
In the original graph, there is no loop, and a loop appears in the final graph.
If you only do a constant propagation, this may not happen

Did you add something there?

**Comment by smuthayan** [comment]
In the original graph, there is no loop because my analysis cannot reach it due to the indirect jump at the end (RBP.2). My second graph has reached the loop by performing constant propagation and dead removal so it is able to solve RBP. Does this make sense?

**Comment by serpilliere** [comment]
Ok. So maybe there is something wrong in the way you re inject data in the second part.
Maybe you should do the following step:
- disable & lift the code of the function
- do propagation do discover the targets of dynamic jumps
- loop from the first step, but add a disasm_callback to add the discovered link during disasm. This will re disassemble but link the 'dynamic' destination to the next bock. (until no more dynamic link are discovered)

This way, I think everything will be correctly propagated.

**Comment by smuthayan** [comment]
Hi thanks for your response! I originally thought of your method but I hoped that something else existed. I think I will be using your method now. For a last attempt, I went ahead and added a rule to not propagate stack access and it seems that even if the stack is not propagated, the algorithm does not recognize RSP as an SSA variable. What do you think?
![ircfg](https://github.com/cea-sec/miasm/assets/49108786/50081d59-6fd5-4acb-acea-828c8533591c)

**Comment by smuthayan** [comment]
Fixed my issue, thank you for the help!

**Comment by serpilliere** [comment]
Ok!
What was the problem with the RSP ?
