### ISSUE TITLE
conditional mov affects IRDst that breaks the symbolic execution?

### ISSUE THREAD

**Issue by cregnec** [cea-sec/miasm#159]
for the following code, the emulbloc function will stop at CMOVZ ESI, EDI instruction. We will have an ExprCond like condition?(0x8048555,lbl_gen_00000000:None).
However, I'm expecting an ExprCond such as condition?(0x08048bd6, 0x08048564)

loc_000000000804854A:0x0804854a
CMP        CL, 0x9
SETBE      CL
OR         AL, CL
CMOVZ      ESI, EDI
ADD        EDX, 0x1
CMP        EDX, DWORD PTR [ESP+0xC]
MOV        ECX, EDX
JNZ        loc_0000000008048BD6:0x08048bd6
->      c_to:loc_0000000008048BD6:0x08048bd6    c_next:loc_0000000008048564:0x08048564 

________________________________________________________________________________
zf ((ECX_init[0:8]+0xF7)?(0x0,0x1))
nf (ECX_init[0:8]+0xF7)[7:8]
pf (parity (ECX_init[0:8]+0xF7))
of (((ECX_init[0:8]+0xF7)^ECX_init[0:8])&(ECX_init[0:8]^0x9))[7:8]
cf ((((ECX_init[0:8]+0xF7)^ECX_init[0:8])&(ECX_init[0:8]^0x9))^(ECX_init[0:8]+0xF7)^ECX_init[0:8]^0x9)[7:8]
af (((ECX_init[0:8]+0xF7)&0x10)?(0x1,0x0))
________________________________________________________________________________
ECX {((((ECX_init[0:8]+0xF7)?(0x0,0x1))|((((ECX_init[0:8]+0xF7)^ECX_init[0:8])&(ECX_init[0:8]^0x9))^(ECX_init[0:8]+0xF7)^ECX_init[0:8]^0x9)[7:8])?(0x1,0x0)),0,8, ECX_init[8:32],8,32}
zf ((ECX_init[0:8]+0xF7)?(0x0,0x1))
nf (ECX_init[0:8]+0xF7)[7:8]
pf (parity (ECX_init[0:8]+0xF7))
of (((ECX_init[0:8]+0xF7)^ECX_init[0:8])&(ECX_init[0:8]^0x9))[7:8]
cf ((((ECX_init[0:8]+0xF7)^ECX_init[0:8])&(ECX_init[0:8]^0x9))^(ECX_init[0:8]+0xF7)^ECX_init[0:8]^0x9)[7:8]
af (((ECX_init[0:8]+0xF7)&0x10)?(0x1,0x0))
________________________________________________________________________________
EAX {(((((ECX_init[0:8]+0xF7)?(0x0,0x1))|((((ECX_init[0:8]+0xF7)^ECX_init[0:8])&(ECX_init[0:8]^0x9))^(ECX_init[0:8]+0xF7)^ECX_init[0:8]^0x9)[7:8])?(0x1,0x0))|EAX_init[0:8]),0,8, EAX_init[8:32],8,32}
ECX {((((ECX_init[0:8]+0xF7)?(0x0,0x1))|((((ECX_init[0:8]+0xF7)^ECX_init[0:8])&(ECX_init[0:8]^0x9))^(ECX_init[0:8]+0xF7)^ECX_init[0:8]^0x9)[7:8])?(0x1,0x0)),0,8, ECX_init[8:32],8,32}
zf ((((((ECX_init[0:8]+0xF7)?(0x0,0x1))|((((ECX_init[0:8]+0xF7)^ECX_init[0:8])&(ECX_init[0:8]^0x9))^(ECX_init[0:8]+0xF7)^ECX_init[0:8]^0x9)[7:8])?(0x1,0x0))|EAX_init[0:8])?(0x0,0x1))
nf (((((ECX_init[0:8]+0xF7)?(0x0,0x1))|((((ECX_init[0:8]+0xF7)^ECX_init[0:8])&(ECX_init[0:8]^0x9))^(ECX_init[0:8]+0xF7)^ECX_init[0:8]^0x9)[7:8])?(0x1,0x0))|EAX_init[0:8])[7:8]
pf (parity (((((ECX_init[0:8]+0xF7)?(0x0,0x1))|((((ECX_init[0:8]+0xF7)^ECX_init[0:8])&(ECX_init[0:8]^0x9))^(ECX_init[0:8]+0xF7)^ECX_init[0:8]^0x9)[7:8])?(0x1,0x0))|EAX_init[0:8]))
of 0x0
cf 0x0
af (((ECX_init[0:8]+0xF7)&0x10)?(0x1,0x0))
________________________________________________________________________________
IRDst ((((((ECX_init[0:8]+0xF7)?(0x0,0x1))|((((ECX_init[0:8]+0xF7)^ECX_init[0:8])&(ECX_init[0:8]^0x9))^(ECX_init[0:8]+0xF7)^ECX_init[0:8]^0x9)[7:8])?(0x1,0x0))|EAX_init[0:8])?(0x8048555,lbl_gen_00000000:None))
EAX {(((((ECX_init[0:8]+0xF7)?(0x0,0x1))|((((ECX_init[0:8]+0xF7)^ECX_init[0:8])&(ECX_init[0:8]^0x9))^(ECX_init[0:8]+0xF7)^ECX_init[0:8]^0x9)[7:8])?(0x1,0x0))|EAX_init[0:8]),0,8, EAX_init[8:32],8,32}
ECX {((((ECX_init[0:8]+0xF7)?(0x0,0x1))|((((ECX_init[0:8]+0xF7)^ECX_init[0:8])&(ECX_init[0:8]^0x9))^(ECX_init[0:8]+0xF7)^ECX_init[0:8]^0x9)[7:8])?(0x1,0x0)),0,8, ECX_init[8:32],8,32}
zf ((((((ECX_init[0:8]+0xF7)?(0x0,0x1))|((((ECX_init[0:8]+0xF7)^ECX_init[0:8])&(ECX_init[0:8]^0x9))^(ECX_init[0:8]+0xF7)^ECX_init[0:8]^0x9)[7:8])?(0x1,0x0))|EAX_init[0:8])?(0x0,0x1))
nf (((((ECX_init[0:8]+0xF7)?(0x0,0x1))|((((ECX_init[0:8]+0xF7)^ECX_init[0:8])&(ECX_init[0:8]^0x9))^(ECX_init[0:8]+0xF7)^ECX_init[0:8]^0x9)[7:8])?(0x1,0x0))|EAX_init[0:8])[7:8]
pf (parity (((((ECX_init[0:8]+0xF7)?(0x0,0x1))|((((ECX_init[0:8]+0xF7)^ECX_init[0:8])&(ECX_init[0:8]^0x9))^(ECX_init[0:8]+0xF7)^ECX_init[0:8]^0x9)[7:8])?(0x1,0x0))|EAX_init[0:8]))
of 0x0
cf 0x0
af (((ECX_init[0:8]+0xF7)&0x10)?(0x1,0x0))

**Comment by commial** [comment]
Actually, in Miasm, CMOVZ ESI, EDI is translated to:
```Python
if zf:
    ESI = EDI
```
And not ```ESI = zf?EDI:ESI``` because this form introduces a wrong dependency between the new ESI and the past ESI.

To have a better translation, Miasm will create a "fake" block, named `lbl_gen_XXX`.
In this block, the `Mov` is done. The block is used if `zf`. So, just before the translation of the `CMOV`, one obtains:
`IRDST = zf?lbl_next, lbl_gen_XXXX`

Take a look to the generated graph (thanks to `example/disasm/full.py`).
May #149 can help you to have a better understanding.

**Comment by serpilliere** [comment]
This subject is discussed in #132 as well.

**Comment by cregnec** [comment]
thank @commial  and @serpilliere. I didn't know this IR behavior.
I was trying to do:
 - disbloc(addr)
 - symbolic exec(bloc)
 - check IRDst and loops
The above IR behavior will break my code since there is actually no 0x8048555 basic bloc in assembler.
