### ISSUE TITLE
Having error during installation in Windows

### ISSUE THREAD

**Issue by bsmondal** [cea-sec/miasm#161]
I am trying to use your framework. But during installation in windows (python 2.7 & VS 12), I was getting the following error:

miasm2/jitter/vm_mngr.c(26) : fatal error C1083: Cannot open include file: 'inttypes.h': No such file or directory

Using google search I got a solution for inttypes.h and placed it in  CV->include. After that, I was having below problem.
.
'__BYTE_ORDER' : undeclared identifie
 'void *' : unknown size
 'fabs' : intrinsic function, cannot defined

I would be very grateful to you, if you can provide me that any solution of it.

**Comment by serpilliere** [comment]
Hi,

We didn't spend time for the moment to compile Miasm on Windows, so it may spit errors during compilation.  The `BYTE_ORDER` macro is used to determine if we are on a little/big endian machine. As you can see in `vm_mngr.h`, there is the following definition:
```C
#ifdef __APPLE__
#define __BYTE_ORDER __BYTE_ORDER__
#elif defined(__NetBSD__)
#define __BYTE_ORDER _BYTE_ORDER
#define __BIG_ENDIAN _BIG_ENDIAN
#define __LITTLE_ENDIAN _LITTLE_ENDIAN
#endif
```
So there is a missing case here to detect windows and set the correct endianness. Maybe some nice Windows programmer can help us here?

**Comment by p-l-** [comment]
I recently came across [this trick](http://esr.ibiblio.org/?p=5095), in case it might help.

**Comment by bsmondal** [comment]
Thanks for your quick response.

**Comment by p-l-** [comment]
Hi, you should probably open another issue for your question.

**Comment by greenozon** [comment]
@bsmondal  I guess this ticket should be closed as it's possible to successfully build miasm on Windows
