### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Celelibi** [cea-sec/miasm#162]
The absence of documentation make miasm practically unusable for someone who isn't into its code.

So would it be possible to make a reference documentation listing all the classes and functions a-la doxygen?

**Comment by fmonjalet** [comment]
Hi @Celelibi,

Your are totally right. A global doc is kind of missing. Could you be more specific on the kind of doc/tutorial you would like to see? What would be the priorities for you?

What I would recommend is to start by reading the examples. Some are really minimal, and you can play with them easily. The readme provides some basic information on the API too.
For the rest, my method was to generate the API doc with doxygen (maybe the Doxyfile could be added to the repo?) and navigate into the generated doc to see which functions are available and how they are implemented.

These advices are only workarounds, and any external viewpoint on what would be the priorities in term of documentation is very wellcome!

Florent

**Comment by serpilliere** [comment]
Hi,

I agree with you @Celelibi, there is a huge lack of documentation.
One of the reason (*reason* not *excuse*) is the API of Miasm has changed a lot til now. Direction is for the moment to push Miasm to open source, to keep commits clean, to answer issues and questions. This is only a question of time, priority and also preferences. As @fmonjalet said, we keep examples (which are use cases) synchronized with the API.

For the moment, the *hardcore* users have to (and do :sweat_smile: ) read the source.

But you are right, we can *also* spend time on documentation as well.

Did I mention it was open source and that we accept patches?

**Comment by commial** [comment]
Hi @Celelibi 

I've recently open this subdomain: http://miasmdoc.ajax.re. You'll find here an auto-generated documentation thanks to `pdoc` and `doxygen`.

I hope it is similar to what you wished.

I welcome any feedback :smiley: .

**Comment by p-l-** [comment]
Fixed by @commial with #165. Feel free to ask open a new issue if you have any questions.
