### ISSUE TITLE
Use miasm for windows binaries

### ISSUE THREAD

**Issue by hrsalehi** [cea-sec/miasm#164]
Hello.
I'm working on an approach to combat symbolic executions of Windows binaries (EXE files). I need to disassemble the file and after applying my algorithm to the code then assemble it again and at last run the symbolic execution.
Because there is no documentation I don't no that "miasm" is good for me or not. Can you expain a little bit?
If I can only run symbolic execution that will be great too.

**Comment by p-l-** [comment]
Hi,

Thanks for taking the time to look into Miasm!

The "Documentation: TODO" in the README file is more or less a joke, actually: the README file provides a good overview of what can be achieved with Miasm, the Python code contains docstrings (OK not all of it, but that's a good start), and the `example` directory contains some interesting use cases that can be good starting points.

I think Miasm is an appropriate tool for what you want to do.

For example, the file `example/jitter/unpack_upx.py` is a generic UPX unpacker. It opens a binary, creates a Miasm sandbox, runs the binary until it reaches the end of the unpacking stage, and reconstructs from the sandbox's memory a valid unpacked executable.

Feel free to reopen this issue if this does not answer you question!
