### ISSUE TITLE
Query on Symbolic Execution.

### ISSUE THREAD

**Issue by bsmondal** [cea-sec/miasm#171]
Hi,

Last few days I worked a lot on miasm. Thanks guys for a nice framework and support me to run it on my PC. Now, I need few clarifications on Symbolic execution by miasm.  After running a symbolic execution of below function, I am getting the following output.
___
int multipath(int a,int b,int op)
{
	int ret=0;
	if(op==0)
	   ret = a+b;
	if(op==1)
	   ret = a-b;
	if(op==2)
	   ret = a*b;
	if(op==3)
	   ret = a/b;
	return ret;
}

**Symbolic output by miasm:**
Solution 0: EAX: (@32[(ESP_init+0x4)]+(- @32[(ESP_init+0x8)])) -> sol_0.dot
Solution 1: EAX: (@32[(ESP_init+0x4)]+@32[(ESP_init+0x8)]) -> sol_1.dot
Solution 2: EAX: 0x0 -> sol_2.dot
Solution 3: EAX: ({@32[(ESP_init+0x4)],0,32, (@32[(ESP_init+0x4)][31:32]?(0xFFFFFFFF,0x0)),32,64}*{@32[(ESP_init+0x8)],0,32, (@32[(ESP_init+0x8)][31:32]?(0xFFFFFFFF,0x0)),32,64})[0:32] -> sol_3.dot
Solution 4: EAX: ({@32[(ESP_init+0x4)],0,32, (@32[(ESP_init+0x4)][31:32]?(0xFFFFFFFF,0x0)),32,64} idiv {@32[(ESP_init+0x8)],0,32, (@32[(ESP_init+0x8)][31:32]?(0xFFFFFFFF,0x0)),32,64})[0:32] -> sol_4.dot
___
**Q:**
Is there any way to know that, for each solution what are the values of a, b and op using and what is the return value?

**something like**
 Solution 0: EAX: 12 a->4 b->8 and op->0

Thank you for your time.

**Comment by commial** [comment]
Hi @bsmondal,

What you're actually using here is the *DependencyGraph*, which is using itself the symbolic execution to render solutions.
Apparently, you've used the explicit version. That is to say, *ask Miasm to give me all implicated lines, and if they represent different paths, yield each ones*.

That's what you have in the *.dot files.
Then, using the `.emul` method, you can symbolic executes each solution history / path / implicated lines to obtain the equation of the result. That's the output: `EAX: (@32[(ESP_init+0x4)]+(- @32[(ESP_init+0x8)]))` <=> `EAX: Arg1 - Arg2` <=> `ret = a - b`.

So, at this point, there is no value for `a`, `b` or `op`. This is, in fact, the interest of the algorithm.
Now if you want to obtain a value for `op` reaching each solution, you have to used the *implicit* DependencyGraph, a version which also tracks implicit (coming from control flow) dependencies.
You'll need the `z3` Python dependency.

I advise you to modify expression to inject ABI + signature information (`@32[(ESP_init+0x4)]` -> `Arg_A`, ...). This will prevent your having memory constraint in the result.

See #152 for a very similar example.

**Comment by bsmondal** [comment]
Hi @commial 

Thanks a lot. It works fine. I was getting some error during z3 installation. But its solve now. That's why it takes time to check and give you feedback.
