### ISSUE TITLE
Install procedure with TinyCC

### ISSUE THREAD

**Issue by r1git** [cea-sec/miasm#178]
Hi, just my 2 cents tip:

If one follows the install procedure using TinyCC he might run into the problem that TinyCC puts the libtcc.so.1.0 in /usr/local/lib which may not be in the default path of the runtime linker (ubuntu for example) :

```
r1git@zenplace:~/tools/miasm/example/jitter$ python x86_32.py toto
Traceback (most recent call last):
  File "x86_32.py", line 26, in <module>
    myjit = Machine("x86_32").jitter(args.jitter)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/arch/x86/jit.py", line 50, in __init__
    jitter.__init__(self, ir_x86_32(sp), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/miasm2/jitter/jitload.py", line 204, in __init__
    self.jit = JitCore_Tcc(self.ir_arch, self.bs)
NameError: global name 'JitCore_Tcc' is not defined

r1git@zenplace:/usr/local/lib/python2.7/dist-packages/miasm2/jitter$ ldd Jittcc.so 
	linux-vdso.so.1 =>  (0x00007fff28bfe000)
	libtcc.so.1.0 => not found
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff1bc9bf000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff1bc5f9000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff1bce07000)
```

The possible solutions :
 - Modify your LD_LIBRARY_PATH
 - Update your /etc/ld.so.conf.d/ file

Ok. Lamest contribution ever. But still !

Congrats for your great tools.

**Comment by commial** [comment]
Hi @r1git ,
Actually, it was already discussed in #163, but at the end of the issue. If you didn't find it, it is surely too deep in the issue.
It will be easier for new users to find your tips, so thanks you for your contribution.

As it is related to system installation of libtcc, and not directly to the setup of Miasm, I'll just close the issue (may a day in a "common troubleshooting" section), still reachable via the searchbox.
