### ISSUE TITLE
Refactoring the way registers are initialized

### ISSUE THREAD

**Issue by gelim** [cea-sec/miasm#180]
Hi,

it seems that you've already coded helpers function to handle the registers initialization with `gen_reg/gen_regs` in `miasm2/core/cpu.py`.
I guess it's meant to be used to clear init code in `regs.py` for the different architectures.
But still you manually write reg init like:

```
PC = ExprId('PC')
reg_pc_str = ['PC']
reg_pc_expr = ExprId(reg_pc_str, sz)
```

I won't touch the code for now, as I don't know if you still support the `gen_reg` way to do.

On a side note, seems a little bit odd that `gen_reg()` and `gen_regs()` coexist together.
You could maybe handle the case when a single register is passed to the function as an exception, and handling it in `gen_regs()` only, giving up on `gen_reg()`, or call `gen_reg` on each elements of the `rnames` list passed to `gen_regs()` if it's seems to you important that `gen_reg()` persists.

Cheers

**Comment by commial** [comment]
Fix by #734
