### ISSUE TITLE
Order of IR instructions and memory access

### ISSUE THREAD

**Issue by mrphrazer** [cea-sec/miasm#194]
Hi!

I'm modelling memory access based on the IR instructions. 
The order of the IR instructions seems not to be represent the program semantics, especially in the epilog, regarding the incrementation of RSP.

First, a few listings:

Assembly:
```
loc_0000000000400577:0x00400577
PUSH       RBP
MOV        RBP, RSP
MOV        DWORD PTR [RBP+0xFFFFFFFFFFFFFFFC], EDI
MOV        EAX, DWORD PTR [RBP+0xFFFFFFFFFFFFFFFC]
ADD        EAX, 0x4
POP        RBP
RET
```
IR:
```
loc_0000000000400577:0x00400577
	RSP = {(RSP[0:64]+(- 0x8)),0,64}
	@64[(RSP[0:64]+(- 0x8))] = RBP

	RBP = RSP

	@32[(RBP+0xFFFFFFFFFFFFFFFC)] = RDI[0:32]

	RAX = {@32[(RBP+0xFFFFFFFFFFFFFFFC)],0,32, 0x0,32,64}

	zf = ((RAX[0:32]+0x4)?(0x0,0x1))
	nf = (RAX[0:32]+0x4)[31:32]
	pf = (parity ((RAX[0:32]+0x4)&0xFF))
	af = (((RAX[0:32]+0x4)&0x10)?(0x1,0x0))
	cf = (((RAX[0:32]^0x4)^(RAX[0:32]+0x4))^((RAX[0:32]^(RAX[0:32]+0x4))&((RAX[0:32]^0x4)^0xFFFFFFFF)))[31:32]
	of = ((RAX[0:32]^(RAX[0:32]+0x4))&((RAX[0:32]^0x4)^0xFFFFFFFF))[31:32]
	RAX = {(RAX[0:32]+0x4),0,32, 0x0,32,64}

	RSP = {(RSP[0:64]+0x8),0,64}
	RBP = @64[RSP[0:64]]

	RSP = {(RSP[0:64]+0x8),0,64}
	RIP = @64[RSP[0:64]]
	IRDst = @64[RSP[0:64]]
```
```dump_id()``` after symbolic execution:
```
zf ((RDI_init[0:32]+0x4)?(0x0,0x1))
nf (RDI_init[0:32]+0x4)[31:32]
pf (parity ((RDI_init[0:32]+0x4)&0xFF))
of (((RDI_init[0:32]+0x4)^RDI_init[0:32])&(RDI_init[0:32]^0xFFFFFFFB))[31:32]
cf ((((RDI_init[0:32]+0x4)^RDI_init[0:32])&(RDI_init[0:32]^0xFFFFFFFB))^(RDI_init[0:32]+0x4)^RDI_init[0:32]^0x4)[31:32]
af (((RDI_init[0:32]+0x4)&0x10)?(0x1,0x0))
RIP @64[RSP_init]
RAX {(RDI_init[0:32]+0x4),0,32, 0x0,32,64}
RSP (RSP_init+0x8)
IRDst @64[RSP_init]
```
```dump_mem()``` after symbolic execution:
```
@32[(RSP_init+0xFFFFFFFFFFFFFFF4)] RDI_init[0:32]
@64[(RSP_init+0xFFFFFFFFFFFFFFF8)] RBP_init
```

The symbolic execution states that the return address is ```64[RSP_init]```, but the last value of ```RSP``` is ```(RSP_init+0x8)```. Thus, ```IRDst``` would get assigned the value at address ```RSP_init + 0x8```. To represent the program semantics, it should look as
```
RIP = @64[RSP[0:64]]
IRDst = @64[RSP[0:64]]
RSP = {(RSP[0:64]+0x8),0,64}
```

The same holds for
```
RSP = {(RSP[0:64]+0x8),0,64}
RBP = @64[RSP[0:64]]
```
(As a side note, ```dump_id()``` doesn't contain ```RBP```)

My questions:
* Is that a bug or intended behaviour?
* In the second case, is there a (straight forward) way I could represent it in a semantic-preserving order?

Thanks in advance :)

**Comment by commial** [comment]
Hi!

Remember that in Miasm, IR expression are evaluated in a parallel way.
Thus:
```
RSP = {(RSP[0:64]+0x8),0,64}
RIP = @64[RSP[0:64]]
IRDst = @64[RSP[0:64]]
```
Equals to:
```
RIP = @64[RSP[0:64]]
IRDst = @64[RSP[0:64]]
RSP = {(RSP[0:64]+0x8),0,64}
```

And the value of `IRDst` will be `@64[RSP_before_expression[0:64]]`.
That way, `XCHG EAX, EBX` is written:
```
EAX = EBX
EBX = EAX
```

So, the statement *The symbolic execution states that the return address is 64[RSP_init], but the last value of RSP is (RSP_init+0x8). Thus, IRDst would get assigned the value at address RSP_init + 0x8.* doesn't hold.

You have:
* `RSP_final` = `RSP_init` + 8
* `IRDst_final` = `@64[RSP_init]`

Does it make more sense to you ?

**Comment by mrphrazer** [comment]
Hi!

Thanks for the clarification, I didn't know that!

Then, (for my analysis), is it safe to assume that an expression gets assigned/modified only once during an asm -> IR transformation?

For example, are there cases where one assembly instruction could be translated to s.th. as:
```
rax = rbx + 7
rcx = 55
rax = rcx + 1
``` 
or would that be  in *every* case translated to the following?
```
rcx = 55
rax = rbx + 7 + 55 + 1
```

A last related, but more general question: Do you have some sort of guideline or specification (or more formal, a grammar) of the transformation process assmembly -> IR that you use for orientation and would be able to publish? For instance, something that enables reasoning about (from assembly) generated  IR in a more general way, as in the question above.

**Comment by commial** [comment]
Firstly, the IR CFG is composed of nodes, which are IR basic blocks.

Each IR basic blocks is an ordered list of *AffBlock*. Each AffBlock is an unordered list of `ExprAff`.
So, for instance, this is an IR basic block:
```
loc_0000000000400577:0x00400577
    RSP = {(RSP[0:64]+(- 0x8)),0,64}
    @64[(RSP[0:64]+(- 0x8))] = RBP

    IRDst = RSP
```
There are two *AffBlock* (in Miasm, it's a list for now):
* `RSP = {(RSP[0:64]+(- 0x8)),0,64}
@64[(RSP[0:64]+(- 0x8))] = RBP`

* `IRDst = RSP`

So now, a few assertions that come to my mind:
* An IR basic block always has one and only one `IRDst` affect
* In an *AffBlock*, destinations are only present once (so, double `rax` affectations is impossible)

Regarding the translation ASM -> IR, you should pay attention to the fact that you can obtain more than one IR basic block for a single ASM basic block.
For instance, `CMOVZ EAX, 4`.

**Comment by mrphrazer** [comment]
Thanks again for confirmation! I modified my code to handle the parallel instructions, it works fine now.
