### ISSUE TITLE
expression simplifications

### ISSUE THREAD

**Issue by mrphrazer** [cea-sec/miasm#239]
Hi,

the simplifications for `a^a` doesn't seem to work. For instance,

```python
expr_simp(ExprOp("^", eax, eax)) # eax ^ eax
```
doesn't apply the simplification. Therefore,  ```(((eax|(eax&(eax^eax)))``` will also not be simplified:

```python
print expr_simp(ExprOp("|", eax, ExprOp("&", eax, ExprOp("^", eax, eax))))
```

I noted that while I was trying to add simplifications for ```a % a``` and ```a / a``` [here](https://github.com/cea-sec/miasm/blob/master/miasm2/expression/simplifications_common.py#L168).

```python
            # A OP A => 0
            if op in ['^', '%', "imod", "umod"] and args[i] == args[j]:
                args[i] = ExprInt_from(args[i], 0)
                del(args[j])
                continue
            # A OP A => 1
            if op in ['/', "idiv", "udiv"] and args[i] == args[j]:
                args[i] = ExprInt_from(args[i], 1)
                del(args[j])
                continue
```
With that, simplifications for `/` will be applied, but not for the other cases (`idiv`, `udiv`, `%`, `^`, ... ).

**Comment by serpilliere** [comment]
I did the following test:
```python
>>> from miasm2.expression.expression import *
>>> from miasm2.expression.simplifications import expr_simp
>>> eax = ExprId('eax')
>>> expr_simp(ExprOp("^", eax, eax))
ExprInt(uint32(0x0L))
>>> expr_simp(((eax|(eax&(eax^eax)))))
ExprId('eax', 32)
```

Have you got a script which produces the error?

**Comment by a-vincent** [comment]
Hi,

please be aware that a / a and a % a should not be simplified if you
cannot guarantee that a is different from 0.

Regards,
 Aymeric

**Comment by mrphrazer** [comment]
@serpilliere Exactly the same code didn't work. However, I couldnt reproduce it on a second machine. After I removed miasm from `site-packages`, it worked again. No idea where the problem was. Thanks!

@a-vincent Thanks for the hint, I'm aware of that. It wasn't supposed to be commited, just for a project where this assumptions holds.
