### ISSUE TITLE
TCC is not properly Installed Error 

### ISSUE THREAD

**Issue by Hiroip** [cea-sec/miasm#293]
Hi ! 

I have an error when I try to build miasm (same as in #42 ) : 

```
building 'miasm2.jitter.Jittcc' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c miasm2/jitter/Jittcc.c -o build/temp.linux-x86_64-2.7/miasm2/jitter/Jittcc.o
miasm2/jitter/Jittcc.c: In function ‘tcc_init_state’:
miasm2/jitter/Jittcc.c:50:3: error: too few arguments to function ‘tcc_add_file’
   tcc_add_file(tcc_state, lib_array[i]);
   ^
In file included from miasm2/jitter/Jittcc.c:21:0:
/usr/local/include/libtcc.h:51:15: note: declared here
 LIBTCCAPI int tcc_add_file(TCCState *s, const char *filename, int filetype);
               ^
SystemExit("error: command 'x86_64-linux-gnu-gcc' failed with exit status 1",)
build with 'notcc'
running build
running build_py
running build_ext
build notcc

********************************************************************************
Warning: TCC is not properly installed,
Miasm will be installed without TCC Jitter
Etheir install TCC or use LLVM jitter
********************************************************************************

build/lib.linux-x86_64-2.7
```

I run a debian VM, here's my uname 
```
Linux fuchikoma 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux
```

tcc -v : 
```
tcc version 0.9.26 (x86-64 Linux)
```

There's no libtcc-dev : 
```
apt-get remove libtcc-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'libtcc-dev' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

I tried with installing tcc via apt-get and via tar.gz but had the same result in both cases

I hope you can help me ! :grin:
regards

**Comment by p-l-** [comment]
Hi,

Have you installed the **latest stable** version of TCC (as stated in the [README](https://github.com/cea-sec/miasm/#configuration)), and not the latest version from the repository?

If that is not the case:

- From the [tags](http://repo.or.cz/w/tinycc.git/tags), select the commit for the latest stable ("release_0_9_26") and then select ".tar.gz" snapshot (or just [click here](http://repo.or.cz/tinycc.git/snapshot/d5e22108a0dc48899e44a158f91d5b3215eb7fe6.tar.gz).

- Remove your previously installed files, extract the archive, enter the repository and run `./configure --disable-static && make && make install`.

**Comment by Hiroip** [comment]
Build worked just fine with this version, many thanks !
