### ISSUE TITLE
ImportError: cannot import name Jittcc

### ISSUE THREAD

**Issue by ithurricane** [cea-sec/miasm#326]
Hi,

I am successfully configured miasm and TinyCC on Kail Linux.
But after running the example I am getting the following error.

root@kali:~/Desktop/miasm-master# python
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from miasm2.analysis.machine import Machine
>>> machine = Machine('x86_32')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "miasm2/analysis/machine.py", line 85, in __init__
    from miasm2.arch.x86 import arch, jit
  File "miasm2/arch/x86/jit.py", line 3, in <module>
    from miasm2.jitter.jitload import jitter, named_arguments
  File "miasm2/jitter/jitload.py", line 23, in <module>
    from miasm2.jitter.jitcore_tcc import JitCore_Tcc
  File "miasm2/jitter/jitcore_tcc.py", line 9, in <module>
    from miasm2.jitter import jitcore, Jittcc
**ImportError: cannot import name Jittcc**

root@kali:/usr/local/lib/python2.7/dist-packages/miasm2/jitter# ldd Jittcc.so 
	linux-vdso.so.1 (0x00007ffd443fc000)
	libtcc.so.1.0 => /usr/local/lib/libtcc.so.1.0 (0x00007f9af80ea000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9af7ecd000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9af7b24000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9af8533000)

Please let me know, what wrong I am doing.
Thank you.

**Comment by serpilliere** [comment]
Hi!
Did you type something like `ldconfig -v` after the installation to update your library path cache?

**Comment by serpilliere** [comment]
Hi!
I tested this on a kali (live DVD):
```
Linux kali 4.3.0-kali1-amd64 #1 SMP Debian 4.3.3-5kali4 (2016-01-13) x86_64 GNU/Linux
```
I downloaded a zip of miasm/elfesteem (zip of current master). I downloaded tinycc 0.9.26 `http://repo.or.cz/tinycc.git/snapshot/d5e22108a0dc48899e44a158f91d5b3215eb7fe6.zip`)

Here is the command history:

```
    5  ls Downloads/
    6  unzip Downloads/miasm-master.zip 
    7  unzip Downloads/elfesteem-master.zip 
    9  cd elfesteem-master/
   10  python setup.py  install
   11  cd ../
   12  unzip Downloads/tinycc-d5e2210.zip 
   13  cd tinycc-d5e2210/
   14  ls
   15  ./configure --disable-static
   16  make
   17  make install
   18  ldconfig -v |less
   19  cd ../miasm-master/
   20  ls
   21  python setup.py  build
   22  python setup.py  install
   23  ls
   24  cd example/
   25  ls
   26  cd jitter/
   27  python unpack_upx.py  ../samples/box_upx.exe 
```

The upx sample is depacked.
Can you give me your kali version?

**Comment by ithurricane** [comment]
now build worked just fine, many thanks !

**Comment by serpilliere** [comment]
Hi!
Just for information:
What did you change? Is there a bug you have corrected or was it a typo or something?
