### ISSUE TITLE
setup.py is using the broken distutils instead of the non-broken setuptools

### ISSUE THREAD

**Issue by arizvisa** [cea-sec/miasm#328]
Since distutils is never updated and as a result developed a history of being pretty fuckin' broken (batteries included), some things such as building on Windows or Msys or Mingw32 will never work due to internal issues with distutils.

setuptools essentially fixes all the issues that distutils has had, is well maintained, and pretty much implements the exact same interface. If you'd like to support more systems out of the box, fixing this would probably be the first step.

In setup.py:3 replace the following line:
`from distutils.core import setup, Extension`

with:
`from setuptools import setup, Extension`

**Comment by commial** [comment]
First, thanks for the remark.

From what I understand, `distutils` is still in use in Python community, especially for not-so-custom needs. `setuptools` seems to also come with its own problems, so we may consider to use it if we really encounter a problem for a given setup
