### ISSUE TITLE
IDA plugins in current version throw errors

### ISSUE THREAD

**Issue by gitttt** [cea-sec/miasm#333]
The IDA plugins for commit 4c9f108ab0ce059532b7f1f776898912fce49278 (from Mar 9) do not work.
They throw various python error and assertions messages.

However, if I replace the miasm folder with an older version (and also replace the miasm2 folder in IDA's python folder) it works.

The older version I took:
commit 5764a1fb42cc3e50cb4c322cc3146375fbce84ef (from Nov 15)

**Comment by serpilliere** [comment]
Hi!
I have just tested the plugins `symbol_exec.py` and everything looks ok.
Can you provide:
- the faulty plugin name
- your IDA version
- some error message
- some of your system information (windows/linux 32/64bit, ...)

By the way, there are currently some *warnings* in the output window when you run the plugings:
```
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "...python/lib/python27.zip/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "...python/lib/python27.zip/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
...
```


But it does not impact the plugin behavior.

**Comment by gitttt** [comment]
Did you try depgraph.py ?

Sent from Outlook Mobile




On Wed, Mar 9, 2016 at 12:50 PM -0800, "serpilliere" <notifications@github.com> wrote:





Hi!
I have just tested the plugins `symbol_exec.py` and everything looks ok.
Can you provide:
- the faulty plugin name
- your IDA version
- some error message
- some of your system information (windows/linux 32/64bit, ...)

By the way, there are currently some *warnings* in the output window when you run the plugings:
```
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "...python/lib/python27.zip/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "...python/lib/python27.zip/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
...
```


But it does not impact the plugin behavior.


---

**Comment by serpilliere** [comment]
Hi!

Oups: My fault! We broke the `DependencyGraph` during the upgrade of `AssignBlock`. Anyway, we are currently working on a much better algorithm for this module (it's in its test phase), and it will be released soon. So I won't fix this bug in the current version, but be sure it will be fixed in its next version. I keep the issue open to track it.

Thank you for the bug reporting!

**Comment by serpilliere** [comment]
Hi,
The PR #339 should resolve this issue.
