### ISSUE TITLE
How to dump full hex of a function ?

### ISSUE THREAD

**Issue by hackmoonlight** [cea-sec/miasm#397]
I used a script python from radare2-bindings to write a code analysing a binary file, i extracted the name , the start address and the size of each function , but i can't dump the hexa of each function , i am asking if there is a methode or python script in radare2 or another tool (capstone , miasm ...) to solve this problem .

**Comment by commial** [comment]
You can retrieve the bytes corresponding to an interval `[start_addr, start_addr + size]` by using the `elfesteem` API.
Once you are on a `bin_stream` object, you can use `bsobj.getbytes(start, length)`. The `bin_stream` object can be obtain, for instance, using the `Container` abstraction:
```Python
from miasm2.analysis.binary import Container

fdesc = open('mybin')
cont = Container.from_stream(fdesc)
bsobj = cont.bin_stream
bts = bsobj.getbytes(start_addr, length)
```

After that, if you really want to obtain a *hexdump*, you can use the `miasm2.core.utils::hexdump` function, which display an output similar to `hexdump -C`:
```Python
>>> from miasm2.core.utils import hexdump
>>> hexdump("Hello, world!")
0000  48 65 6c 6c 6f 2c 20 77 6f 72 6c 64 21            Hello, world!
```

Or by using a `.encode("hex")`.

**Comment by hackmoonlight** [comment]
this is my script : 

```
import sys
    import sqlite3 as lite
    try:
        import os, signal
        from r_core import *
    except:
        from r2.r_core import *

    rc = RCore()
    rc.file_open("/home/younes/Bureau/a.out", 0, 0)
    rc.bin_load("", 0)

    rc.anal_all()
    funcs = rc.anal.get_fcns()
    for f in funcs:
        blocks = f.get_bbs()
        print("+" + (72 * "-"))
        print("| FUNCTION: %s @ 0x%x" % (f.name, f.addr))
        print("| (%d blocks)" % (len (blocks)))
        print("+" + (72 * "-"))
        funcSize=0
        for b in blocks:
            end_byte = b.addr + b.size
            cur_byte = b.addr
            funcSize+=b.size

        print("   | f.size:      0x%x" %(funcSize))

    os.kill (os.getpid (), signal.SIGTERM) 
```

**Comment by commial** [comment]
Ok, so what is your error output?

Are your addresses in RVA / file offset / ... ?

**Comment by hackmoonlight** [comment]
could you explain me what you mean by" emulation " ?

**Comment by commial** [comment]
Did you close the issue on purpose?

I have not managed to find where I talk about "emulation", but if this is related to the emulation in Miasm, I invite you to read about the emulation in [Qemu](https://en.wikipedia.org/wiki/QEMU) (system emulation, user-mode emulation, that is to say running a different architecture set in an emulated environment).

**Comment by hackmoonlight** [comment]
Yes i closed the issue , 
we emulate to know functions behaviours ?

**Comment by commial** [comment]
We emulate for few reasons, depending on your goals:
* recognizing function behaviors
* run untrusted code
* full control on the emulation environment
* ...

In a more general way, regarding Miasm uses and possibilities, I think that issues are not the best way for you to discover Miasm.
You should take a look at examples (`/examples`), at the `README.MD` and consult the blog posts (such as the ones on [miasm.re](http://miasm.re)).
