### ISSUE TITLE
RuntimeError: Unsupported jitter: tcc

### ISSUE THREAD

**Issue by YounesHaj** [cea-sec/miasm#399]
I installed tcc ( arch linux tcc-git <Tiny C Compiler> ) and I installed miasm but when i run this script " https://github.com/cea-sec/miasm/blob/master/test/jitter/jitload.py  " it generates this error , i reinstalled tcc but the same problem persist.
```
Traceback (most recent call last):
  File "emulation.py", line 12, in <module>
    myjit = Machine("x86_32").jitter()
  File "/usr/lib/python2.7/site-packages/miasm2/arch/x86/jit.py", line 50, in __init__
    jitter.__init__(self, ir_x86_32(sp), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/miasm2/jitter/jitload.py", line 214, in __init__
    raise RuntimeError('Unsupported jitter: %s' % jit_type)
RuntimeError: Unsupported jitter: tcc
```

**Comment by itsacoderepo** [comment]
Hi YounesHaj, 

first you need the very specific version of tcc as it is mentioned under https://github.com/cea-sec/miasm#user-content-software-requirements:

```
 To enable code JIT, one of the following module is mandatory:

    GCC
    LLVM v3.2 with python-llvm, see below
    LibTCC tinycc (ONLY version 0.9.26)
```

Second tcc is just annoying. I would rather go with gcc, which works fine on arch. Usually a -j gcc or --jitter gcc is enough for a sandbox.

However jitload.py ignores the flag (read the miasm code and you will know why) but you could make it work with (tcc is default in the jitter constructor):

```
# Init jitter
myjit = Machine("x86_32").jitter(jit_type="gcc")
```
Add a print and you are ready to go. 

```
## Changes must be passed on myjit.cpu instance
assert myjit.cpu.EAX == 4
print myjit.cpu.EAX
```

```
$ python2 jitload.py 
4
```


Best regards
