### ISSUE TITLE
How to use miasm to detect  function behaviour and similar or equivalent  functions ? 

### ISSUE THREAD

**Issue by hackmoonlight** [cea-sec/miasm#403]
I am using miasm for the emulation and symbolic execution of the hexdump of functions extracted by decomposition of binary file , we symbollicaly execute a function to know its inputs and outputs and extracting the mathematic formula of its registers ( ECX , EAX ..) . But how can we Recognize equivalent or similar functions (e.g. functions in statically compiled binaries), deobfuscation, detecting vulnerabilities and malware analysis ?

**Comment by itsacoderepo** [comment]
Hi hackmoonlight,

you don't have a Miasm problem, you have a research problem. 

Best regards

**Comment by serpilliere** [comment]
Hi

Miasm is a reverse engineering Framework. So, for example, it's not a software which can de-obfuscate a program. It's a piece of code which can help you writing a code which can in turn de-obfuscate a program.

For example, if you want to find a vulnerability in a target. Say, you want to spot a format string in a program ([https://www.owasp.org/index.php/Format_string_attack](url)). Maybe you will ask yourself: Ok, I have to find all calls to the `printf` function, and manually analyse them.

Here, `IDA` can help you: it has good heuristics to fully disassemble a program, so it can spot every calls to `printf`. Let say we have 2000 references. Let's take the following hypothesis: you are very lazy, and only want to find very interesting vulnerabilities with only little efforts (this is, as I said, a pure hypothesis).

So you can ask youself: I only want to see `printf` whose first argument doesn't points trivially to a fixed static string. Maybe such a script will automatically filter 990 static `printf` and will spit 10 "interesting" cases (or unresolved cases). Here, you can use the `DependencyGraph` of `Miasm` to track back each `printf` call arguments do this filter.

See?

One of the non trivial part in a framework like Miasm is:
"How the hell does I known the `DependencyGraph` exists and can be used in such a case?!". As you might have noted, there are no documentations after all. 

And here is an answer: Look at the use cases in the examples: there are here to act as showcases, and we built them to this end.

**Comment by commial** [comment]
You may also want to take a look at [Sibyl](https://github.com/cea-sec/sibyl), a function recognition framework based on Miasm

**Comment by hackmoonlight** [comment]
thank you very much for for responding me 
@serpilliere  @commial
