### ISSUE TITLE
Some late commits cause memory mapping error

### ISSUE THREAD

**Issue by mrphrazer** [cea-sec/miasm#417]
Hi, 

I am working on some ELF 64 binaries. Some of the latest commits break my script as follows:

```
[WARNING]: Create dummy entry for 'xxx.dll'
00400546 PUSH       RBP
WARNING: address 0xFFFFFFFFFFFFFFF8 is not mapped in virtual memory:
Traceback (most recent call last):
  File "test.py", line 93, in <module>
    sb.run()
  File "/usr/lib/python2.7/site-packages/miasm2/analysis/sandbox.py", line 481, in run
    super(Sandbox_Linux_x86_64, self).run(addr)
  File "/usr/lib/python2.7/site-packages/miasm2/analysis/sandbox.py", line 127, in run
    self.jitter.continue_run()
  File "/usr/lib/python2.7/site-packages/miasm2/jitter/jitload.py", line 363, in continue_run
    return self.run_iterator.next()
  File "/usr/lib/python2.7/site-packages/miasm2/jitter/jitload.py", line 335, in runiter_once
    assert(self.get_exception() == 0)
AssertionError
```

My script is based on that:

```python
filename = os.environ.get('PYTHONSTARTUP')
if filename and os.path.isfile(filename):
    execfile(filename)
parser = Sandbox_Linux_x86_64.parser(description="ELF sandboxer")
parser.add_argument("filename", help="ELF Filename")
options = parser.parse_args()

sb = Sandbox_Linux_x86_64(options.filename, options, globals())

log_func.setLevel(logging.ERROR)

sb.jitter.jit.log_mn = True
sb.run()

assert (sb.jitter.run is False)
```

The jitter is gcc. In dependence on `sb.jitter.jit.log_mn` it does work or not (on one PC it must be true, on a second PC it must be false). Up until now, creating minimal examples that trigger that behaviour failed (I am not allowed to share the binary.)

**Comment by serpilliere** [comment]
Can you try to flush your cache?
(ie remove the `/tmp/miasm_gcc_cache`, which, by the way, also contains the tcc cache...)

**Comment by mrphrazer** [comment]
great, thanks! it worked immediately. just out of curiosity, do you have any idea what might have been happened there?

**Comment by commial** [comment]
Actually, as the binary you execute did not change, the only thing which change the way GCC cache is retrieved is options.
So depending on the activation of `log_mn`, the `.so` was either recompiled with the last version of Miasm libraries or retrieved from the cache. In this last case, there is a bad link between the `.so` and the expected library API, leading to your bug.

**Comment by itsacoderepo** [comment]
What about this patch for jitcore_gcc.py and jitcore_tcc.py? 

[jitcorepatch.txt](https://github.com/cea-sec/miasm/files/452896/jitcorepatch.txt)

**Comment by serpilliere** [comment]
Erf.
If I understand correctly your patch, it will erase all the cache files before each run.
In fact, I am afraid it will break a desired feature: keeping the cache between many run is a  *great* advantage order to speed up the execution time.


There is trick which could do the job, but I am hesitating to implement it: it will consist in taking the Miasm's revision number in the hash, so the modification of Miasm will give fresh cache files.

But maybe it is a bit overkill.

**Comment by itsacoderepo** [comment]
Yes you're right, my patch is not a good idea, if one wants to keeping the cache. 

How would you query the revision?

Here is a, more cache friendly, solution with a clear_cache flag: 

```
class jitter:
    ...
    def __init__(self, ir_arch, jit_type="tcc", clear_cache=False):
    ...
    self.jit = JitCore(self.ir_arch, self.bs, clear_cache)
    ....
```
```

class JitCore_Gcc(jitcore.JitCore):

    "JiT management, using GCC as backend"

    def __init__(self, ir_arch, bs=None, clear_cache=False):
    ...
        try:
            os.mkdir(self.tempdir, 0755)
            if clear_cache and os.path.exists(self.tempdir): 
                # delete cache files
                fileList = os.listdir(self.tempdir)
                for fileName in fileList:
                    os.remove(self.tempdir+"/"+fileName)
            else:
                os.mkdir(self.tempdir, 0755)
        except OSError:
            pass
        if not os.access(self.tempdir, os.R_OK | os.W_OK):
         
```

**Comment by commial** [comment]
Also, we may don't want to flush the cache on a patch which doesn't affect JiT (which are actually the majority of patches).
Maybe we can introduce a value used in the hash (I have a pending patch which merge redundant code between Tcc and Gcc), which is increased each time a patch broke previous compiled file. That way, one can even conserve patches across different branches.

But I'm not sure this is a very maintainable way. We could also imagine computing a hash of involved files (ie libraries) once at the beginning and using this hash to discriminate caches.

 Currently, I don't see a way to resolved it satisfactorily.

**Comment by serpilliere** [comment]
There is another bad tricky thing:
If you change the *name* of a label in the jitter disassembler between two runs (this is helpful if you want to have the correct name during an emulation trace) in your final script, the emulation will fail as well. For exemple, imagine you jit:

```
CALL loc_000020000
...
loc_000020000:
...
```
and you understand later that 0x200000 is an  ̀AES_decrypt`. You can add the information, but the jitter won't rejit it and will call the new name. Fail.
