### ISSUE TITLE
IR Representation of x86 XCHG instruction seems wrong

### ISSUE THREAD

**Issue by Lukas-Dresel** [cea-sec/miasm#437]
The instruction XCHG EAX, EBX is transformed into IR and results in 
EAX=EBX
EBX=EAX

This looks wrong in terms of logic, and especially this is very confusing when viewing dumped IR graphs.

**Comment by commial** [comment]
As specified in #194, in Miasm IR, lines are evaluated in parallel (for a given AssignBlock, see #330 ).
If you want another representation, you may take a look at #352.

As this is a duplicate, I'm closing this issue. Do not hesitate if you have others questions.
