### ISSUE TITLE
[SH4] getpc() & getsp() does not exist

### ISSUE THREAD

**Issue by guedou** [cea-sec/miasm#480]
The mn_sh4 class does not have the getpc() and getsp() methods. Let me know if you want me to do a PR.

**Comment by guedou** [comment]
This could be a silly issue as their is no `dis_engine()` for SH4. Should I close this issue ?

**Comment by commial** [comment]
As you may have noticed, the `SH4` architecture is not well developed. For now, we just maintain it working.
Unless you have any specific need, complementing it is not really on the roadmap, and then you can close the issue.
