### ISSUE TITLE
Using instruction offset while assembling or disassembling

### ISSUE THREAD

**Issue by guedou** [cea-sec/miasm#483]
Let's imagine that the `YOLO` instruction is defined as a 4-bits prefix (like `1010`) and and a 4-bits immediate.

At offset 0, it is displayed as:
0x0000 YOLO 0x7 -> 1010 0111

At offset 0x2800, it is displayed as:
0x2800 YOLO 0x2807 -> 1010 0111 (<- same binary encoding)

To display `1010 0111` into YOLO 0x2807, I choose to implement the offset computation into the `arg2str()`. It works fine but I am not sure that it is the best way to do it.

Concerning assembling, I did not find a way to do it. Do you think that it is currently possible ?

Thanks.

**Comment by serpilliere** [comment]
Hi

Many architectures use this mecanism. For example, let's take the instruction `JZ` in x86 32 bit:
```python
from miasm2.arch.x86.arch import mn_x86
>>> print mn_x86.dis('7408'.decode('hex'), 32)
JZ         0xA
```

The instruction is described as  0x74 (meaning JZ) and 0x08 which means current address + 0x8 (in fact, in x86, the relative offset is offset + instruction length, so: 0x2 + 0x8 = 0xA) 
In fact the output should be:
```
JZ   $+0xA
```

Let's look at the Instruction description:
```python
addop("j", [bs('0111'), cond, rel_off08])
```

So the RAW disassembly displays the *relative* offset. Now, for convenience, in classic listing, we want to display the absolute address of the jump destination. 
```python
>>> from miasm2.arch.x86.disasm import dis_x86_32
>>> mdis = dis_x86_32(("00"*0x1000+"7408").decode('hex'))
>>> print mdis.dis_bloc(0x1000)
loc_0000000000001000:0x00001000
JZ         loc_000000000000100A:0x0000100a
->      c_next:loc_0000000000001002:0x00001002  c_to:loc_000000000000100A:0x0000100a 
```

The JZ has been modified to `JZ 0x100A`. This job is done in `dstflow2label`. For example in x86:
```python
    def dstflow2label(self, symbol_pool):
        if self.additional_info.g1.value & 6 and self.name in repeat_mn:
            return
        expr = self.args[0]
        if isinstance(expr, ExprId):
            if not isinstance(expr.name, asm_label) and expr not in all_regs_ids:
                raise ValueError("ExprId must be a label or a register")
        elif isinstance(expr, ExprInt):
            ad = expr.arg + int(self.offset)
            l = symbol_pool.getby_offset_create(ad)
            s = ExprId(l, expr.size)
            self.args[0] = s
        else:
            return
```

Which means something like "If the instruction has an argument to fix, replace this argument by $+length+argument".

For the assembly, the function is `fixDstOffset`:
```python
    def fixDstOffset(self):
        expr = self.args[0]
        if self.offset is None:
            raise ValueError('symbol not resolved %s' % l)
        if not isinstance(expr, ExprInt):
            log.warning('dynamic dst %r', expr)
            return
        self.args[0] = ExprInt(int(expr) - self.offset, self.mode)
```


It does the opposite job.

By the way, the addition (and substraction) of the instruction length is done in the encode/decode of the *field* itself (not in the dstflow2label/fixDstOffset). But it's an arbitrary choice.

**Comment by guedou** [comment]
Thanks a lot for this interesting reply !

I helped me to use the following for r2m2:

```python
# Disassembling
mode = machine.dis_engine().attrib
￼instr = machine.mn().dis(buffer, mode)
instr.offset = r2_address
if instr.dstflow():
    instr.dstflow2label(symb_pool)
``` 
```python
# Assembling
mode = machine.dis_engine().attrib
instr = mn.fromstring(str, mode)
instr.offset = r2_address
if instr.offset and instr.dstflow():
    instr.fixDstOffset()
```
