### ISSUE TITLE
Windows setup errors

### ISSUE THREAD

**Issue by pinfred** [cea-sec/miasm#541]
Hi,
Here is log from windows setup:

miasm2/jitter/vm_mngr.c(116) : error C2065: '__BYTE_ORDER' : undeclared identifier
miasm2/jitter/vm_mngr.c(124) : error C2065: '__BYTE_ORDER' : undeclared identifier
miasm2/jitter/vm_mngr.c(132) : error C2065: '__BYTE_ORDER' : undeclared identifier
miasm2/jitter/vm_mngr.c(145) : error C2054: expected '(' to follow 'inline'
miasm2/jitter/vm_mngr.c(146) : error C2085: 'midpoint' : not in formal parameter list
miasm2/jitter/vm_mngr.c(146) : error C2143: syntax error : missing ';' before '{'
miasm2/jitter/vm_mngr.c(156) : warning C4013: 'midpoint' undefined; assuming extern returning int
miasm2/jitter/vm_mngr.c(233) : warning C4244: 'function' : conversion from 'uint64_t' to 'uint16_t', possible loss of data
miasm2/jitter/vm_mngr.c(237) : warning C4244: 'function' : conversion from 'uint64_t' to 'uint32_t', possible loss of data
miasm2/jitter/vm_mngr.c(267) : warning C4244: 'function' : conversion from 'uint64_t' to 'uint16_t', possible loss of data
miasm2/jitter/vm_mngr.c(270) : warning C4244: 'function' : conversion from 'uint64_t' to 'uint32_t', possible loss of data
miasm2/jitter/vm_mngr.c(317) : warning C4244: 'function' : conversion from 'uint64_t' to 'uint16_t', possible loss of data
miasm2/jitter/vm_mngr.c(321) : warning C4244: 'function' : conversion from 'uint64_t' to 'uint32_t', possible loss of data
miasm2/jitter/vm_mngr.c(341) : warning C4244: 'function' : conversion from 'uint64_t' to 'uint16_t', possible loss of data
miasm2/jitter/vm_mngr.c(344) : warning C4244: 'function' : conversion from 'uint64_t' to 'uint32_t', possible loss of data
miasm2/jitter/vm_mngr.c(570) : warning C4244: '=' : conversion from 'uint64_t' to 'unsigned char', possible loss of data
miasm2/jitter/vm_mngr.c(577) : warning C4244: '=' : conversion from 'uint64_t' to 'unsigned short', possible loss of data
miasm2/jitter/vm_mngr.c(584) : warning C4244: '=' : conversion from 'uint64_t' to 'unsigned int', possible loss of data
miasm2/jitter/vm_mngr.c(619) : error C2036: 'void *' : unknown size
miasm2/jitter/vm_mngr.c(642) : error C2036: 'void *' : unknown size
miasm2/jitter/vm_mngr.c(701) : warning C4244: '=' : conversion from 'uint64_t' to 'unsigned char', possible loss of data
miasm2/jitter/vm_mngr.c(704) : warning C4244: '=' : conversion from 'uint64_t' to 'unsigned short', possible loss of data
miasm2/jitter/vm_mngr.c(786) : warning C4244: 'return' : conversion from 'int64_t' to 'int', possible loss of data
miasm2/jitter/vm_mngr.c(793) : warning C4244: 'return' : conversion from 'int64_t' to 'int', possible loss of data
miasm2/jitter/vm_mngr.c(878) : warning C4244: '=' : conversion from 'uint64_t' to 'unsigned int', possible loss of data
miasm2/jitter/vm_mngr.c(881) : warning C4244: 'return' : conversion from 'uint64_t' to 'unsigned int', possible loss of data
miasm2/jitter/vm_mngr.c(896) : warning C4244: '=' : conversion from 'uint64_t' to 'unsigned int', possible loss of data
miasm2/jitter/vm_mngr.c(899) : warning C4244: 'return' : conversion from 'uint64_t' to 'unsigned int', possible loss of data
miasm2/jitter/vm_mngr.c(907) : warning C4334: '<<' : result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
miasm2/jitter/vm_mngr.c(918) : warning C4018: '<' : signed/unsigned mismatch
miasm2/jitter/vm_mngr.c(919) : warning C4334: '<<' : result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
miasm2/jitter/vm_mngr.c(1223) : error C2169: 'fabs' : intrinsic function, cannot be defined
miasm2/jitter/vm_mngr.c(1264) : warning C4244: 'return' : conversion from '__int64' to 'unsigned int', possible loss of data
miasm2/jitter/vm_mngr.c(1399) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
miasm2/jitter/vm_mngr.c(1628) : warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data
miasm2/jitter/vm_mngr.c(1713) : warning C4018: '<' : signed/unsigned mismatch

Regards

**Comment by pinfred** [comment]
The easy ones 👍 
miasm2/jitter/vm_mngr.c(145) : error C2054: expected '(' to follow 'inline'
miasm2/jitter/vm_mngr.c(146) : error C2085: 'midpoint' : not in formal parameter list
miasm2/jitter/vm_mngr.c(146) : error C2143: syntax error : missing ';' before '{'
miasm2/jitter/vm_mngr.c(156) : warning C4013: 'midpoint' undefined; assuming extern returning int

can be resolved just by replacing inline by _inline


fabs must have another name (fabs2 ?)

**Comment by greenozon** [comment]
@pinfred   I guess this issue should be closed as the issue was solved some time ago on Windows...

**Comment by serpilliere** [comment]
close due to #629
