### ISSUE TITLE
Building Miasm and Debian with TCC fails

### ISSUE THREAD

**Issue by shiftre** [cea-sec/miasm#561]
```
deb@debian [12:08:51 PM] [~/miasm] [master]
-> % sudo python setup.py install
building
build with 'all'
running install
running build
running build_py
running build_ext
building 'miasm2.jitter.Jittcc' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c miasm2/jitter/Jittcc.c -o build/temp.linux-x86_64-2.7/miasm2/jitter/Jittcc.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/miasm2/jitter/Jittcc.o -ltcc -o build/lib.linux-x86_64-2.7/miasm2/jitter/Jittcc.so
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libtcc.a(libtcc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libtcc.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
SystemExit("error: command 'x86_64-linux-gnu-gcc' failed with exit status 1",)
build with 'notcc'
running install
running build
running build_py
running build_ext
running install_lib
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/Miasm-2.0.egg-info
Writing /usr/local/lib/python2.7/dist-packages/Miasm-2.0.egg-info
build notcc

********************************************************************************
Warning: TCC is not properly installed,
Miasm will be installed without TCC Jitter
Etheir install TCC or use LLVM jitter
********************************************************************************

build/lib.linux-x86_64-2.7
```

I'm using Debian Jessie, tcc linking fails 

any hints?

Considering this is directly from the branch you mentioned : )

**Comment by commial** [comment]
Hi shiftre, 
Don't worry, unless you specifically want TCC, this error is normal. It just indicates that Miasm has been built without the support of TCC. 

For some historical reason (TCC was mandatory), it is out as an error, but I do agree that it should only be a warning. 
You can check your install through `test_all.py`

**Comment by shiftre** [comment]
Can you share a bit about the usage of Clang/TCC in miasm?

**Comment by serpilliere** [comment]
Yes of course!

To emulate code, `Miasm` translates the native assembly into the intermediate language (basic block by basic block). Then, it uses one of its backend:
* gcc (or tcc): it translates this intermediate language in C, then compiles it and executes the fresh function to emulate the native code behavior.
* llvm: it translates the intermediate language in llvm bytecode, then compiles it and executes the fresh function as well
* python: the intermediate language is interpreted in python to emulate the code behaviour.


So if you don't have TCC, it doesn't really matter: you can use gcc or llvm or python to do code emulation.

This is very close to what do `qemu` (in emulation mode): it has an in intermediate language as well (`TCG`) and generate native code which simulate the behavior of the target.
 By the way, `Miasm` intermediate language is close to `TCG`.

Tell me if you have more questions, or if I am not clear in this explanations.

**Comment by commial** [comment]
We may write a blog post on this, including a note on which engine best fit which use case.

**Comment by serpilliere** [comment]
Can we close this issue?

**Comment by shiftre** [comment]
yeah
