### ISSUE TITLE
Standard library calls handling

### ISSUE THREAD

**Issue by vinatgit** [cea-sec/miasm#572]
Hi. Is there a way to handle standard library calls made by a binary? 
I cannot seem to disassemble the function directly from miasm.

**Comment by commial** [comment]
Hi @vinatgit,

Sorry for the delay, I'm not quite sure to fully understand the question.
If you use the `Sandbox` objects (as `example/jitter/sandbox_pe_x86_32.py`), Miasm will parse the import table and fill it with dummy addresses. At these addresses, breakpoints will be set. When these breakpoints are reached, a function named "{DLL name}_{Function name}" is seek and called.

For instance, this is how `GetProcAddress` is simulated in `example/jitter/unpack_upx.py`. Some functions are already implemented, have a look at `miasm2/os_dep`.
