### ISSUE TITLE
error in disassemble arm64

### ISSUE THREAD

**Issue by jigerd** [cea-sec/miasm#599]
When I disassemble some arm64 instruction use "b=machine.dis_engine(Container.from_string(s).bin_stream).dis_multibloc(0)"
the s is:

**Comment by serpilliere** [comment]
Hi!
It seems this code is a jump table. Miasm disassembler does not handle them natively. For the moment, it's up to the user to do code analysis in order to discover dynamic branches. Maybe one day it will be included in Miasm :smile:  !

**Comment by jigerd** [comment]
@serpilliere 
Is there some examples to me or give some suggestions, that i can know how to continue disassemble when I discover the branches.
