### ISSUE TITLE
Manually adding live variables when using dead_simp()?

### ISSUE THREAD

**Issue by newgre** [cea-sec/miasm#608]
Is there an easy way to tell the dead code elimination mechanism (dead_simp()) that a certain set of registers should be considered live, e.g., at the exit block?

consider this short snippet of code:

```
push ecx
xor [rsp], eax
pop ecx
jmp rax
```

When invoking dead_simp on this code, miasm will optimize away the store to _ecx_ caused by the pop instruction. That is actually expected, since by the end of the block, _ecx_ is in fact dead.

Could I work around this somehow? For instance, by declaring _ecx_ live at the end of the block?

**Comment by commial** [comment]
Hi @newgre,

Currently, the `dead_simp` pass uses IRAnalysis's `get_out_regs` (https://github.com/cea-sec/miasm/blob/master/miasm2/analysis/data_flow.py#L220) method to get elements to considered live at exit blocks.

For instance, in x86, the return register and the stack register are considered live at the exit block (https://github.com/cea-sec/miasm/blob/4f5206dd8774a82ed2c864f4e6fe2d512f9d4408/miasm2/arch/x86/ira.py#L15).

So, you just have to override this method in a custom IRA object to specify what you want to keep (knowing the targeted block through arguments), and use this object with `dead_simp`.

Don't hesitate if you need any additionnal precision.

**Comment by newgre** [comment]
Hi @commial ,

thanks for answering. I wonder though, isn't that change a bit invasive, and, for myuse case, a bit too inflexible? IIUC, that would mean that *any* block will have _ecx_ live at the end of it. 
That's not quite what I'm trying to achieve, what I want instead is to control this on a case-by-case basis. For example, depending on some condition, some other register needs to be considered live at the end of a block, i.e., something like:

```
if cond == 1:
  dead_simp(%consider ecx live at the exit block only%)
elif cond == 2:
  dead_simp(%consider ebx live at the exit block only%)
```

Also note that above snippet could be the final block in a huge control flow graph where _ecx_ or _ebx_ would be used a lot for dead stores, i.e., in those blocks _dead_simp()_ should in fact remove those instructions (but not in the final block).

**Comment by commial** [comment]
Not sure to fully understand what do you mean, but the method `get_out_regs` has the current block under analysis as argument, so you can decide which registers are considered to be live based on that (and then, obtain a case-by-case analysis) :)

**Comment by newgre** [comment]
Thanks, didn't realize that `get_out_regs` takes the current block as a parameter. Will give it a try!
