### ISSUE TITLE
Installation errors and problems

### ISSUE THREAD

**Issue by nihuai** [cea-sec/miasm#629]
1.Installation  python-dev
![image](https://user-images.githubusercontent.com/22935890/31991358-29152626-b9aa-11e7-91ba-a03a14c1a903.png)

2.python-modules：
Python32 and python64，All have to install？

3.LLVM versions：
As of version 0.21.0, llvmlite requires LLVM 5.0
miasm Based on how many versions?
LLVM version 5.0 and llvmlite-0.21.0？

4.JIT 
Clang and LLVM
Only install these two？

**Comment by serpilliere** [comment]
Hi!

Miasm doesn't support native windows installation for the moment, but it can be installed using the Windows Subsystem for linux (You may need a Windows 10).
Some previous issues are linked to your problem: #541 and #161

**Comment by nihuai** [comment]
thank you
How to solve the other problems? 2-4

**Comment by serpilliere** [comment]
As I said, native windows installation is not supported, so I am afraid I cannot fully answer the question  :cold_sweat:
