### ISSUE TITLE
concrete execute libc functions

### ISSUE THREAD

**Issue by tiedaoxiaotubie** [cea-sec/miasm#638]
In the concept of concolic execution,sometimes I want to execute libc functions or system call with concrete value instead of symbolic value,at that time,I just want to make binary go on execute when encounter libc/sys_call,and I don't want to collect the constrains in those functions.
    I want to pass concrete parameter to libc functions,obtaining return value of libc function by real execute the function instead of using simulate procedure since writing simulate procedure of every export function is very hard.How can I manage to do that using miasm?

**Comment by commial** [comment]
Hi,

From what I understand, there are 2 questions here:
* during a concolic execution using the DSE module, the symbolic execution engine is always called before the concrete one for a given address. So, when you encounter a fake import address:
1. the jitter callback is called, which tell the DSE engine the new PC
2. the DSE engine detects the new PC is a fake address and try to call a symbolic handler
3. the jitter engine detects a breakpoint is registered on this address, and call it: this is where the fake concrete API is called
4. the fake handler modify PC, so the block is not retrieved / executed. The process restart from 1. instead

If you want another behavior, you have to decide (and implement) how the symbolic engine should retrieve new information after the concrete handler (what about memory writes, symbolic arguments, ...?).
* To avoid libc simulation, you can map it and do the loader work to let your code call the right function. You may have to simulate a few syscall, but probably not too much. This is a solution I never test, but this is already done for PE

**Comment by tiedaoxiaotubie** [comment]
why I have to simulate a few syscall since miasm support syscall emulation in its document?
besides,is there any example that shows how to add special hook to handle unmapped memory access like unicorn does?

**Comment by commial** [comment]
> why I have to simulate a few syscall since miasm support syscall emulation in its document?

I'm not sure to see where the "documentation" of Miasm stands that syscall emulation is already supported.
Moreover, for now, the semantic of the instruction syscall is (from `x86/sem.py`):
```Python
def l_syscall(_, instr):
    e = []
    e.append(m2_expr.ExprAff(exception_flags,
                             m2_expr.ExprInt(EXCEPT_PRIV_INSN, 32)))
    return e, []
```
Which only raise an exception.
Some work is needed to handle these exception, get back the syscall number and associated arguments.
What is already emulated in Miasm is a few libs API, such as `memcpy`.

> besides,is there any example that shows how to add special hook to handle unmapped memory access like unicorn does?

When an unmapped memory access occurs, an exception  `EXCEPT_ACCESS_VIOL` is set on the `VmMngr` object.
You can handle it using the `add_exception_handler` callback (on jitter), using something like:
```Python
from miasm2.jitter.csts import EXCEPT_ACCESS_VIOL
        
def callback(jitter):
        # Do something
        ...
        # Clear exception flag
        jitter.vm.set_exception(jitter.vm.get_exception() ^ EXCEPT_ACCESS_VIOL)
        # Let the execution continue
        return True
jitter.add_exception_handler(EXCEPT_ACCESS_VIOL, callback)
```

**Comment by commial** [comment]
You can now do exactly this kind of things (ie, fully running the libc and only stubbing syscalls). You can have have a look to the `jitter/run_with_linux_env.py` example, and more generally, the `miasm2.os_dep.linux` sub-module
