### ISSUE TITLE
Is possible memory access breakpoint on jitter?

### ISSUE THREAD

**Issue by kismp123** [cea-sec/miasm#639]
Hi again.

is possible memory access breakpoint on jitter? 
memory watch exists on debug mode. but jitter don't exists.

below is from jitloader.py(execute breakpoint). 
```
    def add_breakpoint(self, addr, callback):
        """Add a callback associated with addr.
        @addr: breakpoint address
        @callback: function with definition (jitter instance)
        """
        self.breakpoints_handler.add_callback(addr, callback)
        self.jit.add_disassembly_splits(addr)
        # De-jit previously jitted blocks
        self.jit.updt_automod_code_range(self.vm, [(addr, addr)])
```

I want to script or do something on runtime. any possible solution? 
Thank you always.

**Comment by commial** [comment]
Hi,

There is an API [`jitter.vm.add_memory_breakpoint`](https://github.com/cea-sec/miasm/blob/master/miasm2/jitter/vm_mngr_py.c#L625). You have an example of use in a [regression test](https://github.com/cea-sec/miasm/blob/master/test/jitter/test_post_instr.py), or in the [debugger implementation](https://github.com/cea-sec/miasm/blob/master/miasm2/analysis/debugging.py#L93)

**Comment by kismp123** [comment]
Thank you!
