### ISSUE TITLE
Python3 compatibility?

### ISSUE THREAD

**Issue by pfalcon** [cea-sec/miasm#650]
Were there any thoughts about subj?

A first step towards could be as simple as starting to use `print` as a function:

~~~
from __future__ import print_function
print("use me as a function")
~~~

I found 565 hits for the statement print in the codebase, that alone is a big nuisance for someone who might be interested in python3 support.

Thanks.

**Comment by serpilliere** [comment]
We have to switch to python3 one day. We are discussing this point to choose the good option with @p-l- who has some expertise with this.

**Comment by p-l-** [comment]
@serpilliere I'd rather say experiences than expertise ;-)

**Comment by fishilico** [comment]
Hello, are there any news on this subject?
For information, a recent version of `pip` added a deprecation warning about Python 2.7's End of Life (on 2020-01-01), https://github.com/pypa/pip/blob/04f1e70427fd392e1a68c13174816b1b21f48baa/src/pip/_internal/cli/base_command.py#L148-L158. This could mean than installing miasm's dependencies will become harder new year, if it has not migrated to Python 3.

Also, for the more practical aspect of things, Fedora 30 dropped `python2-z3` package in favor of `python3-z3` (cf. https://src.fedoraproject.org/rpms/z3/c/9257eb278f0353c184d5f68286fe4df7b6a0e504). This means that it won't be possible to use both z3 and miasm in the same Python script when Fedora 30 will be released.

**Comment by serpilliere** [comment]
Hi!
Yes, this is exactly the kind of signs we were waiting for:
We don't want to support python2 AND python3 as having a tool supporting both languages seems a bit hard to maintain (@p-l-  has great experience return of experience from scapy at this point)

We were waiting for classic "stable releases" of different OSes to fully support pyhton3.

Another point is that we have some PR which are still written in python2 to merge, so we will merge them *before* translating in python3

And after this, we will push a PR to fully swtich Miasm to python3

**Comment by serpilliere** [comment]
Hum. Interesting remark from  @p-l-: "IDA does not support python3"
So maybe we will have to support both python2 and python3.
