### ISSUE TITLE
RuntimeError: Unsupported jit arch: x86

### ISSUE THREAD

**Issue by APlus123** [cea-sec/miasm#651]
OS enviroment:
OS: Ubuntu 16.04 amd64 (in VMware)
LLVM version: LLVM 5.0 ,llvm-5.0-dev
g++ version:　g++ -5.4.0
python version: Python 2.7.12
LibTCC: tinycc  0.9.26
Miasm version: 1ef1c50  (the lastest version)
    Below is the terminal log ，when I initializing the Jit engine with a stack, it throws an error, and I use Machine("x86_32") , the same error occurs ! 
   But if I run "python /home/hack/miasm_env/miasm/test/jitter/jitload.py ", there is no error for jitload.py , Waitting for your reply ,thanks!

>>> s = '\x8dI\x04\x8d[\x01\x80\xf9\x01t\x05\x8d[\xff\xeb\x03\x8d[\x01\x89\xd8\xc3'
>>> from miasm2.analysis.machine import Machine
>>> myjit = Machine("x86_64").jitter(jit_type='python')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "miasm2/arch/x86/jit.py", line 189, in __init__
    jitter.__init__(self, ir_x86_64(sp), *args, **kwargs)
  File "miasm2/jitter/jitload.py", line 194, in __init__
    raise RuntimeError('Unsupported jit arch: %s' % arch_name)
RuntimeError: Unsupported jit arch: x86

**Comment by commial** [comment]
Hi @APlus123,

You probably have run your script in the `miasm` folder, or forgot to setup build Miasm.
As some modules must be compiled, the `setup.py build` step is needed, in addition to using the built Python module (for the `*.so` to be present).

**Comment by APlus123** [comment]
Hi @commial ,
Much appreciated to your kind reply and your excellent project, I've solved this problem. Due to the wrong path, I've ran my script in the miasm folder, while I run my script in the ./miasm/miasm2/jitter folder ,everything goes well !
