### ISSUE TITLE
Data segment on x86_16

### ISSUE THREAD

**Issue by nastypuma** [cea-sec/miasm#704]
Hi ! I'm a new user of miasm. Currently, I'm trying to emulate the first stage of a simple bootloader on x86 arch.

Even if I activated segmentation, miasm seems to be lost when the jitter tries to access memory referenced by DS.

Here is the gist where the code is displayed by IDA, displayed/emulated by Miasm and the Python script I wrote :  https://gist.github.com/nastypuma/7139a09b8438346f66febb2153cf69b3

Once again, I'm new to miasm, so maybe I'm not using it correctly.

**Comment by serpilliere** [comment]
Hi!
Glad to hear from a new Miasm user :smile: 
Before starting, here is a short description of Miasm segmentation mecanism. If you enable segmentation, each memory lookup has the following form in intermediate representation:
```
mov [EAX], 12 => @32[segm(ds, eax)] = 12
xor EAX, [EBX+ESI] => EAX = EAX ^ @32[segm(ds, ebx + esi)]
and special case:
mov [ESP+12], 12 => @32[segm(ss, esp + 12)] = 12
```
And Miasm does exactly the same thing in 16 bit.
But what does the operator  `segm` in Miasm? (which is used in 16 or 32 bit):
- it takes its first parameter (the segment)
- get its corresponding segment descriptor in the CPU
- get its base address
- add this base address to the memory address.

And we are done with segmentation.

Now, if we look at the *real* segmentation mecanism in 16 bit, this is totally different. It does:
```
mov [AX], 12 => mov word ptr [(ds << 4) + ax], 
```

Here is the problem in your script:
- you set ds value to 4
- you set the base address for the corresponding entry '4' to 0x7c00

which seems ok for now.
But the first thing your bootloader is doing is resetting the DS to 0x7c0. In Miasm we get:
```
mov [AX], 12 => @16[(ds << 4) + ax], 12
```
As `ds` is 0x7C0, Miasm search the base address of the segment number 0x7c0, which has not been initialized, and uses the default address 0.


So now I think you can see the "trick" to support such a code: you have to write for each segment entry, the corresponding base adress computed like on 16 bit segmentation:
```python
for i in xrange(0x1000):
   myjit.cpu.set_segm_base(i, i << 4)
```

Now, when the code erases `DS` with 0x7c0, the mov becomes:
```
@16[segm(ds, ax)] = 12
```
which gives:
```
@16[segm(0x7c0, ax)] = 12
```
which gives:
```
@16[0x7c00 + ax], 12
```

which is the same result as in 16 bit segmentation :smile: 


Is it ok for you?

I admit this is not trivial. Maybe one day, I may patch this to make the 16 bit segmentation code directly convert the code to the  `(ds << 4) + addr` to make things cleaner.

Happy 16 bit jit!

**Comment by serpilliere** [comment]
Can I close the issue?

**Comment by nastypuma** [comment]
Yes !
Thanks a lot :)
