### ISSUE TITLE
Comparisons for AsmLabel

### ISSUE THREAD

**Issue by Mizari** [cea-sec/miasm#705]
Hello!

Could you, please, implement comparisons (equality, le, ge) for AsmLabel? This way users can use dictionaries for them. Right now I've got this: "<AsmLabel 'loc_0000000000000008' > != <AsmLabel 'loc_0000000000000008' >"

Edit: also this would get fixed, I think:  
ira.blocks are: {<AsmLabel 'loc_0000000000000008' >: <miasm2.ir.ir.IRBlock object at 0x7f57fbbae8c0>, <AsmLabel 'loc_0000000000000000' >: <miasm2.ir.ir.IRBlock object at 0x7f57fbb5c370>}
type(dst_label) is <class 'miasm2.core.asmblock.AsmLabel'>
dst_label ==  loc_0000000000000008:0x00000008

but
del ira.blocks[dst_label]
raises this:
KeyError: <AsmLabel 'loc_0000000000000008' >

**Comment by serpilliere** [comment]
Hi!


In fact, the AsmLabel is close to the singleton pattern. There are some rules for them:
- You must not talk about AsmLabel (ok this one is a bad joke)
- You have to create them *only* by using the corresponding symbol pool.
- You must not create label using yourself `AsmLabel(...)`
- You must not use label created in a symbol pool in a different symbol pool.

If you apply those rules, you won't have any strange behaviour like before.

Note: We are currently have a brain storming (more or less) on this and the way Miasm handle label in IR. So this may change in a near future, and this kind of thing won't be anymore.

**Comment by serpilliere** [comment]
Ok, so maybe yoy have created a new `symbol_pool` implicitely: Can you give us you init code? For example, in `full.py', we have:
```python
machine = Machine(arch)
mn, dis_engine = machine.mn, machine.dis_engine
ira, ir = machine.ira, machine.ir
...
mdis = dis_engine(bs, symbol_pool=cont.symbol_pool)
...
    ir_arch = ir(mdis.symbol_pool)
    ir_arch_a = ira(mdis.symbol_pool)
```

If you don't give `ira` a `symbol_pool`, it will generate one, which will be different from the one in `dis_engine`

**Comment by serpilliere** [comment]
The `symbol_pool` is a kind of symbol manager: it keeps informations on labels, their names and thier offset.
It enforces some rules which are (erf):
- two different label cannot have the same offset
- two different label cannot have the same name
- given a `symbol_pool`, each manipulated label have been created by this `symbol_pool`

**Comment by Mizari** [comment]
```
m = Machine('x86_64')

c = miasm2.analysis.binary.Container.from_string(code)

mdis = m.dis_engine(c.bin_stream)

blocks = mdis.dis_multiblock(0)

ira = m.ira()
```
Like in examples, so yeah, implicit symbol pool. Constructing ira the way you showed seems to remove all problems I had. Thanks!
