### ISSUE TITLE
CMPXCHG is incorrect

### ISSUE THREAD

**Issue by Mizari** [cea-sec/miasm#711]
Hello, I've met the following problem:

One of additional blocks for "cmpxchg dword [rbp + rbx], ecx" instruction have these assigns:
cmpxchg block at lbl_gen_00000000:None
dst <class 'miasm2.expression.expression.ExprId'> zf
src <class 'miasm2.expression.expression.ExprInt'> 0x0
**dst <class 'miasm2.expression.expression.ExprId'> RAX
src <class 'miasm2.expression.expression.ExprCompose'> {@32[RBP + RBX] 0 32, RAX[32:64] 32 64}**
dst <class 'miasm2.expression.expression.ExprId'> IRDst
src <class 'miasm2.expression.expression.ExprId'> loc_0000000000000006:0x00000006

Notice the highlighted one: RAX's higher part here should be zeroed, not stay the same.

**Comment by serpilliere** [comment]
Hi!

The #712 should fix the issue.
Are you ok with it?

**Comment by commial** [comment]
Fixed by #712, please re-open if it didn't.
