### ISSUE TITLE
Bad assign generation

### ISSUE THREAD

**Issue by Mizari** [cea-sec/miasm#761]
Hello!

Instruction "pop qword ptr [rsp + 0x8]" produces assign "@64[RSP + 0x8 + 0x8] = @64[RSP]". It would be better to produce "@64[RSP + 0x10] = @64[RSP]" here.

Thanks

**Comment by serpilliere** [comment]
Hi!
Yes, the default Miasm IR may *not* be in the most simplified form.
Anyway, here is a patch to manage this case:#764

**Comment by commial** [comment]
Fixed, thanks for reporting
