### ISSUE TITLE
Readme out of date

### ISSUE THREAD

**Issue by Frky** [cea-sec/miasm#775]
The examples given in the readme file seem to be out of date: when iterating over blocks, I have the following error: 

```
>>> blocks = mdis.dis_multiblock(0)
>>> for block in blocks:
...  pass
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "miasm2/core/asmblock.py", line 637, in __iter__
    raise RuntimeError("DEPRECATED")
RuntimeError: DEPRECATED

```

Also, is it normal that the link to clone Miasm repo refers to serpillere's repo instead of cea-sec (line 443)?

**Comment by commial** [comment]
Done, thanks again!
