### ISSUE TITLE
Replace hardcoded program name with first -c string when --mimic-env is provided

### ISSUE THREAD

**Issue by PAFsec** [cea-sec/miasm#785]
Hi guys,

First, thank you for your work.

In the sandbox context, it would be conveniant to directly have the first **argv** pointer pointing to the first value given via the  **-c** option, and, if inexistant, then provide the default hardcoded _PROGRAM_PATH_ value.

So far, the only way to actually pass it is :

```
sb.PROGRAM_PATH = 'something'
sb.run(START_ADDR)
```

which **does not work** as the sandbox has already been initialized with the filling of its parameter **self.argv**.

Hence my dirty hack:
```
cl = map(lambda x: str.replace(x, "./program", sb.fname), sb.argv)
```
and then putting them on the stack.

What do you think ?

Have a good day.

**Comment by serpilliere** [comment]
Hi!

Can't you set the PROGRAM_PATH directly on the Class? I mean before the instanciation of it?

Something like:
```python
Sandbox_Win_x86_32.PROGRAM_PATH = ...
sb = Sandbox_Win_x86_32..
```

**Comment by serpilliere** [comment]
Time out :)
