### ISSUE TITLE
Troubles installing miasm FW on native windows 7

### ISSUE THREAD

**Issue by PavelKotov1** [cea-sec/miasm#792]
Greetings everybody!
I am really new to the subject, so please just bear with me. 
I am trying to install miasm and keep having troubles.
Here is the result of my running "python setup.py build" :
building
build with 'all'
running build
running build_py
creating build
creating build\lib.win-amd64-2.7
creating build\lib.win-amd64-2.7\miasm2
copying miasm2\__init__.py -> build\lib.win-amd64-2.7\miasm2
creating build\lib.win-amd64-2.7\miasm2\arch
copying miasm2/arch\__init__.py -> build\lib.win-amd64-2.7\miasm2/arch
creating build\lib.win-amd64-2.7\miasm2\arch\x86
copying miasm2/arch/x86\arch.py -> build\lib.win-amd64-2.7\miasm2/arch/x86
copying miasm2/arch/x86\ctype.py -> build\lib.win-amd64-2.7\miasm2/arch/x86
copying miasm2/arch/x86\disasm.py -> build\lib.win-amd64-2.7\miasm2/arch/x86
copying miasm2/arch/x86\ira.py -> build\lib.win-amd64-2.7\miasm2/arch/x86
copying miasm2/arch/x86\jit.py -> build\lib.win-amd64-2.7\miasm2/arch/x86
copying miasm2/arch/x86\regs.py -> build\lib.win-amd64-2.7\miasm2/arch/x86
copying miasm2/arch/x86\sem.py -> build\lib.win-amd64-2.7\miasm2/arch/x86
copying miasm2/arch/x86\__init__.py -> build\lib.win-amd64-2.7\miasm2/arch/x86
creating build\lib.win-amd64-2.7\miasm2\arch\arm
copying miasm2/arch/arm\arch.py -> build\lib.win-amd64-2.7\miasm2/arch/arm
copying miasm2/arch/arm\disasm.py -> build\lib.win-amd64-2.7\miasm2/arch/arm
copying miasm2/arch/arm\ira.py -> build\lib.win-amd64-2.7\miasm2/arch/arm
copying miasm2/arch/arm\jit.py -> build\lib.win-amd64-2.7\miasm2/arch/arm
copying miasm2/arch/arm\regs.py -> build\lib.win-amd64-2.7\miasm2/arch/arm
copying miasm2/arch/arm\sem.py -> build\lib.win-amd64-2.7\miasm2/arch/arm
copying miasm2/arch/arm\__init__.py -> build\lib.win-amd64-2.7\miasm2/arch/arm
creating build\lib.win-amd64-2.7\miasm2\arch\aarch64
copying miasm2/arch/aarch64\arch.py -> build\lib.win-amd64-2.7\miasm2/arch/aarch64
copying miasm2/arch/aarch64\disasm.py -> build\lib.win-amd64-2.7\miasm2/arch/aarch64
copying miasm2/arch/aarch64\ira.py -> build\lib.win-amd64-2.7\miasm2/arch/aarch64
copying miasm2/arch/aarch64\jit.py -> build\lib.win-amd64-2.7\miasm2/arch/aarch64
copying miasm2/arch/aarch64\regs.py -> build\lib.win-amd64-2.7\miasm2/arch/aarch64
copying miasm2/arch/aarch64\sem.py -> build\lib.win-amd64-2.7\miasm2/arch/aarch64
copying miasm2/arch/aarch64\__init__.py -> build\lib.win-amd64-2.7\miasm2/arch/aarch64
creating build\lib.win-amd64-2.7\miasm2\arch\msp430
copying miasm2/arch/msp430\arch.py -> build\lib.win-amd64-2.7\miasm2/arch/msp430
copying miasm2/arch/msp430\ctype.py -> build\lib.win-amd64-2.7\miasm2/arch/msp430
copying miasm2/arch/msp430\disasm.py -> build\lib.win-amd64-2.7\miasm2/arch/msp430
copying miasm2/arch/msp430\ira.py -> build\lib.win-amd64-2.7\miasm2/arch/msp430
copying miasm2/arch/msp430\jit.py -> build\lib.win-amd64-2.7\miasm2/arch/msp430
copying miasm2/arch/msp430\regs.py -> build\lib.win-amd64-2.7\miasm2/arch/msp430
copying miasm2/arch/msp430\sem.py -> build\lib.win-amd64-2.7\miasm2/arch/msp430
copying miasm2/arch/msp430\__init__.py -> build\lib.win-amd64-2.7\miasm2/arch/msp430
creating build\lib.win-amd64-2.7\miasm2\arch\sh4
copying miasm2/arch/sh4\arch.py -> build\lib.win-amd64-2.7\miasm2/arch/sh4
copying miasm2/arch/sh4\regs.py -> build\lib.win-amd64-2.7\miasm2/arch/sh4
copying miasm2/arch/sh4\__init__.py -> build\lib.win-amd64-2.7\miasm2/arch/sh4
creating build\lib.win-amd64-2.7\miasm2\arch\mips32
copying miasm2/arch/mips32\arch.py -> build\lib.win-amd64-2.7\miasm2/arch/mips32
copying miasm2/arch/mips32\disasm.py -> build\lib.win-amd64-2.7\miasm2/arch/mips32
copying miasm2/arch/mips32\ira.py -> build\lib.win-amd64-2.7\miasm2/arch/mips32
copying miasm2/arch/mips32\jit.py -> build\lib.win-amd64-2.7\miasm2/arch/mips32
copying miasm2/arch/mips32\regs.py -> build\lib.win-amd64-2.7\miasm2/arch/mips32
copying miasm2/arch/mips32\sem.py -> build\lib.win-amd64-2.7\miasm2/arch/mips32
copying miasm2/arch/mips32\__init__.py -> build\lib.win-amd64-2.7\miasm2/arch/mips32
creating build\lib.win-amd64-2.7\miasm2\arch\ppc
copying miasm2/arch/ppc\arch.py -> build\lib.win-amd64-2.7\miasm2/arch/ppc
copying miasm2/arch/ppc\disasm.py -> build\lib.win-amd64-2.7\miasm2/arch/ppc
copying miasm2/arch/ppc\ira.py -> build\lib.win-amd64-2.7\miasm2/arch/ppc
copying miasm2/arch/ppc\jit.py -> build\lib.win-amd64-2.7\miasm2/arch/ppc
copying miasm2/arch/ppc\regs.py -> build\lib.win-amd64-2.7\miasm2/arch/ppc
copying miasm2/arch/ppc\sem.py -> build\lib.win-amd64-2.7\miasm2/arch/ppc
copying miasm2/arch/ppc\__init__.py -> build\lib.win-amd64-2.7\miasm2/arch/ppc
creating build\lib.win-amd64-2.7\miasm2\core
copying miasm2/core\asmbloc.py -> build\lib.win-amd64-2.7\miasm2/core
copying miasm2/core\asmblock.py -> build\lib.win-amd64-2.7\miasm2/core
copying miasm2/core\asm_ast.py -> build\lib.win-amd64-2.7\miasm2/core
copying miasm2/core\bin_stream.py -> build\lib.win-amd64-2.7\miasm2/core
copying miasm2/core\bin_stream_ida.py -> build\lib.win-amd64-2.7\miasm2/core
copying miasm2/core\cpu.py -> build\lib.win-amd64-2.7\miasm2/core
copying miasm2/core\ctypesmngr.py -> build\lib.win-amd64-2.7\miasm2/core
copying miasm2/core\graph.py -> build\lib.win-amd64-2.7\miasm2/core
copying miasm2/core\interval.py -> build\lib.win-amd64-2.7\miasm2/core
copying miasm2/core\locationdb.py -> build\lib.win-amd64-2.7\miasm2/core
copying miasm2/core\objc.py -> build\lib.win-amd64-2.7\miasm2/core
copying miasm2/core\parse_asm.py -> build\lib.win-amd64-2.7\miasm2/core
copying miasm2/core\sembuilder.py -> build\lib.win-amd64-2.7\miasm2/core
copying miasm2/core\types.py -> build\lib.win-amd64-2.7\miasm2/core
copying miasm2/core\utils.py -> build\lib.win-amd64-2.7\miasm2/core
copying miasm2/core\__init__.py -> build\lib.win-amd64-2.7\miasm2/core
creating build\lib.win-amd64-2.7\miasm2\expression
copying miasm2/expression\expression.py -> build\lib.win-amd64-2.7\miasm2/expression
copying miasm2/expression\expression_helper.py -> build\lib.win-amd64-2.7\miasm2/expression
copying miasm2/expression\expression_reduce.py -> build\lib.win-amd64-2.7\miasm2/expression
copying miasm2/expression\modint.py -> build\lib.win-amd64-2.7\miasm2/expression
copying miasm2/expression\parser.py -> build\lib.win-amd64-2.7\miasm2/expression
copying miasm2/expression\simplifications.py -> build\lib.win-amd64-2.7\miasm2/expression
copying miasm2/expression\simplifications_common.py -> build\lib.win-amd64-2.7\miasm2/expression
copying miasm2/expression\simplifications_cond.py -> build\lib.win-amd64-2.7\miasm2/expression
copying miasm2/expression\smt2_helper.py -> build\lib.win-amd64-2.7\miasm2/expression
copying miasm2/expression\__init__.py -> build\lib.win-amd64-2.7\miasm2/expression
creating build\lib.win-amd64-2.7\miasm2\ir
copying miasm2/ir\analysis.py -> build\lib.win-amd64-2.7\miasm2/ir
copying miasm2/ir\ir.py -> build\lib.win-amd64-2.7\miasm2/ir
copying miasm2/ir\symbexec.py -> build\lib.win-amd64-2.7\miasm2/ir
copying miasm2/ir\symbexec_top.py -> build\lib.win-amd64-2.7\miasm2/ir
copying miasm2/ir\symbexec_types.py -> build\lib.win-amd64-2.7\miasm2/ir
copying miasm2/ir\__init__.py -> build\lib.win-amd64-2.7\miasm2/ir
creating build\lib.win-amd64-2.7\miasm2\ir\translators
copying miasm2/ir/translators\C.py -> build\lib.win-amd64-2.7\miasm2/ir/translators
copying miasm2/ir/translators\miasm.py -> build\lib.win-amd64-2.7\miasm2/ir/translators
copying miasm2/ir/translators\python.py -> build\lib.win-amd64-2.7\miasm2/ir/translators
copying miasm2/ir/translators\smt2.py -> build\lib.win-amd64-2.7\miasm2/ir/translators
copying miasm2/ir/translators\translator.py -> build\lib.win-amd64-2.7\miasm2/ir/translators
copying miasm2/ir/translators\z3_ir.py -> build\lib.win-amd64-2.7\miasm2/ir/translators
copying miasm2/ir/translators\__init__.py -> build\lib.win-amd64-2.7\miasm2/ir/translators
creating build\lib.win-amd64-2.7\miasm2\analysis
copying miasm2/analysis\binary.py -> build\lib.win-amd64-2.7\miasm2/analysis
copying miasm2/analysis\cst_propag.py -> build\lib.win-amd64-2.7\miasm2/analysis
copying miasm2/analysis\data_analysis.py -> build\lib.win-amd64-2.7\miasm2/analysis
copying miasm2/analysis\data_flow.py -> build\lib.win-amd64-2.7\miasm2/analysis
copying miasm2/analysis\debugging.py -> build\lib.win-amd64-2.7\miasm2/analysis
copying miasm2/analysis\depgraph.py -> build\lib.win-amd64-2.7\miasm2/analysis
copying miasm2/analysis\disasm_cb.py -> build\lib.win-amd64-2.7\miasm2/analysis
copying miasm2/analysis\dse.py -> build\lib.win-amd64-2.7\miasm2/analysis
copying miasm2/analysis\expression_range.py -> build\lib.win-amd64-2.7\miasm2/analysis
copying miasm2/analysis\gdbserver.py -> build\lib.win-amd64-2.7\miasm2/analysis
copying miasm2/analysis\machine.py -> build\lib.win-amd64-2.7\miasm2/analysis
copying miasm2/analysis\modularintervals.py -> build\lib.win-amd64-2.7\miasm2/analysis
copying miasm2/analysis\sandbox.py -> build\lib.win-amd64-2.7\miasm2/analysis
copying miasm2/analysis\__init__.py -> build\lib.win-amd64-2.7\miasm2/analysis
creating build\lib.win-amd64-2.7\miasm2\os_dep
copying miasm2/os_dep\common.py -> build\lib.win-amd64-2.7\miasm2/os_dep
copying miasm2/os_dep\linux_stdlib.py -> build\lib.win-amd64-2.7\miasm2/os_dep
copying miasm2/os_dep\win_32_structs.py -> build\lib.win-amd64-2.7\miasm2/os_dep
copying miasm2/os_dep\win_api_x86_32.py -> build\lib.win-amd64-2.7\miasm2/os_dep
copying miasm2/os_dep\win_api_x86_32_seh.py -> build\lib.win-amd64-2.7\miasm2/os_dep
copying miasm2/os_dep\__init__.py -> build\lib.win-amd64-2.7\miasm2/os_dep
creating build\lib.win-amd64-2.7\miasm2\jitter
copying miasm2/jitter\codegen.py -> build\lib.win-amd64-2.7\miasm2/jitter
copying miasm2/jitter\csts.py -> build\lib.win-amd64-2.7\miasm2/jitter
copying miasm2/jitter\emulatedsymbexec.py -> build\lib.win-amd64-2.7\miasm2/jitter
copying miasm2/jitter\jitcore.py -> build\lib.win-amd64-2.7\miasm2/jitter
copying miasm2/jitter\jitcore_cc_base.py -> build\lib.win-amd64-2.7\miasm2/jitter
copying miasm2/jitter\jitcore_gcc.py -> build\lib.win-amd64-2.7\miasm2/jitter
copying miasm2/jitter\jitcore_llvm.py -> build\lib.win-amd64-2.7\miasm2/jitter
copying miasm2/jitter\jitcore_python.py -> build\lib.win-amd64-2.7\miasm2/jitter
copying miasm2/jitter\jitload.py -> build\lib.win-amd64-2.7\miasm2/jitter
copying miasm2/jitter\llvmconvert.py -> build\lib.win-amd64-2.7\miasm2/jitter
copying miasm2/jitter\__init__.py -> build\lib.win-amd64-2.7\miasm2/jitter
creating build\lib.win-amd64-2.7\miasm2\jitter\arch
copying miasm2/jitter/arch\__init__.py -> build\lib.win-amd64-2.7\miasm2/jitter/arch
creating build\lib.win-amd64-2.7\miasm2\jitter\loader
copying miasm2/jitter/loader\elf.py -> build\lib.win-amd64-2.7\miasm2/jitter/loader
copying miasm2/jitter/loader\pe.py -> build\lib.win-amd64-2.7\miasm2/jitter/loader
copying miasm2/jitter/loader\utils.py -> build\lib.win-amd64-2.7\miasm2/jitter/loader
copying miasm2/jitter/loader\__init__.py -> build\lib.win-amd64-2.7\miasm2/jitter/loader
copying miasm2\jitter\JitCore.h -> build\lib.win-amd64-2.7\miasm2\jitter
copying miasm2\jitter\op_semantics.h -> build\lib.win-amd64-2.7\miasm2\jitter
copying miasm2\jitter\queue.h -> build\lib.win-amd64-2.7\miasm2\jitter
copying miasm2\jitter\vm_mngr.h -> build\lib.win-amd64-2.7\miasm2\jitter
copying miasm2\jitter\vm_mngr_py.h -> build\lib.win-amd64-2.7\miasm2\jitter
copying miasm2\jitter\arch\JitCore_aarch64.h -> build\lib.win-amd64-2.7\miasm2\jitter\arch
copying miasm2\jitter\arch\JitCore_arm.h -> build\lib.win-amd64-2.7\miasm2\jitter\arch
copying miasm2\jitter\arch\JitCore_mips32.h -> build\lib.win-amd64-2.7\miasm2\jitter\arch
copying miasm2\jitter\arch\JitCore_msp430.h -> build\lib.win-amd64-2.7\miasm2\jitter\arch
copying miasm2\jitter\arch\JitCore_ppc32.h -> build\lib.win-amd64-2.7\miasm2\jitter\arch
copying miasm2\jitter\arch\JitCore_ppc32_regs.h -> build\lib.win-amd64-2.7\miasm2\jitter\arch
copying miasm2\jitter\arch\JitCore_x86.h -> build\lib.win-amd64-2.7\miasm2\jitter\arch
running build_ext
building 'miasm2.jitter.VmMngr' extension
creating build\temp.win-amd64-2.7
creating build\temp.win-amd64-2.7\Release
creating build\temp.win-amd64-2.7\Release\miasm2
creating build\temp.win-amd64-2.7\Release\miasm2\jitter
D:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\bin\HostX64\x64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Python27\PC /Tcmiasm2/jitter/vm_mngr.c /Fobuild\temp.win-amd64-2.7\Release\miasm2/jitter/vm_mngr.obj
vm_mngr.c
d:\miasm\miasm2\jitter\vm_mngr.h(196): error C2146: syntax error: missing ')' before identifier 'src'
d:\miasm\miasm2\jitter\vm_mngr.h(196): error C2081: '__uint128_t': name in formal parameter list illegal
d:\miasm\miasm2\jitter\vm_mngr.h(196): error C2061: syntax error: identifier 'src'
d:\miasm\miasm2\jitter\vm_mngr.h(196): error C2059: syntax error: ';'
d:\miasm\miasm2\jitter\vm_mngr.h(196): error C2059: syntax error: ')'
d:\miasm\miasm2\jitter\vm_mngr.h(202): error C2061: syntax error: identifier 'vm_MEM_LOOKUP_128'
d:\miasm\miasm2\jitter\vm_mngr.h(202): error C2059: syntax error: ';'
d:\miasm\miasm2\jitter\vm_mngr.h(202): error C2059: syntax error: '<parameter-list>'
miasm2/jitter/vm_mngr.c(82): error C2065: '__BYTE_ORDER': undeclared identifier
miasm2/jitter/vm_mngr.c(90): error C2065: '__BYTE_ORDER': undeclared identifier
miasm2/jitter/vm_mngr.c(98): error C2065: '__BYTE_ORDER': undeclared identifier
miasm2/jitter/vm_mngr.c(104): error C2061: syntax error: identifier 'set_endian128'
miasm2/jitter/vm_mngr.c(104): error C2059: syntax error: ';'
miasm2/jitter/vm_mngr.c(104): error C2059: syntax error: '<parameter-list>'
miasm2/jitter/vm_mngr.c(169): error C2061: syntax error: identifier 'memory_page_read'
miasm2/jitter/vm_mngr.c(169): error C2059: syntax error: ';'
miasm2/jitter/vm_mngr.c(169): error C2059: syntax error: '<parameter-list>'
miasm2/jitter/vm_mngr.c(264): error C2146: syntax error: missing ')' before identifier 'src'
miasm2/jitter/vm_mngr.c(264): error C2081: '__uint128_t': name in formal parameter list illegal
miasm2/jitter/vm_mngr.c(264): error C2061: syntax error: identifier 'src'
miasm2/jitter/vm_mngr.c(264): error C2059: syntax error: ';'
miasm2/jitter/vm_mngr.c(264): error C2059: syntax error: ')'
miasm2/jitter/vm_mngr.c(265): error C2449: found '{' at file scope (missing function header?)
miasm2/jitter/vm_mngr.c(352): error C2059: syntax error: '}'
miasm2/jitter/vm_mngr.c(485): warning C4013: 'memory_page_write' undefined; assuming extern returning int
miasm2/jitter/vm_mngr.c(504): error C2146: syntax error: missing ')' before identifier 'src'
miasm2/jitter/vm_mngr.c(504): error C2081: '__uint128_t': name in formal parameter list illegal
miasm2/jitter/vm_mngr.c(504): error C2061: syntax error: identifier 'src'
miasm2/jitter/vm_mngr.c(504): error C2059: syntax error: ';'
miasm2/jitter/vm_mngr.c(504): error C2059: syntax error: ')'
miasm2/jitter/vm_mngr.c(505): error C2449: found '{' at file scope (missing function header?)
miasm2/jitter/vm_mngr.c(508): error C2059: syntax error: '}'
miasm2/jitter/vm_mngr.c(521): warning C4013: 'memory_page_read' undefined; assuming extern returning int
miasm2/jitter/vm_mngr.c(538): error C2061: syntax error: identifier 'vm_MEM_LOOKUP_128'
miasm2/jitter/vm_mngr.c(538): error C2059: syntax error: ';'
miasm2/jitter/vm_mngr.c(538): error C2059: syntax error: '<parameter-list>'
miasm2/jitter/vm_mngr.c(570): error C2036: 'void *': unknown size
miasm2/jitter/vm_mngr.c(593): error C2036: 'void *': unknown size
miasm2/jitter/vm_mngr.c(837): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
miasm2/jitter/vm_mngr.c(922): warning C4018: '<': signed/unsigned mismatch
SystemExit("error: command 'D:\\\\Program Files (x86)\\\\Microsoft Visual Studio\\\\2017\\\\Professional\\\\VC\\\\Tools\\\\MSVC\\\\14.12.25827\\\\bin\\\\HostX64\\\\x64\\\\cl.exe' failed with exit status 2",)
============
or with a different tool chain:
_**raise ValueError(str(list(resul.keys()))
ValueError: [u'path', u'include', u'lib']**_

Like I said I am very new in this area and am lost trying to interpret this output.
My O/S is Windows 7 SP1, 64-bit.
 Python 2.7.13 (v 2.7.13, Dec 17 2017, 14:24:46) [MSC v.1500 64 bit (AMD64)] on win32 
using the latest miasm version cloned from github, Z3, elfesteem, pyparsing are in place.

If any additional info is needed, I would be happy to provide it.
Hope somebody could help me!
Thanks in advance!

**Comment by serpilliere** [comment]
Hi!

Sadly, Miasm is not supported on native windows yet!
However, you can use it using Linux sub system on windows 10.

**Comment by PavelKotov1** [comment]
Thanks for the answer!
Is windows native support somewhere in the foreseeable future?
And what about Ubuntu or kali under VMware? Any hidden obstacles to watch out for?

**Comment by commial** [comment]
Hi,
As stated in few recent issues, we are not working on a native windows support yet. However, we have hope to have it working with a decent installation of LLVM. Actually, the recent introduction of WSL (Windows Sub-Linux) and its pretty forward miasm installation made the native Windows support less of a priority.
Regarding Miasm on a VM (ubuntu / kali / etc.), it should works like a charm.
Regarding Miasm on FreeBSD, it should work, but I'm not 100% confident it will. I know it have been tested on a few BSD, but I don't know for FreeBSD.

I'm closing this issue, if you have any trouble with FreeBSD, please open a dedicated issue.
