### ISSUE TITLE
pip version is outdated/broken

### ISSUE THREAD

**Issue by 0xgalz** [cea-sec/miasm#813]
Hello

I tried running the examples on your pip version of miasm and it seems it's a bit outdated,
miasm2.core.locationdb.LocationDB class doesn't exist in the version and none of the examples work :+1: 

could you update it so others won't have the same problem i had?

**Comment by commial** [comment]
Hello,
Actually, we do not support pip installation (yet).
The supported way is described in the README, using "setup.py install" on dependencies (ie, elfesteem) and on miasm2.
