### ISSUE TITLE
Incorrect compilation

### ISSUE THREAD

**Issue by Mizari** [cea-sec/miasm#862]
instr = mn_x86.fromstring("DEC EBX", 64)
mn_x86.asm(instr)
results in ['K', '\xff\xcb', 'gK', 'B\xff\xcb', 'g\xff\xcb', 'gB\xff\xcb']
'K' doesnt look correct byte representation of this instruction

**Comment by serpilliere** [comment]
Correct!
I will fix this to remove DEC/INC in 64 mode
Thank you!

**Comment by serpilliere** [comment]
I pushed #863, it should fix this.
Thanks for the bug reporting, and sorry for the delay !
