### ISSUE TITLE
Support for Windows Driver jitting

### ISSUE THREAD

**Issue by mp-ssi** [cea-sec/miasm#877]
Hi dear Miasm developpers !

I am opening this question since I have tried to jit a packed Windows driver, and encountered some issues.

I am taking this binary as a reference for discussion, which is from a known rootkit family (see [online white paper](https://artemonsecurity.com/uroburos.pdf)): `50edc955a6e8e431f5ecebb5b1d3617d3606b8296f838f0f986a929653d289ed`

The issues I had so far:

* Stack VM base address is 0x13000 and collides with a section from the binary (patching Miasm hardcoded offset solves this)
* When loading other drivers (e.g. `tdi.sys` or `ndis.sys`), I also had VM addresses collisions
* The `MOV CR0, EAX` could not be jitted at `loc_a610c` because of `CR0`

So, is Miasm able to handle driver jitting, and if yes, what kind of APIs would you pick to manage it ?

Thank you very much for your help !

**Comment by serpilliere** [comment]
Hi!

For the moment, Miasm does not rebase any binary. So you will have a collision with the default stack address. We may add one day the binary rebasing in Miasm.

But for now, there are multiple solution:
* you can change the default stack base address in the sandbox class
* you can rebase your target using a pe fixer before running it in Miasm.

For the `cr0`, you are right, there will be a problem. We will add the mov from/to crX as privileged instruction in the future. Thus, we will only have to handle privileged instruction exception in your script, like any other breakpoint for example.

For now, it's a bit ugly: If you have few mov from/to cr0, and the addresses of those instruction are fixed, you can add "manually" breakpoint on them, and do some stuff in your script, so forward eip and resume execution.

This is a hack, but it may help you in some cases!

Anyway, we already faced this and did the bad hack. But the things above are on the todo list :smiley:

**Comment by mp-ssi** [comment]
Hi again! 

Thank you very much for your answer.
Bad hacks are fair enough ;-) I will go for it.

Cheers !

**Comment by commial** [comment]
Please, do not hesitate to reopen if you need more help :-)
