### ISSUE TITLE
creation of a slack channel

### ISSUE THREAD

**Issue by enkomio** [cea-sec/miasm#881]
What about creating a slack channel were to ask for help? The current documentation unfortunately is not very helpful to who want to start.

Having a channel were to ask for help would be very helpful.

**Comment by Evilcry** [comment]
Sounds a great idea, one of the problems that blocks people from using miasm is the steep initial learning curve in my experience.

**Comment by commial** [comment]
Another cea_sec project, [IVRE](https://github.com/cea-sec/ivre), is using gitter. So we'll probably give a try to it, does it seem OK for you?

**Comment by enkomio** [comment]
Yes, gitter is perfectly fine too.

**Comment by commial** [comment]
Done, right here: https://gitter.im/cea-sec/miasm
