### ISSUE TITLE
Aarch64: BICS instruction, 'res' variable not assigned.

### ISSUE THREAD

**Issue by su-vikas** [cea-sec/miasm#901]
In arch/aarch64/sem.py, line 294, for BICS instruction, 'res' variable is not assigned.

**Comment by serpilliere** [comment]
Hi!
The #902 should fix the problem!
I have tested it, its seems ok (except the carry flag, which is not computed here. todo)

**Comment by commial** [comment]
Should be fixed, please re-open if not.

Thanks for the report
