### ISSUE TITLE
REP instruction prefix not supported

### ISSUE THREAD

**Issue by nofiv** [cea-sec/miasm#927]
The issue is displayed in [rep_movsd.txt](https://github.com/cea-sec/miasm/files/2749644/rep_movsd.txt). It looks as if REP prefix wasn't supported at all in the fromstring method(https://github.com/cea-sec/miasm/blob/master/miasm2/arch/x86/arch.py#L671) and as if byte '\xf3' was automatically considered to be REPE prefix(https://github.com/cea-sec/miasm/blob/master/miasm2/arch/x86/arch.py#L551). However it could be also REP prefix(https://c9x.me/x86/html/file_module_x86_id_279.html).

**Comment by serpilliere** [comment]
Hi!
I agree with you: In Miasm it seems the `REP` and `REPE` are aliases at the moment :disappointed: 
Globally, their are a lot of alias/shortcut/divergence... in every architectures.
