### ISSUE TITLE
Test fails with include error on Debian sid

### ISSUE THREAD

**Issue by trou** [cea-sec/miasm#94]
```
$ python test_all.py -m
[...]
[TEST/ARCH] Running tests on x86/unit/mn_strings.py ...                                                                    ERROR
In file included from <string>:12:
In file included from /usr/include/python2.7/Python.h:33:
/usr/include/stdio.h:33: error: include file 'stddef.h' not found
Erreur de compilation !
[...]
```
Probable valid paths  : 
```
libgcc-4.9-dev:amd64: /usr/lib/gcc/x86_64-linux-gnu/4.9/include/stddef.h
libgcc-4.8-dev:amd64: /usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h
```

**Comment by trou** [comment]
It's probably a bug in the  `load` hack that uses `cc` to find include dirs.

**Comment by trou** [comment]
On one of my debian sid systems,  `cc -Wp,-v -E -` includes `/usr/include/x86_64-linux-gnu` but not on the other... it appears to be the source of the problem.

**Comment by commial** [comment]
I've tried to reproduce the issue thanks to Docker.

On March 2nd:
```
$ docker pull debian:sid
$ docker build -t "miasm:sid"
```

I used [this Dockerfile](https://github.com/serpilliere/miasm-docker/blob/master/base/Dockerfile), just by replacing `jessie` by `sid` (to be sure).

After building, I got:
```
$ cat /etc/debian_version 
8.0
$ python test_all.py
                                                              Miasm2 Regression tests
===============================================================================

Current mode: Multiprocessing
Nb CPU detected: 4

===============================================================================
Success rate: 96/96
```

Currently, we consider that if an installation is working with the minimal version of a particular distribution (using Docker), it should be working on this particular distribution. If it is not, it seems to be related to a user specific configuration.

Can you look for any specificities ?

**Comment by trou** [comment]
Bleh. Permission error on tcc path in /usr/local :( sorry for the noise.
