### ISSUE TITLE
instruction_x86.b does not send back the right bytes

### ISSUE THREAD

**Issue by hegusung** [cea-sec/miasm#95]
Hi,

Here is an little example :

$python
>>> from miasm2.arch.x86.arch import mn_x86
>>> inst = mn_x86.dis('\x65\xc7\x00\x09\x00\x00\x00', 32, 0)
>>> inst.b
'\xc7\x00\t\x00\x00\x00'
>>> inst.l
7

We can see the 0x65 byte is ignored in inst.b whereas inst.l still send back the correct value.

Is it an issue or just normal behavior?

**Comment by commial** [comment]
Thanks for your bug report !

With #113:
```Python
>>> from miasm2.arch.x86.arch import mn_x86
>>> inst = mn_x86.dis('\x65\xc7\x00\x09\x00\x00\x00', 32, 0)
>>> inst.b
'e\xc7\x00\t\x00\x00\x00'
>>> inst.l
7
```
