### ISSUE TITLE
x86 : Disasm_Exception : stmxcsr

### ISSUE THREAD

**Issue by hegusung** [cea-sec/miasm#96]
Hi,

I'm trying to use miasm on the libc, however it seems strmxcst instruction isn't supported by miasm

mn_x86.dis("\x0f\xae\x5c\x24\x0c", 32, 0) 
# a Disasm_Exception occurs

thanks,

**Comment by commial** [comment]
Thanks to PR #97:
```Python
>>> print Machine("x86_32").mn.dis("\x0f\xae\x5c\x24\x0c", 32, 0)
STMXCSR    DWORD PTR [ESP+0xC]
```

Thanks for reporting !
