### ISSUE TITLE
Sandbox only seems to be mapping the .text section for an ELF

### ISSUE THREAD

**Issue by hax0kartik** [cea-sec/miasm#982]
Hey, 
I have written a [script](https://gist.github.com/hax0kartik/d43579891e110a32900d3cf8b6349801) which allows me to load a function from a 3ds ELF(ARMv6, proprietary OS). I have hacked around the arml_Linux sandbox to make it load the binary and most of it seems to work, aside from the fact that miasm only seems to be mapping the .text section of the elf and is not mapping the .rodata section which is also present. [Here](https://cdn.discordapp.com/attachments/356378491375190016/547638281286844437/newslist.elf.gz) is the link to the elf which you can load in IDA(no symbols). 
Any help is appreciated!

**Comment by hax0kartik** [comment]
Apparently the region was being mapped at 0x9A0 bytes ahead. I fixed it temporarily by using get_mem and set_mem

**Comment by BlackLuny** [comment]
@hax0kartik Could share the script?The link you present may something wrong?
