### ISSUE TITLE
Simplified Error

### ISSUE THREAD

**Issue by J4ckKn1ght** [cea-sec/miasm#997]
When I try to test IR simplify in disassembly example full.py, it is has an error when simplify at entry_point
Binary: [quarkslab.elf](https://github.com/Toizi/deobfuscate_cfg_flattening/blob/master/samples/quarkslab.elf)

> D:\Miasm\miasm\example\disasm>python full.py D:\nkn\sample\quarkslab.elf -g -s -y  -x -z -i
INFO : Load binary
INFO : ok
INFO : import machine...
INFO : ok
INFO : func ok 0000000000400460 (0)
INFO : generate graph file
INFO : generate intervals
[0x400460 0x40048B]
INFO : build img
cannot import python PIL imaging
INFO : total lines 0
INFO : generating IR and IR analysis
INFO : generating IR... 400460
INFO : Print blocks (without analyse)
INFO : Gen Graph... 400460
INFO : Print blocks (with analyse)
INFO : Simplify...
INFO : ok...
Traceback (most recent call last):
  File "full.py", line 357, in <module>
    ircfg = simplifier.simplify(ircfg_a, head)
  File "full.py", line 341, in simplify
    ssa = self.do_simplify_loop(ssa, head)
  File "C:\Python27\lib\site-packages\miasm\analysis\simplifier.py", line 281, in do_simplify_loop
    modified = self.do_simplify(ssa, head)
  File "full.py", line 335, in do_simplify
    modified = super(CustomIRCFGSimplifierSSA, self).do_simplify(ssa, head)
  File "C:\Python27\lib\site-packages\miasm\analysis\simplifier.py", line 271, in do_simplify
    return super(IRCFGSimplifierSSA, self).simplify(ssa, head)
  File "C:\Python27\lib\site-packages\miasm\analysis\simplifier.py", line 31, in ret_func
    modified = func(self, ircfg, head)
  File "C:\Python27\lib\site-packages\miasm\analysis\simplifier.py", line 69, in simplify
    modified |= simplify_pass(ircfg, head)
  File "C:\Python27\lib\site-packages\miasm\analysis\simplifier.py", line 31, in ret_func
    modified = func(self, ircfg, head)
  File "C:\Python27\lib\site-packages\miasm\analysis\simplifier.py", line 221, in do_propagate_int
    modified |= del_unused_edges(ssa.graph, set([head]))
  File "C:\Python27\lib\site-packages\miasm\analysis\data_flow.py", line 1507, in del_unused_edges
    block = ircfg.blocks[node]
KeyError: <LocKey 28>

**Comment by serpilliere** [comment]
Hi!

Yep, here is the bug: as you didn't provide an address, `full.py` will use the entry point as default disasm address. This function in a classic elf (it's the case here) is a simple call to the initialization of the libc, which is a function which does not return.
![graph_exec](https://user-images.githubusercontent.com/9433661/54084652-b88aad80-4333-11e9-93fb-9234eb79aae0.png)


So the analyzed graph is "incomplete": it ends on an un disasm block, which mess the IR simplifier.

This is not the first time someone disclose this bug: we will try in the future to patch the simplifier to accept "incomplete" graphs.
![graph_irflow](https://user-images.githubusercontent.com/9433661/54084653-be808e80-4333-11e9-814d-5b05b371c675.png)



ps: by the way, maybe you want to try to analyse the main or the target function, at address 0x400550) which is a complete function, which is supported by the simplifier
```
python2 example/disasm/full.py -g -p -x -y -z     quarkslab.elf    0x400550
```
which gives:
![final](https://user-images.githubusercontent.com/9433661/54084742-cd1b7580-4334-11e9-97bc-b6b397634caf.png)

**Comment by serpilliere** [comment]
Ho, just a side note:
It seems the propagation is not fully done here: 
```
loc_400574:
    RCX.1 = zeroExt_64(var_4)
    var1 = var4
    IRDst = (RCX.1[0:32] == 0x8DEA83B5) ? (XXX, YYY)
```
the `RCX.1` in the `IRDst` equation should be replaced by `zeroExt_64(var_4)`. The slice and zero extention should cancel and give a cleaner code:
```
IRDst = (var_4 == 0x8DEA83B5) ? (XXX, YYY)
```

**Comment by serpilliere** [comment]
In fact, it's not a simplifier miss: we don't recall the simplifier after transforming detected local stack vars.. so they are not propagated.
Here is the final graph if we also propagate local vars:
![final](https://user-images.githubusercontent.com/9433661/54103568-318a1380-43cd-11e9-97fd-3df42ae68fb5.png)

**Comment by serpilliere** [comment]
Maybe we can do some more tricks. I *think* we can simplify (if var1 & var2 are on 32bits):
```
(signedExt_64(var1) * signedExt_64(var2))[:32]
```
to
```
var1 * var2
```

**Comment by J4ckKn1ght** [comment]
Thanks you very much for your supporting. Propagate(int, mem, expr) is only apply for ssa. How can I apply for ircfg after replace stack vars?

**Comment by serpilliere** [comment]
The PR #1168  has been merged, and you can now do propagation of expressions without the generation of local vars (which was buggy)
```
python2 miasm/example/disasm/full.py -g -p -x  -z     quarkslab.elf    0x400550
```
which gives:
![final](https://user-images.githubusercontent.com/9433661/84156305-a1bc9480-aa69-11ea-986a-7a3874b053d5.png)

You have an example on how to do multiple transformation in ssa here: https://github.com/cea-sec/miasm/blob/6faf83fe27bbfc7fec501d9b674480f02edea854/miasm/analysis/simplifier.py#L314

Feel free to reopen this issue!
